### ISSUE TITLE
Suggestion: UI element to renice

### ISSUE THREAD

**Issue by SteveDavidson** [mackworth/cTiVo#321]
For those of us with under-powered Macs who want to get some work done while encoding is going on, renice is our friend (setting cTiVo and spawned processes to reduced priority — I usually use 15). Most people are probably unfamiliar with how to do that and would benefit from a checkbox in the Preferences that set a reduced priority for cTiVo and spawned processes.  Just a thought that might help a few people.

**Comment by mackworth** [comment]
Not a bad idea. 

Q: I haven’t looked into it, but do you know how one renices the main app?

**Comment by mackworth** [comment]
Okay, I guess I'm not getting to this one, so I'm going to close this for now.
