### ISSUE TITLE
Suggestion: Prioritize Download Queue Order by Status/ExpireDate

### ISSUE THREAD

**Issue by bradbamford** [mackworth/cTiVo#328]
I find myself manually manipulating the Download Queue by moving items that will be deleted from TiVo soon (yellow exclamation status) to the top of the Download Priority so they can be completed first, before newer recording with a Green status. Otherwise, they wouldn't be be downloaded in time before TiVo deletes them.

It would be nice if this was an **option** to automate this.

**Comment by mackworth** [comment]
I looked at this for a bit, and didn't quite see the problem. If you're using subscriptions, then recently added shows would be automatically downloaded after older ones. And if you're doing it manually and are concerned about expiration, then dragging them on top of older ones doesn't seem very hard.
