### ISSUE TITLE
cTivo consistently crashing chrome

### ISSUE THREAD

**Issue by loudneighbor** [mackworth/cTiVo#334]
This is repeatable.  Mac Mini (late 2012), OS X 10.12.6, Chrome 69.0.3497.100, cTivo 3.1.2
When using more than 1 concurrent encoders cTivo freezes Chrome.
Yeah, I know, don't use more than one encoder.
Anyway, using Safari or Firefox doesn't appear to have the same conflicts.

Thought you should know.... p.s. I do like cTivo.

**Comment by mackworth** [comment]
Interesting difference. So, when it goes back to one encoder, does Chrome recover?

**Comment by loudneighbor** [comment]
Yes, it appears to work fine.  With 2 encoders Chrome often gets very slow or just plain catatonic, so I scale back to 1 encoder, reboot Chrome, seems to work fine.  Writing this from Chrome as 1 encoder is chunking in the background.

**Comment by mackworth** [comment]
Ok, so this is really about cTiVo using up too much of the CPU, and Chrome not handling that well.  As I have an issue about optionally lowering cTIVo's priority to leave more CPU for the foreground apps, I'm going to close this issue, but I am aware of the problem.

**Comment by loudneighbor** [comment]
Hi, Hugh,
Thanks for your response.
I like using cTivo, seems to have fewer issues than KTTMG.The latter has been acting up in the past year - suspect some cable company tweaks give it fits.
Anyway, nice work.
Cheers,
-Alex 

    On Thursday, September 27, 2018, 11:10:39 AM MDT, Hugh Mackworth <notifications@github.com> wrote:  
 
 
Ok, so this is really about cTiVo using up too much of the CPU, and Chrome not handling that well. As I have an issue about optionally lowering cTIVo's priority to leave more CPU for the foreground apps, I'm going to close this issue, but I am aware of the problem.
