### ISSUE TITLE
Closed captioning is scrambled

### ISSUE THREAD

**Issue by MikeRich88** [mackworth/cTiVo#338]
I am getting scrambled closed captioning - letters are missing or transposed. It's somewhat readable, but definitely messed up. Watching the show directly on the TiVo works fine.

Device: TiVo BOLT
Source: OTA
Software: cTiVo 3.2.0 beta

This happens regardless of the format that I use.

As troubleshooting, I am going to download the program stream directly from the TiVo, run tivodecode on  it, and then see if the captioning is screwed up there. This will tell us where the problem is more specifically.

**Comment by mackworth** [comment]
This is a known issue in ccextractor and TiVo:  https://github.com/CCExtractor/ccextractor/issues/136
