### ISSUE TITLE
Timing out trying to reach TiVo

### ISSUE THREAD

**Issue by mrfusiontm** [mackworth/cTiVo#339]
This suddenly started happening the other day and its a problem with the current stable version as well as the Beta2.  I've rebooted my machine, my network, the TiVo and the Ethernet adaptor its connected to.  My machine has no problem getting to the Internet, the TiVo has no problem getting to the Internet.  They are both on the same network.  When I start up ctivo, it says "Updating Living Room" for a bit then stops.  Nothing shows up in the TiVo show list.  Here's a verbose log, perhaps there's a clue in there as to the connection issue?

[com.cTiVo.cTiVo 2018-10-26--12-06-04-382.log](https://github.com/mackworth/cTiVo/files/2519102/com.cTiVo.cTiVo.2018-10-26--12-06-04-382.log)

**Comment by mrfusiontm** [comment]
You can close this.  I left it alone for a day and without doing anything, it suddenly showed up again.
I hate network weirdness......

**Comment by mackworth** [comment]
Not terribly surprising. Any network glitches get amplified with the frequency of updates and the lengthy downloads that cTiVo does.  FYI, all the log really says is "timed out".
