### ISSUE TITLE
using zfs file systems

### ISSUE THREAD

**Issue by capcasady** [mackworth/cTiVo#344]
Macos 10.13 with open zfs external file systems broken.  Finding space available Using the NSURLVolumeAvailableCapacityKey works but using the ..important and ...opportunistic variations does not.  They apparently are not supported by ZFS but give a value of zero and not an error so ctivo thinks they are low on space and won't use them.

**Comment by mackworth** [comment]
Thanks for the simultaneous report, diagnosis, and fix; that's great.
I've put in a fall-back check using ..CapacityKey for the next beta. Let me know if it works.

**Comment by capcasady** [comment]
sounds good I will check it   eventually

**Comment by mackworth** [comment]
Let me know if beta3 fixes this for you.

**Comment by mackworth** [comment]
Did Beta 3 help on this?

**Comment by mackworth** [comment]
Well, I'll assume it does. Let me know otherwise.

**Comment by capcasady** [comment]
Sorry be so long in replying but I was on vacation for all of December.
The beta 3 version does indeed work fine with a zfs file system.
Thanks for the work
