### ISSUE TITLE
File naming errors

### ISSUE THREAD

**Issue by gespensen** [mackworth/cTiVo#346]
I have been getting a lot of file naming errors. I use the Plex naming convention. While cTiVo will name an episode as SEAL Team - S02E07 - Outside the Wire.mp4 I get a lot of episodes named SEAL Team - 2018-11-21 - Parallax.mp4. The naming error is not limited to one TV Show but is happening to other TV Shows and more frequently. While checking the episode details it always has the correct episode number listed as in the example SEAL Team - 2018-11-21 - Parallax.mp4 has the Episode Number : S02E08.  
cTiVo Version Version: 3.1.2 (857)
Mac OS Version: 10.13.6 (17G65)

**Comment by mackworth** [comment]
Thanks for reporting it. There are two paths to cTiVo getting notified of a show. In one API, the episode number is known to be reported incorrectly by TiVo (and nowadays, usually just empty). I ran some simulations in my head, and I think you've found a timing problem. When cTiVo finds a new show through the older API, it checks the subscription and also validates the episode information through the RPC API. The subscription then creates a download, and depending on the queue status, the download starts (which is when the filename is created). So if the RPC info hasn't come back soon enough, then the download would use the old episode info (probably empty), so the filename defaults to the first shown date. A split second later, the UI would be updated anyways to show the correct episode info, but it's too late for the download. This seems to match your symptoms, and is feasible with current code path.

So, I'll have to think about where to wait for the RPC data to arrive. Either delay subscription check, or hold off creating a download, or hold off launching the download. This is complicated by the fact that some TiVos don't provide the RPC data, and sometimes the RPC data doesn't come back at all. (Let's just say there's a lot of code in cTiVo checking and working around TiVo bugs in an API they don't really support anymore.)

**Comment by mackworth** [comment]
So, give beta 3 a try. If there's no RPC info, then it delays launching the download.  A bit hard to test, so let me know if it fixed it for you.

**Comment by gespensen** [comment]
OK loaded up the beta will let it run this week.

**Comment by mackworth** [comment]
Any results?

**Comment by gespensen** [comment]
There hasn’t been only a few new shows over the holidays. I’ll have to give it some more time. Of the few shows that have transferred, there hasn’t been any naming errors.

**Comment by mackworth** [comment]
Still working ok?

**Comment by gespensen** [comment]
the Beta version seems to be resolving the naming issue. With several new downloads over the past week, there have been no naming errors.

**Comment by mackworth** [comment]
Great. Thank you.
