### ISSUE TITLE
HBO Surround Sound

### ISSUE THREAD

**Issue by John236498** [mackworth/cTiVo#348]
I'm using version 3.1.2 of the application. When I try to encode an HBO recording the surround sound is missing. Opening the file in Subler there is only one audio track with 2 channels. Now I happen to notice that the channel is broadcast in stereo sound until the HBO static intro that appears before every show appears. From that moment on its in surround sound. I don't know if that's how its broadcast directly from HBO or this is something that the cable provider does. But I would like some assisitance with getting the encoded file with surround sound not just stereo sound. If anybody can help me with this I would appreciate it. Thank you.

**Comment by mackworth** [comment]
Which Format are you using, and if you do a Decrypted TiVo download, and look at the resulting file in Subler, does it show stereo or surround?

Also, which cable provider do you have that lets you download shows from HBO? I’ve never heard of that.

**Comment by John236498** [comment]
- I exclusively use the Higher Quality format. When you refer to a Decrypted TiVo download- Are you asking about downloading the MPEG-PS/MPEG-TS directly from the WebUI of the device? Or using the app as I normally would? If as I would normally use the app- the resulting file only shows stereo track within Subler.
- My cable provider is Blue Ridge Communications.

**Comment by mackworth** [comment]
Well, congrats that you can even download these shows. AFAIK, every major provider marks HBO shows as copy-protected, so TiVo blocks the downloading.

Decrypted TiVo Shows is a cTiVo Format that simply removes the encryption with no re-encoding. Thus it shows you exactly what's in the original stream, as opposed to most Formats that change the content in various ways. My initial hypothesis is that these shows only contain a stereo track when downloaded from TiVo, and therefore we can't create a surround track. (But I may be wrong...) So give that Format a try and look inside with Subler.

**Comment by John236498** [comment]
I dowloaded the show using the Decrypted TiVo Show format. Subler is unable to open the file. However, I opened the file with VLC Media Player and the media information screen shows me the following with regards to the audio...

Stream 0
     Codec: A52 Audio (aka AC3) (a52)
     Type: Audio
     Channels: 3F2M/LFE
     Sample Rate: 48000 Hz
     Bits Per Sample: 32

**Comment by mackworth** [comment]
So that's good, 5.1 channel AC3. Now why isn't it coming across in the video. (FYI, Subler might be able to open it if you rename to MPG)
When you play that in VLC, are you hearing surround sound?

Next, can you run a show with Higher Quality format, but first set "Don't delete tmp Files (for debug only)" on. Then after it runs, go to your tmp folder, and you should have a folder named [YOURSHOWNAME]_ffmpeg.  Compress that in the Finder and post it.

**Comment by mackworth** [comment]
Oh, and don't forget to turn it off afterwards; that setting will swamp your hard drive.

**Comment by John236498** [comment]
For the Decrypted TiVo Show format - Yes, I can hear surround sound when played in VLC. It behaves just like it would if I played the recording from the TiVo.

For Higher Quality format - Again, there is no surround sound. Just stereo. VLC shows me the following on the media information screen...

Stream 1
Codec: MPEG AAC Audio (mp4a)
Type: Audio
Channels: Stereo
Sample Rate: 48000 Hz
Bits per sample: 32

I've uploaded the file you requested. Interestingly within that tmp folder there's a **buffer[YOURSHOWNAME].mpg** file which I'm assuming is a copy of the recording before being recoded into the Higher Quality format. That **buffer[YOURSHOWNAME].mpg** has the surround sound.

[Westworld-The Passenger_ffmpeg.zip](https://github.com/mackworth/cTiVo/files/2708983/Westworld-The.Passenger_ffmpeg.zip)

**Comment by mackworth** [comment]
That log file shows that when cTiVo asks ffmpeg what's in the downloaded file, it gets the following:
```
Input #0, mpeg, from '/Users/JaM4150/Downloads/cTivo TEMP folder/bufferWestworld-The Passenger.mpg':
  Duration: 01:31:01.52, start: 1.000000, bitrate: 7785 kb/s
    Stream #0:0[0x80]: Audio: ac3, 48000 Hz, stereo, fltp, 384 kb/s
    Stream #0:1[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, top first), 1920x1080 [SAR 1:1 DAR 16:9], Closed Captions, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
```
As you can see, ffmpeg is reporting that the audio is stereo instead of 5.1. cTiVo assumes ffmpeg knows what it's doing, so it asks ffmpeg to create the output file with stereo (albeit converted to AAC, which is more compatible in the Apple ecosystem).

Now, admittedly that contradicts what you're seeing out of VLC, not to mention what you're hearing.  Try [MediaInfo](
https://itunes.apple.com/us/app/mediainfo/id510620098?mt=12)  and see what it says about the streams.

**Comment by John236498** [comment]
It almost sounds like ffmpeg isn't recognizing that around ~60seconds into the broadcast/recording that it goes from Stereo to Surround sound.

MediaInfo says this about the **Decrypted TiVo Show** file and the **buffer[YOURSHOWNAME].mpg** file utilized for the Higher Quality format file...

General... 1 Audio Stream: AC-3
Streams... Audio: 384 Kbps, 48.0 KHz, 16 bits, 2 channels, AC-3 (DVD-Video) (Dolby Digital)

MediaInfo says this about the **Higher Quality format** file...
General... 1 Audio Stream AAC LC
Streams... Audio: 129 Kbps, 48.0KHz, 2 channels, AAC LC

**Comment by mackworth** [comment]
So, let's try this. Here's a version of the script used by Higher Quality that always copies the AC-3 stream unchanged into the resulting file in addition to the stereo stream. 

To use it, download, and decompress somewhere. Then 
go to `Edit>Edit Formats`, 
Choose Higher Quality, 
Duplicate
 change the name to Higher Quality-HBO or something
Change the encoder to the file you downloaded.
Save it.
Download a show using this Format.
 See if it works.

[ffmpeg_edl_ac3.sh.zip](https://github.com/mackworth/cTiVo/files/2709182/ffmpeg_edl_ac3.sh.zip)

**Comment by mackworth** [comment]
(I should mention that I edited the script, but haven't tried it, as I have no way to download an HBO show with the properties you describe. If it doesn't work first time, best would be to post the file somewhere temporarily and post a link to it here, and I'll try running it against it.)

**Comment by John236498** [comment]
I played back the **Higher Quality-HBOtest** format file. This time there is 2 audio streams. I switched between both streams and unfortunately at the ~60 second mark it doesn't switch over to Surround Sound but remains Stereo.

MediaInfo reports the same thing as it has before about the **buffer[YOURSHOWNAME].mpg** file. As for the **Higher Quality-HBOtest** it reports the following...

General... 2 Audio Streams: AAC LC / AC-3
Streams...
Audio #1: 129 Kbps, 48.0 KHz, 2 channels, AAC-LC
Audio #2: 192 bps, 48.0 KHz, 16 bits, 2 channels, AC-3 (Dolby Digital)

I have attached the **[YOURSHOWNAME]_ffmpeg** logs. Earlier when you mentioned posting the file temporarily- Were you referring to the the recording?

[Westworld-The Passenger_ffmpeg.zip](https://github.com/mackworth/cTiVo/files/2711253/Westworld-The.Passenger_ffmpeg.zip)

**Comment by mackworth** [comment]
So ffmpeg is indeed confused by your audio stream.  Even when outputting to AC3, it’s reducing it to stereo.  Here’s a different version of the shell script that just asks ffmpeg to copy it unchanged. Wherever you put the previous version, just replace it with this one, and the HBOtest Format should pick it up without needing to be edited again.


[ffmpeg_edl_ac3.sh.zip](https://github.com/mackworth/cTiVo/files/2711426/ffmpeg_edl_ac3.sh.zip)

**Comment by mackworth** [comment]
Here is a version of the script that (a) passes through AC3 streams without encoding and (b) accepts a new command line argument: -noStereo. This is a candidate for inclusion as the standard script called by the Default Format.
Again, if you simply decompress and put the .sh file where the original one was, your HBOTest Format should work without changes. If you don't want to have to choose between the stereo and the AC3 version, you can add -noStereo to the Audio options in HBOTest.
[ffmpeg_edl_ac3.sh.zip](https://github.com/mackworth/cTiVo/files/2715280/ffmpeg_edl_ac3.sh.zip)

**Comment by John236498** [comment]
So for the script you provided 6 days ago - MediaInfo reports the following about the  **buffer[YOURSHOWNAME].mpg**file...

General... 1 Audio Stream
Streams... Audio #1: 384 Kbps, 48.0 KHz, 16 bits, 2 channels, AC-3 (DVD-Video)

...But states this about the final file...

General... 2 audio streams: AAC LC / AC-3
Streams...
Audio #1: 129 Kbps, 48.0 KHz, 2 channels, AAC LC
Audio #2: 384 Kbps, 48.0 KHz, 16 bits, 2 channels, AC-3 (Dolby Digital)

... When I play this file I have to switch to the 2nd audio track. This is when it switches over to Surround Sound ~60 seconds into playback.

As for the script you provided 5 days ago (pass AC3 w/o encoding, -noStereo, candidate for inclusion) - MediaInfo reports the following about the **buffer[YOURSHOWNAME].mpg** file...

General... 1 Audio Stream
Streams... Audio #1: 384 Kbps, 48.0 KHz, 16 bits, 2 channels, AC-3 (DVD-Video)

... But states the about the final file...

General... 1 Audio Stream: AAC LC
Streams... Audio #1: 129 Kbps, 48.0 KHz, 2 channels, AAC LC

... When I play this file its just Stereo Sound.

I've uploaded logs from both scripts. See below.

[Westworld-The Passenger_ffmpeg.zip](https://github.com/mackworth/cTiVo/files/2720040/Westworld-The.Passenger_ffmpeg.zip)

[Westworld-The Passenger-1_ffmpeg-CandidateScript.zip](https://github.com/mackworth/cTiVo/files/2720039/Westworld-The.Passenger-1_ffmpeg-CandidateScript.zip)

**Comment by mackworth** [comment]
I just tried it again with a regular AC3 5.1 track, and it worked fine. 

Can you export the Format (File>Export Formats, select just the noStereo one) and post it (you may need to compress it as well)?

**Comment by mackworth** [comment]
ah, never mind. I assigned the AC3 to the wrong channel.  Try this one:

[ffmpeg_edl_ac3.sh.zip](https://github.com/mackworth/cTiVo/files/2722756/ffmpeg_edl_ac3.sh.zip)

**Comment by mackworth** [comment]
So is that working now?

**Comment by John236498** [comment]
No it isn't working now. No switchover to to surround at ~60 seconds.

Same as it was before about the **buffer[YOURSHOWNAME].mpg** file. Final file details below...

General... 1 Audio stream: AAC LC
Streams... Audio #1: 129 Kbps, 48.0 KHz, 2 channels, AAC LC

[Westworld-The Passenger-2_ffmpeg.zip](https://github.com/mackworth/cTiVo/files/2739159/Westworld-The.Passenger-2_ffmpeg.zip)

**Comment by mackworth** [comment]
Interesting. And which audio options were used?

**Comment by mackworth** [comment]
checking again...

**Comment by mackworth** [comment]
Closing due to lack of response.
