### ISSUE TITLE
cTivo suddenly not seeing my Tivo Premiere

### ISSUE THREAD

**Issue by wjmt3** [mackworth/cTiVo#355]
Hi,

Suddenly, one of my two Tivos (Premiere) is not visible to cTivo anymore. I have rebooted both the Tivo and my Mac. But cTivo now sees only my Roamio. I have verified that the Tivo in question is not having any network issues (wired connection appears to be working perfectly.) It is listed in the Tivos section of cTivo Preferences, with the correct MAK.

Do you have any clue what might be going on, and what I can do about it? Everything worked fine as of a few days ago. Thanks!

**Comment by mackworth** [comment]
Happy to help. Simplest would be if the enabled box is off in edit>edit TiVo’s. Then the first step is to set your log level to Detail, Quit and restart cTivo, then post the log (Help>show logs in finder).

**Comment by wjmt3** [comment]
OK. The first thing I did was go back to the list of Tivos. I mentioned that both Tivos were listed in Edit Tivos. But it's more interesting than that. Though I only have two Tivos, there are four entries in that box. "Premiere", "Roamio", plus two more based on the MAC address of each (I renamed them on Tivo.com for easy recognition long ago)

When I opened this ticket, the two named entries were listed and checked. The ones with MAC addresses were NOT checked.

So I checked one of the MAC addresses, and all the content of the Premiere instantly reappeared! It won't have a friendly nickname, but I can live with that! I'm not sure why the sudden change, but it appears to be working now. :)

**Comment by mackworth** [comment]
Can you post a screenshot?

**Comment by wjmt3** [comment]
Of the list of Tivos? Sure, but I'll have to redact the MAK somehow, since it appears in that window, and Tivo is explicit about it not leaving one's household.

**Comment by mackworth** [comment]
That’d be fine, or you can email it to me at Mackworth at aol dot com

I’d love to get the log also

**Comment by wjmt3** [comment]
Will get it to you shortly via email. One small update: the OTHER Tivo now has also decided it prefers to be known by its MAC address.

**Comment by mackworth** [comment]
On hold due to hardware problems. Please reopen when appropriate.

**Comment by wjmt3** [comment]
I have been able to confirm that this issue happened ENTIRELY because TiVo.com somehow lost the assigned nicknames for my TiVos, even though I made no changes. Commenting for the sake of completeness, but this issue can be closed.

**Comment by mackworth** [comment]
Thanks for the update. So both devices then became unavailable over Bonjour, under any name)?

**Comment by wjmt3** [comment]
No, they remained available, but reverted to their MAC addresses, in the format "DVR XXXX (TiVo)"

This is why cTiVo on the old machine suddenly listed 4 devices when I had only two. :) I just had to enable them.
