### ISSUE TITLE
Skip data download fails

### ISSUE THREAD

**Issue by tdlivings** [mackworth/cTiVo#356]
trying to manually download skip data and it fails. It says it is available yet it fails to download when right click download skip data.

[com.cTiVo.cTiVo 2019-03-09 06-23.log](https://github.com/mackworth/cTiVo/files/2948583/com.cTiVo.cTiVo.2019-03-09.06-23.log)

**Comment by tdlivings** [comment]
a couple of other problems I been having, Although it may be my system, Downloads that reside on my HDD are not showing in bold and so can not be dragged, and in some cases an episode in the subscribed section fails to queue automatically.

**Comment by mackworth** [comment]
For the SkipData, is it just the one show, or have others failed/worked?  If you could increase the log level in RPC (In Adv Prefs) to Detail, and try the manual SkipMode again, that would be helpful.

Are the downloads on an external drive/network drive? If so, how is it formatted? If not, similarly setting TiVoManager to Verbose, quitting and restarting will give more information about what's happening.

On the Subscribing, set Subscription to Verbose, then right-click on the relevant subscription, and select `Re-Apply to Shows`, and see if it works this time.

**Comment by tdlivings** [comment]
Two different shows so far. External ExFat SSD.

**Comment by tdlivings** [comment]
I can download the show, I just can not get Skip-Mode on two separate TiVo boxes, multiple shows.

**Comment by mackworth** [comment]
So, that's definitely why you're not seeing the shows marked. cTiVo marks downloaded shows with a "cTiVoDownload" extended attribute in order to find them again later, but ExFat doesn't store Mac metadata (nor does it give an error), so that mark gets lost. 

Let me know if you have a chance to do the logging on the other two issues. Can't really diagnose it otherwise.

**Comment by tdlivings** [comment]
[com.cTiVo.cTiVo 2019-03-09 06-20.log](https://github.com/mackworth/cTiVo/files/2948917/com.cTiVo.cTiVo.2019-03-09.06-20.log)

**Comment by tdlivings** [comment]
Reformated Ssd to APFS, still no bold for finder reference and still no skip Mode data

[com.cTiVo.cTiVo 2019-03-09--22-51-16-762.log](https://github.com/mackworth/cTiVo/files/2948918/com.cTiVo.cTiVo.2019-03-09--22-51-16-762.log)

**Comment by tdlivings** [comment]
Changed it to HFS+ looks like that's what it wants.

**Comment by tdlivings** [comment]
Pardon the rambling. With APFS External it is not bold until I drag it to Internal APFS drive. Then it show bold. If I delete it from internal and leave copy on external it removed bold finder location. I reformatted to HFS+ and it downloads and bold is delayed. closing and opening app didn't  update finder data. refresh all tivos either. When I updated tivos individually it update the finder and made entry bold.

**Comment by tdlivings** [comment]
If I set log level to verbose and quit, it changed to major. This happens every time.

**Comment by mackworth** [comment]
That last one is actually a feature. Too many people were turning on Verbose and flooding their drive. So when you start up, if you don’t hold down Control-Option, it will reset back to Major. But that should only be with all modules set to Verbose (as it would on the General prefs page); if you only set the TivoManager to Verbose in Adv Prefs, it should be fine.

On your drives, it looks like there are indeed [some issues with APFS external drives and Spotlight (see this google search)](
https://www.google.com/search?q=apfs+spotlight+external+drive). You can try turning it off and on in Privacy to start the indexing again. Also, if there's a lot of files on the disk already, then it may just take a while for Spotlight to catch up, which may be why HFS+ reporting also was delayed. Nothing to do with refreshing TiVos; that's probably just a timing coincidence. All cTiVo does is mark the file when it's first created, and make it bold when Spotlight tells it one was found.  If you search for cTiVoDownload in the finder, it will also show you all of the known downloads. 

On the SkipMode, I'm definitely seeing a problem there.  What kind of Tivo is it?  It seems to be responding slowly to the key commands we send. If you don't mind doing a few diagnostic steps, we may be able to see what's happening.

**Comment by tdlivings** [comment]
Will do on the verbose, Model it a Romio OTA, 4 tuner model, not a newer model by far. Let me know what steps to take if it will help…. I am testing some new workflows and the skip data would be a "nice to have" going forward.

**Comment by mackworth** [comment]
Okay, then let's try the following.

1. First, set all Debug levels in Adv Pref to Major, except for RPC at Detail.
2. Note what time it is so I can find these tests easily.
3. Select the ones with SkipMode info
4. Right-Click Reload All Info
5. Right-Click Get SkipMode
6. Quit cTiVo
7. Wait about 10 seconds
8. Then in Terminal, type `defaults write com.ctivo.ctivo RPCTime '2.0, 1.6, 1.0, 0.4'`
9. Repeat steps 3-5

**Comment by tdlivings** [comment]
17:25

**Comment by mackworth** [comment]
Hmm?

**Comment by tdlivings** [comment]
LOL, did I do it wrong?

**Comment by mackworth** [comment]
Ah, maybe because Github strips attachments from emails. They have to be posted at the site

**Comment by tdlivings** [comment]
[com.cTiVo.cTiVo 2019-03-09--22-51-16-762.log](https://github.com/mackworth/cTiVo/files/2948998/com.cTiVo.cTiVo.2019-03-09--22-51-16-762.log)

**Comment by mackworth** [comment]
So it's showing a 50% rate, which is pretty useless, but the defaults command didn't work; the second try used the same parameters.  

Here's a version with a hardwired longer time. give it a try.  (Same steps 1-6)
https://www.dropbox.com/s/zid0vq12o38xs0n/cTiVoTemp.zip?dl=0

**Comment by tdlivings** [comment]
That is why I have it on a wire, the wireless on the TiVo is useless.

**Comment by tdlivings** [comment]
Houston, we have lift - off
[com.cTiVo.cTiVo 2019-03-09--22-51-16-762.log](https://github.com/mackworth/cTiVo/files/2949037/com.cTiVo.cTiVo.2019-03-09--22-51-16-762.log)

**Comment by tdlivings** [comment]
<img width="857" alt="Screen Shot 2019-03-09 at 19 18 00" src="https://user-images.githubusercontent.com/22117759/54080227-1f5e8700-42a0-11e9-9567-b853c09ce8b9.png">

**Comment by tdlivings** [comment]
Blue Blood Manual edit: 42:03, Auto Edit with CommSkip: 42:09. Awesome. Thank you for your help.

**Comment by mackworth** [comment]
Good to hear. I've incorporated the slower timing (previously only for very old TiVos) as the default for all of them now. It's only a few seconds, and doesn't get run all that often anyways.  Thanks for reporting it and the help confirming the fix.
