### ISSUE TITLE
Downloading causes Tivo Boot loop.

### ISSUE THREAD

**Issue by tdlivings** [mackworth/cTiVo#358]
The last 2 times I have downloaded TiVo shows the boxes get in a boot loop. I am going to be on the road today so I can not do much with it but I wanted to start the topic.

Platform: series 5
Software version: 21.8.3 RC4-848-6-846

**Comment by mackworth** [comment]
By boot loop, do you mean that the TiVo rebooted itself, or that TiVo reported a busy message, suggesting a reboot?

**Comment by tdlivings** [comment]
looks like the working version too. Must be my side.

**Comment by tdlivings** [comment]
TiVo reboot, over and over
tested working version same thing, checking individual shows now. We had a frequency shift yesterday, my guide is fubar

**Comment by tdlivings** [comment]
you can close this one with my apologies. Looks like my side....

**Comment by mackworth** [comment]
No problem; hope your TiVo recovers...
