### ISSUE TITLE
Suggestion: Utilize TiVo pause points

### ISSUE THREAD

**Issue by wjmt3** [mackworth/cTiVo#359]
When transferring a show between two TiVos, it is possible to select "Transfer from pause point", and transfer, say, only the last 15 minutes of a program if that's all you want.

It would be awesome if a future version of cTiVo were able to read these pause points to offer similar flexibility.

**Comment by mackworth** [comment]
AFAIK, nobody’s been able to reverse engineer the video-transfer protocol between TiVos or with iOS devices. They used to support a midpoint restart on the regular file transfer, but that hasn’t been true for a while.
