### ISSUE TITLE
ethernet tivo

### ISSUE THREAD

**Issue by donaldnaegele** [mackworth/cTiVo#361]
I am brand new to your app today. I love it so far. I have two Tivos. One wireless and one wired via ethernet direct to my router. 

I can't see any files on that ethernet Tivo.

Thoughts?

Don

**Comment by mackworth** [comment]
So, a few possibilities.  Quickest diagnostic would be to go to Preferences>Advanced and set TiVoManager debug level to Detail, then quit and start cTiVo again.  Then Help>Show Logs In Finder and post the log file here (not via email though).

**Comment by donaldnaegele** [comment]
[com.cTiVo.cTiVo 2019-03-25--21-44-41-456.log](https://github.com/mackworth/cTiVo/files/3005633/com.cTiVo.cTiVo.2019-03-25--21-44-41-456.log)

not sure if i did this right?

**Comment by donaldnaegele** [comment]
<img width="586" alt="Screen Shot 2019-03-25 at 2 49 40 PM" src="https://user-images.githubusercontent.com/17925461/54956500-4c03d700-4f0d-11e9-8839-a93d7ce4e34a.png">

**Comment by mackworth** [comment]
You did, but I deleted the screenshot, as it has your Media Key, which is essentially your password.

So, on the other hand, the log doesn't show any contact with Office HD, but the screenshot shows both of them present? Is the second one not appearing in the main screen? Or did it appear afterwards?

**Comment by donaldnaegele** [comment]
Oops. Thanks. It was appearing at the top left where I could switch TiVo’s. Now it no longer shows there. Not sure how to get it back.

**Comment by mackworth** [comment]
Can you post log again? Sounds like it saw it and then went away...

**Comment by donaldnaegele** [comment]
[com.cTiVo.cTiVo 2019-03-25--23-45-52-839.log](https://github.com/mackworth/cTiVo/files/3005930/com.cTiVo.cTiVo.2019-03-25--23-45-52-839.log)

**Comment by mackworth** [comment]
Thank you. Can you resend the first one as well (it should have more info by now)?  Or any other log file there.  There's a gap between these two from 14:45 to 16:45.

(And neither has any reference to Office HD

**Comment by mackworth** [comment]
And, can you run this application (from Mac App Store)?
https://itunes.apple.com/us/app/discovery-dns-sd-browser/id1381004916?mt=12

It will show whether your TiVos are advertising themselves on the network.  (Look at the _tivo-xxx categories)

**Comment by donaldnaegele** [comment]
<img width="478" alt="Screen Shot 2019-03-25 at 5 51 27 PM" src="https://user-images.githubusercontent.com/17925461/54963629-a8272500-4f26-11e9-955f-c4759fb9c867.png">

Office isn't listed.

**Comment by mackworth** [comment]
And...
Can you resend the first log as well (it should have more info by now)? Or any other log file in the folder. There's a gap between these two from 14:45 to 16:45.

(And neither has any reference to Office HD)

**Comment by donaldnaegele** [comment]
[com.cTiVo.cTiVo 2019-03-25--23-45-52-839.log](https://github.com/mackworth/cTiVo/files/3006122/com.cTiVo.cTiVo.2019-03-25--23-45-52-839.log)

**Comment by mackworth** [comment]
Nope, that’s the second one. There should be a log dated: 2019-03-25--21-44-41-456.log

Clearly the issue is that your Mac isn’t “seeing” the Office HD TiVo (at least not all the time).  I think is your Office HD is the one on Ethernet, right? Is the Mac on the same Ethernet or a different one or WiFi?  Can you check the IP addresses:  The Macs in your Network preferences, and both TiVos:

From TIVO central, click on "Settings & Messages," then click on "Settings," then on "Network & Phone." A screen will appear that Network Connections across the top. One of the lines on this screen will say "IP Address."

**Comment by donaldnaegele** [comment]
OfficeHD is my ethernet one. And it's connected directly to the same router as my iMac.  The iMac is on the same (any my only) network as the Wifi Tivo (which seems to work ok). I'm sending all the logs I have. Thanks SO much for your help so far.

[com.cTiVo.cTiVo 2019-03-25--23-45-52-839.log](https://github.com/mackworth/cTiVo/files/3006391/com.cTiVo.cTiVo.2019-03-25--23-45-52-839.log)

**Comment by mackworth** [comment]
Hmm, so there’s only the one log?  And the IP addresses will help diagnose your network...

**Comment by mackworth** [comment]
So my presumption is that your router is dividing your network logically and not connecting Bonjour packets across. Your Living Room is at 192.168.1.17, and your Mac is probably on the same subnet. If your Office TiVo is on, say, 192.168.0.xx, then It wouldn’t be seen. 

The good news is even without reconfiguring the net, you can just manually add your TiVo. Just find out the actual IP address, and add it to the Manual TiVo page; you should then be good to go. The only negative would be if your net reconfigures for some reason, assigning a new address to the Office HD, then you will have to edit that page. Fortunately, that’s a relatively rare event.

**Comment by donaldnaegele** [comment]
Thanks SO much for your help. I will add it manually and see if that works. I'll let you know.

Thanks again.

Don

**Comment by donaldnaegele** [comment]
So before adding it manually I rebooted the ethernet connected tivo and it now shows up in your app. Not sure what happened.

Thanks.

**Comment by mackworth** [comment]
Great to hear. There’s a process running in the TiVo that broadcasts its availability. Sounds like that might have crashed. 

Let me know if you have any other issues.
