### ISSUE TITLE
On TiVo queue doesn't always refresh

### ISSUE THREAD

**Issue by jridder** [mackworth/cTiVo#363]
I am on macOS 10.14.4 and I am running the latest release of cTivo (3.3.0). I have noticed on occasion the view of what is on the TiVo doesn't refresh on it's own, causing cTivo to not download the next episode. I am pulling TV episodes from a Bolt running the latest updates. The only way I have found around the issue is to quit cTivo and relaunch the app.

[com.cTiVo.cTiVo 2019-03-26--22-14-00-149.log](https://github.com/mackworth/cTiVo/files/3010884/com.cTiVo.cTiVo.2019-03-26--22-14-00-149.log)

**Comment by jridder** [comment]
I selected Refresh TiVo on the File menu and it did refresh and started to download the episode that was ready to go. Waiting to see if it does the same on the next episode on it's own.

**Comment by mackworth** [comment]
easy enough to test, just manually record a few seconds of a show, and it should immediately show up (first as copy-protected during recording, so possibly filtered by "Show Protected Shows" option; then as a regular show).  

If you want to confirm the subscriptions are working, you can hit Cmd-N and just type ALL. This create a Subscription which will record all shows, and you can obviously delete it once you're done testing. It will create a Download for every non-suggestion show you have in the current list as well, but again, just delete those before doing your test.

**Comment by jridder** [comment]
Alright, I just picked something to record and it showed up in the list. The <<ALL SHOWS>> was added. 
Ok the show I did a few minutes of recording shows in the list as it is still recording but it's not.
<img width="1134" alt="Screen Shot 2019-03-26 at 7 33 37 PM" src="https://user-images.githubusercontent.com/11082465/55043960-14288c80-4ffe-11e9-8bcd-791d46341925.png">

**Comment by mackworth** [comment]
Interesting; so the in-progress showed up immediately, but once finished, it didn’t change over in cTiVo?

**Comment by jridder** [comment]
Correct. I let it sit for a while and it never refreshed until I forced it to. The other thing I noticed is that you can't click on anything (left or right) in the upper window until you tell it to refresh. It's kind of like its froze.

**Comment by mackworth** [comment]
Hmm, that suggests something’s getting hung up. I assume you’ve restarted cTiVo at some time here. Can you ...

1) quit and re-enter cTiVo
2) go to Preferences>General, and set the log level to Detail. Then close that, and ...
3) Do the same recording/stop process with the show (note if same freeze happens)
4) Go to Help>Show logs in Finder to find the latest Log
5) Post that log here, so I can see if there's any errors in the "conversation"

**Comment by jridder** [comment]
Went through the same recording action. Started the recording and then stopped it after a few minutes. The episode I recorded was FBI: Apex and per the snapshot, it still shows recording but it's not. This time around I can right click on the episodes and get some choices for actions.

[com.cTiVo.cTiVo 2019-03-26--22-14-00-149.log](https://github.com/mackworth/cTiVo/files/3011258/com.cTiVo.cTiVo.2019-03-26--22-14-00-149.log)
<img width="1134" alt="Screen Shot 2019-03-26 at 8 40 37 PM" src="https://user-images.githubusercontent.com/11082465/55046478-6f12b180-5007-11e9-9f02-37149d641d07.png">

**Comment by jridder** [comment]
I refreshed the TiVo and it tried to download the episode and I keep getting a Server Busy warning.

[com.cTiVo.cTiVo 2019-03-26--22-14-00-149.log](https://github.com/mackworth/cTiVo/files/3011274/com.cTiVo.cTiVo.2019-03-26--22-14-00-149.log)

**Comment by mackworth** [comment]
You're correct; I can re-create, and will fix.  Eventually it should always pick it up, either if another show starts recording, or after a couple hours. Didn't notice in my testing, as I always have a lot more shows especially with TiVo suggestions turned on, which means that it's creating shows a lot.

On the Server Busy, sorry about that. With opening and closing and adding shows and canceling them, you're stressing the file server. We do lots of things to protect it, but sometimes it fails. It sometimes resets after a couple hours, but otherwise, you'll have to reboot your TiVo (now available in your Remote Control Window.)

If you get that frozen upper window again, let me know.

**Comment by jridder** [comment]
After I posted the last note, the TiVo decided to reboot itself. 
I left cTiVo running last night and at some point it refreshed itself and downloaded and processed the episodes. Weird.

Thanks Hugh!

**Comment by wjmt3** [comment]
Not sure whether this data point is needed, but I just recorded an episode, which has finished, and the "recording" icon is indeed still there, with the other details in "grayed out" text. Since restarting cTiVo, it now displays correctly.

**Comment by mackworth** [comment]
Yup, although you should be able to either refresh the queue Cmd-R, or just wait for the next show or auto-refresh to get it.  I’ll post a fix soon.

**Comment by mackworth** [comment]
Fixed in 3.3.1 beta1; check it out and let me know.

**Comment by jridder** [comment]
Thanks Hugh. I will give it a whirl this weekend.

**Comment by jridder** [comment]
It works!!!! Thank you!!!
