### ISSUE TITLE
SkipMode question: does it use the annoying SkipMode sound effect?

### ISSUE THREAD

**Issue by wjmt3** [mackworth/cTiVo#364]
The sound itself so annoys me (somehow managing to be much _louder_ than whatever I happen to be watching) that I wish I could disable it completely, as useful as it otherwise is.

if cTiVo uses that chime in any way, I won't be using SkipMode features anytime soon.

**Comment by mackworth** [comment]
Fascinating. So my Roamio (using the old UI) doesn’t make any noise at all when using Skipmode, neither with up/down or with the green button. So I don’t know if it makes the chime with Hydra UI?  

To extract the commercial points, cTiVo does send a network command to jump to the end, then multiple Down commands to get it to jump to the various start points. So it probably would cause the same sound effect. 

On the other hand, we don’t need your TV to be on while doing the SkipMode retrieval (in fact, as I’ve discovered during development, it’s rather annoying if you accidentally set it to 24hr retrieval and then it decides to retrieve one while you’re watching a show). 

So if a chime goes off in the woods with no one around, does it really exist?

**Comment by wjmt3** [comment]
Oh, I should have clarified: the chime I'm referring to is the one that accompanies the momentary popup that the TiVo puts up at the start of every commercial break (or whenever you stop rewinding or fast-forwarding too soon) that says "Press D to SKIP and resume show". It's a tri-tone sound, similar to but faster and louder than the Special Information Tone in the world of telecommunications, which plays before the recording "You have reached a number that has been disconnected or is no longer in service" when you misdial a phone number.

**Comment by mackworth** [comment]
Ah, I know what you mean. No, I don’t think we’ll cause that one.  cTiVo plays across the boundary at the end if the commercial break, not the beginning.
