### ISSUE TITLE
Tiny aesthetic issue: Recording status icon

### ISSUE THREAD

**Issue by wjmt3** [mackworth/cTiVo#365]
I happen to have cTiVo open while I am recording a show, and I notice that the status icon is a black dot which contains a smaller red dot. Wouldn't it be more complementary to its green counterpart as a solid red dot?

**Comment by mackworth** [comment]
You're probably right that they should be updated. The icons are actually from the TiVo UI back in 2013.

**Comment by mackworth** [comment]
Fixed in 3.3.1 beta1; with new icons for in-progress, recently recording and TiVo suggestions.

**Comment by wjmt3** [comment]
I'm relatively new here; where do I access beta releases?

**Comment by mackworth** [comment]
In the Releases tab at the top level.  Here: https://github.com/mackworth/cTiVo/releases/tag/3.3.1Beta1
