### ISSUE TITLE
3.3.0 Known Issues // 3.3.1 beta

### ISSUE THREAD

**Issue by mackworth** [mackworth/cTiVo#366]
Known Issues in 3.3.0:

-    cTiVo does not always immediately notice when a show has finished recording (fixed in beta1)
-    If you have never used Mark before, 3.3.0 upgrade will incorrectly turn it on, while leaving Cut enabled as well. (workaround: turn off Mark)
-    Incorrectly reports "No memory buffer" in logs when memory enabled.
-    Handbrake CLI no longer compatible with 10.9  (workaround: don't use HB presets on 10.9)

Latest beta release 3.3.1 beta2 fixes above (except Handbrake)
Also has new status icons, matching TiVo's for in-progress, recently recording, and suggestions.

**Comment by tdlivings** [comment]
Let me know when you enable eGPU for the 1080p profile. I am very interested in using this feature/ profile. thank you

**Comment by mackworth** [comment]
Sorry for delay. Unfortunately, I have neither a eGPU nor a T2 to experiment with, so can't really help. @sugyfelix apparently had it working, but hasn't been able to post anything about it yet in  #343

**Comment by mackworth** [comment]
3.3.1 is now released. In addition to above issues, it fixes an unusual crash when Bonjour search returned an undocumented NSNull.

**Comment by mackworth** [comment]
Sigh; I uploaded the beta 2 file by mistake.
I have just replaced with the correct file. (Now named `cTiVo.3.3.1.final.zip`; the incorrect file was named `cTiVo.3.3.1.zip`). 
Easy to check which version you have with either Finder>Get Info or cTiVo>About cTiVo.

**Comment by tdlivings** [comment]
Thank you
