### ISSUE TITLE
Commercials marked instead of cut

### ISSUE THREAD

**Issue by mr100percent** [mackworth/cTiVo#367]
Version 3.3.0 has a bug where on first launch the "Cut Commercials" and "Mark commercials" are both checked in preferences. Unchecking the boxes and then checking one (in this case Cut) seems to allow it to default to one or the other option. Adding shows to Queue defaults to Mark Commercial regardless of the preference settings. The video files also output in marked form.

The workaround I see is to pause the queue, add the show, and then manually change the boxes in the queue.

**Comment by mackworth** [comment]
Thanks for reporting that. When you say”first launch”, do you mean from not using it before, or from upgrading from a prior version?

And then on “Adding shows to Queue defaults to Mark Commercial regardless of the preference settings”, does that happen after you fixed it in Prefs, or just before that? 

(The “seems to allow it” suggests the latter, but the need for a workaround suggests it didn’t really fix it?)

**Comment by mr100percent** [comment]
Ah, I mean first launch from upgrading from a prior version.

The problem happens both before and after fixing it in prefs.

**Comment by mackworth** [comment]
Fascinating. And no such problem before upgrading... Can you email your preferences file to me?  Mackworth at aol dot com. 

It is in ~/Library/Preferences/com.ctivo.ctivo.plist 

And If you use Time Machine or any other backup, if there’s any chance you can retrieve your preferences from before you upgraded, that would be really Great to figure this out.

**Comment by mackworth** [comment]
So, 3.3.0 does have a minor upgrade bug: if you have only used Cut (formerly known as Skip), then 3.3.0 will also turn Mark on. Just turn Mark off, and you should be fine. Will be fixed in next beta.

**Comment by mackworth** [comment]
Fixed in 3.3.1 beta, so closing for now.
