### ISSUE TITLE
no longer has option to prefer show info from thetvdb

### ISSUE THREAD

**Issue by lordquibble** [mackworth/cTiVo#368]
With the 3.3.0 update (love the skip mode features, btw) it seems that the option to prefer using show info from TheTVDB has been removed. This causes issues because TiVo can regularly provide bad show data that cTiVo can access. This has three effects that I have observed.

First, please see the attached screenshot for example. On the TiVo, these do present as episodes 15 and 16, but in cTiVo they present both as episode 15. Previously, by retrieving the show data from TheTVDB, this would be corrected.
![Screen Shot 2019-03-30 at 2 02 56 PM](https://user-images.githubusercontent.com/49103836/55280518-92ce4400-52f4-11e9-89fc-242e34b149c9.png)

Second, some shows change their name (their subtitle actually, but its all the same for tivo) each season. "Marvel's Avengers Assemble" (https://www.thetvdb.com/series/marvels-avengers-assemble) is my most recent example. Previously, when cTiVo pulled show data from thetvdb, it would recognize that the episodes were part of the overall show, and as such, when the  files got processed by my Plex server, they would be handled correctly.

Lastly, shows that had the same name as a previous show (i.e. The Flash (1990) vs The Flash (2014)) would present problems when being downloaded and processed by my Plex server. I had worked out a mostly-functional solution by including the TVDBSeriesID information in the show folder name. It seemed that plex would search this as well as the show name and 4 out 5 times actually match the the right show. With the option to not explicitly prefer info from thetvdb missing, it seems that the TVDBSeriesID information is not reliably present in the show information.

I hope this can be corrected easily. please let me know if you have any follow up questions.

Cheers

**Comment by mackworth** [comment]
So, although I took out the GUI control, the option is still there "hidden". OTOH, I'm a little surprised that it's not still working for you, as if you had it set previously, it should still be working.

To restore, quit cTiVo, go into Console and type `defaults write TrustTVDBEpisodes -bool YES`, and then see if it's working for you.

(That episode 15 problem drove me crazy as well on the TiVo itself, just trying to figure out which order to watch in!)

If anyone else wants the control restored, add a note here!

**Comment by mackworth** [comment]
BTW, it's possibly you're having a different problem. If the TiVo UI is showing 15/16 (which it didn't for me), then cTiVo should be showing the same. It's possible that you're still using the TrustTVDB setting, but having a problem getting to TVDB. Might check the logs for any error msgs about that.

**Comment by mackworth** [comment]
Oh, one more debugging tip here. For older episodes, cTiVo remembers the TiVo/tidbit info, so Control-click Reload All Info to cause it to forget all that and reload from the sources again.

**Comment by mackworth** [comment]
And if you want to see what's happening, just open the most recent log (Help>Show logs) in Console, set Debug Level to Detail, then "Reload All Info" and it will document what it's getting from TVDB and TiVo, and what decisions it's making.

**Comment by mackworth** [comment]
Let me know if that's not working for you, but I'll close this for now.
