### ISSUE TITLE
Simultaneous downloads no longer working

### ISSUE THREAD

**Issue by octaviojlima** [mackworth/cTiVo#369]
After the latest update cTivo does not perform simultaneous downloads from different Tivos. Has anyone reported something similar?

**Comment by mackworth** [comment]
Nope, thank you for reporting it. So, what order are you seeing? If you have two downloads from two different TiVos, does it finish one and then immediately start the next one from the other TiVo? Or does the second never start?

Can you set up a couple downloads on different TiVos (with Queue off), set Debug level to Detail, and then start the queue, then post the resulting log.

**Comment by octaviojlima** [comment]
> Nope, thank you for reporting it. So, what order are you seeing? If you have two downloads from two different TiVos, does it finish one and then immediately start the next one from the other TiVo? Or does the second never start?
> 
> Can you set up a couple downloads on different TiVos (with Queue off), set Debug level to Detail, and then start the queue, then post the resulting log.

They are processed sequentially. I will run the tests when I have some time and will report the results shortly.

**Comment by mackworth** [comment]
Great. BTW, one quick thing to check: if Concurrent Encoders in Advanced Preferences is lower than 2, then you would get that symptom.

**Comment by octaviojlima** [comment]
> Great. BTW, one quick thing to check: if Concurrent Encoders in Advanced Preferences is lower than 2, then you would get that symptom.

It is set to two which is the number of TiVos on the network.

**Comment by octaviojlima** [comment]
> Great. BTW, one quick thing to check: if Concurrent Encoders in Advanced Preferences is lower than 2, then you would get that symptom.

I was able to run the test. Please find the log attached.
[com.cTiVo.cTiVo 2019-04-04--17-58-35-272.log](https://github.com/mackworth/cTiVo/files/3046104/com.cTiVo.cTiVo.2019-04-04--17-58-35-272.log)

**Comment by mackworth** [comment]
Can I get the log(s) before this one?

**Comment by mackworth** [comment]
So, what's happening is that somehow cTiVo lost track of how many encodings were going on.  Relevant log portion:
````
2019-04-04 20:58:41:959 -[MTTiVo manageDownloads]@1274>Number of encoders after launching show "Young Sheldon: A Perfect Score and a Bunsen Burner Marshmallow"  is 2
2019-04-04 21:09:21:461 -[MTTiVoManager encodeFinished:]@1789>Num encoders after decrement from notification MTNotificationShowDownloadDidFinish is 1 
2019-04-04 21:09:24:617 -[MTTiVo manageDownloads]@1274>Number of encoders after launching show "The Big Bang Theory: The Laureate Accumulation"  is 2
2019-04-04 21:19:44:930 -[MTTiVoManager encodeFinished:]@1789>Num encoders after decrement from notification MTNotificationShowDownloadDidFinish is 1 
````
So before even starting the first show, it thought 1 was in process, which increments to 2, and after that finished, it still thought 1 was going on, and so on.  Therefore, it won't start another show until the previous one is finished. Nothing to do with separate TiVos, just counting how many encodings are going on in parallel. To fix, just quit and restart cTiVo, and the encoder count will reset to zero.

OTOH, I'd like to get the logs from before this run to see if there's any clues on how it managed to get into that state. There was a beta version that had a problem with tracking completions, but haven't seen the problem otherwise. Thanks for reporting it.

**Comment by octaviojlima** [comment]
> So, what's happening is that somehow cTiVo lost track of how many encodings were going on. Relevant log portion:
> 
> ```
> 2019-04-04 20:58:41:959 -[MTTiVo manageDownloads]@1274>Number of encoders after launching show "Young Sheldon: A Perfect Score and a Bunsen Burner Marshmallow"  is 2
> 2019-04-04 21:09:21:461 -[MTTiVoManager encodeFinished:]@1789>Num encoders after decrement from notification MTNotificationShowDownloadDidFinish is 1 
> 2019-04-04 21:09:24:617 -[MTTiVo manageDownloads]@1274>Number of encoders after launching show "The Big Bang Theory: The Laureate Accumulation"  is 2
> 2019-04-04 21:19:44:930 -[MTTiVoManager encodeFinished:]@1789>Num encoders after decrement from notification MTNotificationShowDownloadDidFinish is 1 
> ```
> So before even starting the first show, it thought 1 was in process, which increments to 2, and after that finished, it still thought 1 was going on, and so on. Therefore, it won't start another show until the previous one is finished. Nothing to do with separate TiVos, just counting how many encodings are going on in parallel. To fix, just quit and restart cTiVo, and the encoder count will reset to zero.
> 
> OTOH, I'd like to get the logs from before this run to see if there's any clues on how it managed to get into that state. There was a beta version that had a problem with tracking completions, but haven't seen the problem otherwise. Thanks for reporting it.

Thank you. I will restart cTiVo. Unfortunately, I do not have previous logs as I had no problems with it whatsoever. It is the first time this happens to us. I will leave the logs on starting now and should the issue persist I will send you the new logs. Thank you again.

**Comment by mackworth** [comment]
It keeps some logs even at the "Normal" setting. Are there no other files in that folder?

**Comment by octaviojlima** [comment]
> It keeps some logs even at the "Normal" setting. Are there no other files in that folder?

Nope, no files. But I do think I have a clue as to what was the problem. We used to have a movie recorded that cTiVo thought could be retrieved but was probably copy protected. It showed on the list of available shows, but it always failed to transfer. Could it be that when the transfer failed, cTiVo was still believing an encoder had been allocated for it? We decided to get rid of it as we never watched it again.

**Comment by mackworth** [comment]
Well, it's not supposed to...All cases of finishing, failing, or canceling are supposed to be reported to the central counter.  Oh, well.  Let me know if it happens again...

**Comment by octaviojlima** [comment]
As a side note, cTiVo is a brilliant piece of software.

> Well, it's not supposed to...All cases of finishing, failing, or canceling are supposed to be reported to the central counter. Oh, well. Let me know if it happens again...

I will. As a side note, cTiVo is a brilliant piece of software. Well done!

**Comment by mackworth** [comment]
Thank you!
