### ISSUE TITLE
Question: RE: SkipMode Download

### ISSUE THREAD

**Issue by tdlivings** [mackworth/cTiVo#370]
I have auto download of SkipMode data set between 11:00 pm and 4:00 am so as not to disturb my wife's live viewing. However, the SkipMode data is not automatically downloading. I was wondering if I was doing something wrong.

**Comment by mackworth** [comment]
That should be fine. Set the debug level to Major, restart cTiVo, and let it run overnight, and post the log

**Comment by tdlivings** [comment]
Copy,

**Comment by mackworth** [comment]
Any news here?

**Comment by tdlivings** [comment]
No news, I have to download the skip data manually if I want it. I am not sure if is a computer sleeping issue or a delay in the info being available. As a result the show does not populate the queue. I admit though, I have not had much time to fiddle with it. Another thing I have noticed, not ma bug, but certain channels can not be recoded with anything but decrypted because the sound track drifts slightly. Mainly I have been using 1080P with skip mode for the tests.

**Comment by mackworth** [comment]
So, if the computer's asleep, it probably won't see the SkipMode notifications from the TiVo.  On the other hand, when it next wakes up, it should pick them up.   If you increase the log to Major, and let it run, I can take a look.

**Comment by tdlivings** [comment]
should I designate a show recode as needing it? I have it set to auto download at night. 
<img width="517" alt="Screen Shot 2019-04-18 at 21 25 15" src="https://user-images.githubusercontent.com/22117759/56405302-9cc2d300-6220-11e9-81af-85ee8a2ec205.png">

**Comment by mackworth** [comment]
Sorry, I don't know what "designate a show recode as needing it?" means? 

I note that you only have auto-Skipmode set for 2-4, not 11-4.

cTivo's "Disable Sleep during Downloads" should prevent sleep if any shows are queued up. As you have that enabled, if a show is available (with or without SkipMode having arrived), then it should stay awake until it is downloaded.

(Alternatively, you can set it to AutoWake in System Preferences>Energy Saver>Schedule.  The problem is that you don't know when the SkipMode data will arrive, so if you wake at 2, it might fall asleep again by the time it arrives at, say, 3:30.)

Regardless, best way to figure out what's going on is to see the log for an overnight session where it doesn't do the AutoSkip.

**Comment by tdlivings** [comment]
So I should download and auto retrieve at the same time window? Designate as needing it is, set program to need skip mode before using cut and recode to 1080P, (clear as mud, no?)

**Comment by tdlivings** [comment]
<img width="515" alt="Screen Shot 2019-04-18 at 21 43 02" src="https://user-images.githubusercontent.com/22117759/56405841-f9bf8880-6222-11e9-8f15-17439e683b5b.png">

**Comment by tdlivings** [comment]
I added survivor manually to the queue using 1080p with skip and cut. Lets see how it works tonight (this Morning). So far skip data not downloaded.

**Comment by mackworth** [comment]
You can set the AutoSkip and download timeframes independently, but if you're cutting shows, then no SkipMode shows can start to download until the SkipMode data has been retrieved. There is no problem having them run simultaneously either. No need to delay download until after AutoSkip, for example. 

(On survivor, do you have the debug log set to Major?)  You can also do the test without waiting overnight. Just set the AutoSkip start time to one minute in the future, and when it hits, it should start the AutoSkip process. (Caveat: needs at least 15 seconds for the time change to register).

**Comment by tdlivings** [comment]
major yes. wait one

**Comment by tdlivings** [comment]
can I email you a vid, 80 mb

**Comment by tdlivings** [comment]
[com.cTiVo.cTiVo 2019-04-19--03-43-07-462.log](https://github.com/mackworth/cTiVo/files/3097034/com.cTiVo.cTiVo.2019-04-19--03-43-07-462.log)

**Comment by tdlivings** [comment]
looks like it is downloading correctly on a manual queue

**Comment by mackworth** [comment]
So, yes, that log shows it working, although it did fail the first time through with a timing problem.  What kind of TiVo is it?  But you've had no problem with manual SkipMode, right?

That's indeed a real test of AutoSkip, as you have it sitting waiting for 61 seconds before it auto-launched, but do leave it in Major debug mode and try some subscribed shows.

````
2019-04-18 21:52:48:050 -[MTTivoRPC findSkipModePointsForShow:withCompletionHandler:]_block_invoke_9@1766>For Survivor: S38E09 (Action Adventure); tivo:rc.15003169; clip:tivo:cm.85038 ; format: 1, got EDL (
    "Start =  0:00.00, End =  2:03.96, type=0, offset =  2:03.96; length = 123.96",
    "Start = 10:51.42, End = 13:45.96, type=0, offset =  4:58.50; length = 174.54",
    "Start = 29:03.84, End = 32:26.18, type=0, offset =  8:20.83; length = 202.33",
    "Start = 38:18.46, End = 41:34.72, type=0, offset = 11:37.09; length = 196.26",
    "Start = 46:25.32, End = 51:01.89, type=0, offset = 16:13.67; length = 276.58",
    "Start = 58:16.49, End = 61:18.91, type=0, offset = 19:16.09; length = 182.41",
    "Start = 62:05.62, End = 65:00.00, type=0, offset = 22:10.46; length = 174.38"
)
````

**Comment by tdlivings** [comment]
A romio ota. I will check on it tomorrow with an subscription.

**Comment by tdlivings** [comment]
The time out issue is probably because the Tivo needs to be awake for the retrieval. It takes a moment for it to wake up, I am guessing. I have set a manual subscription for an episode recoding tonight with 1080p and cut and skip mode selected. I will post the log tomorrow.

**Comment by tdlivings** [comment]
I set a new subscription for Blindspot and set the recode profile to one that would use the skip mode data in hopes of determining if A) the data would auto download and, B) if the show would fall into the download queue. I am happy to report both happened successfully. Included it the log. 

<img width="712" alt="Screen Shot 2019-04-20 at 08 53 11" src="https://user-images.githubusercontent.com/22117759/56459563-2ae6a880-634a-11e9-8048-897e627365b7.png">

[com.cTiVo.cTiVo 2019-04-20--03-50-51-140.log](https://github.com/mackworth/cTiVo/files/3100318/com.cTiVo.cTiVo.2019-04-20--03-50-51-140.log)

**Comment by mackworth** [comment]
Great to hear. Let me know if you have any other problems!
