### ISSUE TITLE
Awkward behavior when selecting programs/switching apps

### ISSUE THREAD

**Issue by wjmt3** [mackworth/cTiVo#372]
I notice that, if I have a program that is highlighted for any reason, and I switch to another program, the highlighted show changes from blue to gray. That much is normal and expected because it's in the background. However, if I bring cTiVo back to the foreground, the selection _remains_ in gray.

Because of this, I can't overstate how many times I have right-clicked a program, only to discover that the expected options do not show; it is first necessary to specifically left-click on the show (even though it's technically already selected) which turns the selection blue again, presenting all the expected options after I (again) right-click.

Other apps seem to notice such focus changes automatically.

**Comment by mackworth** [comment]
I’m traveling, and won’t be able to look at this until next week. My theory is that this is due to there being three tables; none of which is then selected when you return. You’ll see the same grey semi-selected rows in NowPlaying when you select the Download table. Note the blue (IIRC) highlighting around the table at the time.

**Comment by mackworth** [comment]
(Sorry for delay.) So, I'm not seeing this on my Mac at all. If I have a line (or lines) selected in NowPlaying, Download or Subscription (blue), switch out to another app (now selected line is grey), and come back, the same line is again highlighted in blue.  

The other thing i note is if I have a line selected in NowPlaying and right-click on a grey-selected line in the Download Queue, then the contextual menu appears without having to first select that table.

Which MacOS version are you running? (and I assume the latest 3.3.0 or 3.3.1 beta)   Do you have another Mac to try it on?

**Comment by wjmt3** [comment]
Hi Hugh,

Sorry for my own delay. Paying particular attention to what you have written, I will have to give it another shot. I am running 3.3.1beta 2 (1052), on MacOS 10.14.3. I don't presently have another Mac to try it on.

**Comment by mackworth** [comment]
Are you still seeing this?

**Comment by wjmt3** [comment]
Yikes.. sorry for another delay. It's been a busy patch. For reasons I can't explain, I'm not seeing it, either. I'll have to pay _very_ close attention to what I'm doing if I notice this behavior again. I'm not sure what changed between now and when I opened this.

**Comment by mackworth** [comment]
No problem. Let me know if you see it again.
