### ISSUE TITLE
is 3.3.1 still a beta version?

### ISSUE THREAD

**Issue by suschizu** [mackworth/cTiVo#374]
Hey @mackworth - I just noticed after downloading cTiVo 3.3.1 that the version-number still contains "beta":
![sc1](https://user-images.githubusercontent.com/16004333/57637564-0332db00-75ac-11e9-9b4f-4b927bb6baa6.png)

**Comment by mackworth** [comment]
You are 100% right; thank you! 
Yesterday, I uploaded the beta 2 version again by mistake.  
I have just replaced with the correct file. (Now named `cTiVo.3.3.1.final.zip` instead of the incorrect file: `cTiVo.3.3.1.zip`

**Comment by suschizu** [comment]
perfect thanks :)

**Comment by tdlivings** [comment]
checking for update in ctivo reports 3.3.0 is still the latest build.

**Comment by mackworth** [comment]
Correct. I have a habit of posting the release version for a week or so before updating the Sparkle update. Given the vast QA resources at my disposal, a slower rollout is less risky.

**Comment by tdlivings** [comment]
Ah, got it. Thank you.

**Comment by mackworth** [comment]
No problem; there's no way you'd know my rollout schedule, and I appreciate the report. 

If I don't hear of potential problems, I can't fix em.
