### ISSUE TITLE
3.3.2 Beta issues

### ISSUE THREAD

**Issue by mackworth** [mackworth/cTiVo#375]
Any issues with 3.3.2 beta; let me know here.

**Comment by tannebil** [comment]
Been running it for a couple of weeks without any issues.

Still have two issues that are ongoing:

1. Files are not being deleted after adding to iTunes but I've got a Hazel rule that cleans there up so it's not creating a problem.

2. The OnDisk flag periodically gets lost for what looks like a random set of shows. The latest time was after the upgraded to the beta version. I don't see any pattern. I blame it on some subtle issue with the Drobo implementation of HFS+

**Comment by mackworth** [comment]
Thanks for the update. After cTiVo asks iTunes to load the file, iTunes responds with the file’s pathname, which cTiVo then checks to see if it’s changed, meaning that iTunes copied it. Unfortunately, comparing two paths is harder than it sounds, so we rely on some file system attributes, which may be failing on the Drobo. I’ll put some logging in the next version to see what’s happening. 

On figuring out the OnDisk problem, I would note that if a download successfully happens within current session, then it’s marked as OnDisk. Only on quitting and restarting cTiVo does this flag get refreshed from the directory system.

**Comment by tannebil** [comment]
So if an OnDisk disappears between cTiVo restarts, that means either that the directory file entry update was not actually successful, e.g. the change got cached in Dropbox file system but never actually got written to disk so they get lost when I reboot the Drobo. I’ll try to remember to double-check that next time I reboot the Drobo.

I’m also giving some thought to adding (at least temporarily) an additional storage device that is less abstracted from HFS+ and APFS that I could use to hold my iTunes library.

Any experience with APFS on external mechanical drives? I hear things about “copy-on-write” badly fragmenting files when they get updated. I wonder if that effects the headers in video files where the metadata is stored? Or the way files get written out by the encoders? Or is one of those theoretical issues that has no practical effect 99.9% of the time.

**Comment by mackworth** [comment]
>>So if an OnDisk disappears between cTiVo restarts, that means either that the directory file entry update was not actually successful, e.g. the change got cached in Dropbox file system but never actually got written to disk so they get lost when I reboot the Drobo. 

Well, that's possible (although unlikely, as I'm sure it writes it through within an extremely short period of time). What I was saying is that if the Drobo isn't recording the metadata, you wouldn't know that until you restarted cTiVo, as it remembers recently done shows within itself until it restarts, whereupon it relies on the filesystem.

>> Any experience with APFS on external mechanical drives? I hear things about “copy-on-write” badly fragmenting files when they get updated. 
Well, that's more about video editing itself. It doesn't affect the integrity of the actual data, but editing it over and over can create slowdowns on mechanical drives, where the traditional approach of copying the whole thing may be slower during editing, but leave to less fragmentation over time.

For use as described (writing out tivo videos and then viewing it multiple times), no, not a problem. In fact, it has one big advantage: you can treat your file system as tags, putting shows in more than one directory (e.g. a recently-recorded-videos folder, as well as traditional /show/season folder), without any performance or space penalty.

So I've [posted 3.3.2 beta2](https://github.com/mackworth/cTiVo/releases/download/3.3.2Beta2/cTiVo-beta.app.zip), which has more logging in adding to iTunes area. (Set Download to Major, and you'll be told whether iTunes reported a problem, copied to a new file, or just added to its list along with the relevant paths).

On the OnDisk, if you set logging on TiVoManager to Verbose, then run some shows, and then quit and restart, and then look in logs. Search for "Adding xattr data" you'll see what shows/paths are being marked, and look for  "ShowsonDisk =" you'll see what the filesystem is reporting back.

**Comment by tannebil** [comment]
I tested out the beta with the Download folder set to an external drive formatted with APFS and iTunes Media set to the Drobo.

1. The file on the external drive was deleted when the file was added to iTunes (expected behavior)
2. The OnDisk flag didn’t appear even after restarting cTiVo

For the next test, I changed the iTunes preference to not copy the file to the iTunes Media location.

1. The file wasn’t deleted from Downloads (expected behavior)
2. The OnDisk flag appeared. I restarted cTiVo to verify (expected behavior)

For the next test, I changed the Download setting to point to a folder on the Drobo

1.The file wasn’t deleted from Downloads (expected behavior)
2, The OnDisk flag appeared after a short delay and survived a cTiVo restart (expected behavior)

For the next test, I changed iTunes back to copy the file to the iTunes Media location

1, File was deleted from Downloads (expected behavior)
2. The OnDisk flag was not set (unexpected behavior) however restarting cTiVo caused it to appear (expected behavior)

I’ve attached the log. It looks like your debug lists all the files that have the OnDisk flag set. I’ve got an extra copy of my iTunes Media folder on the external drive which is why you’ll see a bunch of duplicates on "External 8GB”.

I’m going to continue to run in the final configuration tested and rerun the files that don’t show the OnDisk flag. I’ll let you know what I observe.

**Comment by mackworth** [comment]
Thanks; nice work.  
Unfortunately, gitbhub strips attachments when you post via email, so you'll need to come to the issue page to post the log.

**Comment by tannebil** [comment]
I uploaded it by editing my comment on the web site as I kind of figured that might happen. It's there for me

**Comment by tannebil** [comment]
I processed about 25 files and had one failure to delete from the Download folder. It appears that cTiVo didn't get a success message from iTunes on the add (even through it got added) so it didn't delete the file. Here's the log entires

```
2019-06-30 23:33:58:887 -[MTDownload observeValueForKeyPath:ofObject:change:context:]@263>Changing DL status of Endeavour on Masterpiece: Confection-Great Room(4d140) to Encoded (12)
2019-06-30 23:33:59:079 -[MTTiVoManager addShow:onDiskAtPath:]@216>Adding xattr data to show Endeavour on Masterpiece: Confection (Great Room) 0x7fa890683c20 at /Volumes/Drobo/TiVoShows/Endeavour on Masterpiece - S06E03 - Confection - 2019-06-30.mp4
2019-06-30 23:33:59:082 -[MTDownload finalFinalProcessing]@2070>Empty caption file for Endeavour on Masterpiece: Confection-Great Room(4d140)
2019-06-30 23:33:59:519 -[MTDownload observeValueForKeyPath:ofObject:change:context:]@263>Changing DL status of Endeavour on Masterpiece: Confection-Great Room(4d140) to Adding To iTunes (13)
2019-06-30 23:33:59:520 -[MTDownload finalFinalProcessing]@2101>Adding to iTunes Endeavour on Masterpiece: Confection-Great Room(4d140)
        "/Volumes/Drobo/TiVoShows/Endeavour on Masterpiece - S06E03 - Confection - 2019-06-30.mp4"
        QueueFileName = "/Volumes/Drobo/TiVoShows/Endeavour on Masterpiece - S06E03 - Confection - 2019-06-30.mp4";
        QueueTitle = "Endeavour on Masterpiece: Confection";
2019-06-30 23:35:59:573 -[MTiTunes importIntoiTunes:withArt:]@230>Couldn't add iTunes or AppleTV track: Endeavour on Masterpiece: Confection (Default (Threads 5))from file:///Volumes/Drobo/TiVoShows/Endeavour%20on%20Masterpiece%20-%20S06E03%20-%20Confection%20-%202019-06-30.mp4 because (null)
2019-06-30 23:35:59:573 -[MTDownload finalFinalProcessing]_block_invoke@2108>Nil from iTunes; problem adding Endeavour on Masterpiece: Confection-Great Room(4d140) at /Volumes/Drobo/TiVoShows/Endeavour on Masterpiece - S06E03 - Confection - 2019-06-30.mp4?
2019-06-30 23:35:59:574 -[MTTiVoManager notifyForName:withTitle:subTitle:isSticky:]@1734>Notify: Endeavour on Masterpiece: Confection: TiVo show transferred.
2019-06-30 23:36:00:095 -[MTDownload observeValueForKeyPath:ofObject:change:context:]@263>Changing DL status of Endeavour on Masterpiece: Confection-Great Room(4d140) to Complete (14)
2019-06-30 23:36:01:892 -[MTDownload launchUserScript]_block_invoke@2056>For Endeavour on Masterpiece: Confection-Great Room(4d140), User task returned: 
        QueueFileName = "/Volumes/Drobo/TiVoShows/Endeavour on Masterpiece - S06E03 - Confection - 2019-06-30.mp4";
        QueueTitle = "Endeavour on Masterpiece: Confection";

```

**Comment by mackworth** [comment]
Thanks again for the detailed work. I'm reconstructing what's happened, but it's taking a while, so I'll be back to you shortly. 

The odd thing is that I'm seeing the metadata being added, but then the report back from the OS doesn't have it.
 (I think it has to do with some multithreading stuff, where the copying step makes it take much longer to "add to iTunes", and the metadata gets damaged somehow in the meantime.)

Could you try one where you enable iTunes Copying, but disable cTiVo's "Delete file after copying into iTunes"? (therefore expecting two copies to show up in report)?

Note that you can do a Spotlight search for "cTiVoDownload showName" to see which are marked on the disks at any given moment.  (e.g. "cTiVoDownload Costa Rica")

**Comment by tannebil** [comment]
I will add that my Drobo fell over last week with unrecoverable HFS+ corruption so maybe there were lesser corruption issues that were creating random issues. Disk Warrior "fixed" the corruption issue but had way to many orphaned file pieces to be trusted so I blew everything away and recovered from Time Machine. I'm redoing all my shows that are still on TiVo and have missing OnDisk info because neatness counts and to flush out any intermittent problems.

**Comment by mackworth** [comment]
Beta 3 is released, and it should improve some of the issues above; also cleans up a couple more Catalina issues.

**Comment by rqchin** [comment]
I'm not sure this is a 3.3.2 beta issue but that's the version I'm running. I have a dozen shows that are showing "Waiting for Ads", from as long ago as last Thursday, 5 days ago. Can the update from TiVo with the Skip Data take that long to become available?

**Comment by mackworth** [comment]
Nope.  It shouldn’t wait more than 6 hours, so that’s a problem. If you want me to see what’s going on, if you could take a screenshot of the queue, then turn Debug logging to Verbose, then Pause Queue and Resume queue. For better or worse, that may launch the shows, giving me no info on why it’s waiting, but it’s worth a try. If it doesn’t, try quitting and restarting cTiVo, then post the log here.

**Comment by rqchin** [comment]
OK, I made these changes and all those pending Waiting for Ads went away but maybe unexpectedly, it seemed to do them one by one just before each one was ready to download. The screen capture is from when it had done 10 of them and had two left to do, so maybe that and the logs will help trace what was happening.
[cTivo_skipmode.zip](https://github.com/mackworth/cTiVo/files/3527954/cTivo_skipmode.zip)

**Comment by rqchin** [comment]
@mackworth Perhaps I'm using the program incorrectly or in a way that is unintended but I try not to clear out my queue (but believe me, I'd like to) because when the queue gets cleared, all the shows on the Tivo that have been recorded lose their check mark and then I lose track of what's been exported inside the cTivo interface. Am I missing some other way to see in the upper panel that a show has already been exported?

**Comment by mackworth** [comment]
So, there's a Queued flag (whether a show is in the queue or not, and there's also an OnDisk flag (whether a show has been downloaded and is still available on your disk). Subscriptions also keep track of which shows they have downloaded to avoid downloading the same show twice, but that's not visible.

**Comment by rqchin** [comment]
I see. I was using the Queued flag as the indicator of it being processed. I'll try using the OnDisk indicator instead.

**Comment by tdlivings** [comment]
I clear off the queue and leave the latest dated file on the top and then I know the list point done for everything below it because I off load the data from a scrub drive to a QNAP NAS for archiving.

**Comment by rqchin** [comment]
@tdlivings Great idea - thanks! I wanted to do the same with my Synology but couldn't figure out how to do it and not lose track of what had been done. I could just make the Synology the destination for cTivo but that is too risky if the network connection gets lost for some reason.

**Comment by mackworth** [comment]
So, 3.3.2 beta has been renamed to 3.4.0 and released. So closing this track.
