### ISSUE TITLE
Skipmode/Comskip issues

### ISSUE THREAD

**Issue by splark** [mackworth/cTiVo#376]
I recently noticed that some older shows, such as Seinfeld, are showing up on Tivo with Skip data, regardless of what time they are recorded.  This generally great, but I am having an issue sometimes with the end of the show being clipped.

I developed a custom ComSkip config to address this, but I am finding that once skip data has been created for an episode (either by Skip mode or ComSkip), Ctivo will not regenerate it when I reschedule the download or delete it from the queue and re-add it.  Changing the Strategy to ComSkip only does no seem to help.

Is there a way to force Ctivo to regenerate this data?

Steve

**Comment by mackworth** [comment]
Ah, yes. Old saying: there’s only three hard problems in computer programming: knowing when to invalidate a cache, and off-by-one errors. 

If you right-click on the show (or download), and hit “Reload all info”, it should throw away the Skipmode commercial breaks. (Note: if the download is marked as using Skipmode and it’s within the Skipmode-allowed time range, then cTiVo will promptly reload them, so first mark it as not-Skipmode. )

**Comment by mackworth** [comment]
did that work for you?

**Comment by splark** [comment]
Sorry take so long to get back to you.  That's what I needed.

Thanks

**Comment by splark** [comment]
Thans\ks

**Comment by mackworth** [comment]
No problem; glad it worked.
