### ISSUE TITLE
Download fails with "invalid MAK"

### ISSUE THREAD

**Issue by mrfusiontm** [mackworth/cTiVo#377]
I have one episode of a show that keeps failing to download with an "invalid MAK" error.
I tried an episode of a different show and it downloaded just fine.
[com.cTiVo.cTiVo 2019-06-22--15-02-58-737.log](https://github.com/mackworth/cTiVo/files/3316967/com.cTiVo.cTiVo.2019-06-22--15-02-58-737.log)

I tried downloading the latest beta and it still behaves the same way.

**Comment by mackworth** [comment]
That is reported by the decryhption software tivodecode, which probably means a glitch in the digital stream. There’s two things you can try, but I’ll warn you that neither have a high probability of success.

First is to switch to TS for this download (this is not the normal error message for this case; cTiVo switches automatically when it detects a problem with PS transmission). Just right-click on the download table, enable the useTS column, turn it on for this download, and then run it again. (You may need to turn off the queue (Cmd-U) momentarily to allow you to Reschedule the download without it immediately launching it.)

Second would be to switch to TiVoLibre in Advanced Preferences. TiVoLibre is said to handle more error cases than Tivodecode, but I personally haven’t seen that to be the case. This requires you to have the Java Runtime installed on your machine if you don’t have it already. You can get that here: https://www.java.com/en/download/

Let me know if either of those help.

**Comment by mrfusiontm** [comment]
No matter what I try, I can not get it to switch to TS to download.  I removed the queue, added the useTS column,  paused the queue and rescheduled it.  Turned on useTS and after it finished with "Waiting for the TiVo" and started to download, it toggled useTS off.  I even went into channels and turned on TS for this station and it still turns of useTS as soon as it starts to download. 

TiVoLibre failed immediately as well.

**Comment by mackworth** [comment]
As I suspected, the first part means that that it really is a PS channel (once it starts downloading and cTiVo sees the contents, then it will switch to the appropriate transport).  So that's not the cause.

Unfortunately, with TL failing as well, there's not really any chance of getting that particular show to download.

**Comment by mrfusiontm** [comment]
Ok, well thanks for the suggestions!  And thanks for a great program!

**Comment by mackworth** [comment]
You’re welcome, and thanks for the praise!
