### ISSUE TITLE
Tivo/Rovi guide data wrong/setting removed in 3.3

### ISSUE THREAD

**Issue by wjmt3** [mackworth/cTiVo#378]
The notes for version 3.3 mention:
"Removed "Prefer TVDB's episode Info" option as TiVo's data is now accurate through RPC"

Lately, I've been seeing some VERY wrong episode information, in which the Tivo/Rovi data directly contradicts the information provided by the producers.

Therefore, I would like to see a preference for TVDB info make a comeback.

How wrong? Example:

Diners, Drive-ins and Dives
Episode: "Piling on the Pork"
Foodnetwork.com: Episode 30.1
Tivo: Episode 29.9

**Comment by mackworth** [comment]
I believe it’s still there, just no UI. 

In Terminal, type `defaults write com.ctivo.ctivo TrustTVDBEpisodes -bool YES`   

Let me know if that works for you, and how often you’re seeing a problem with the data.

**Comment by wjmt3** [comment]
Thanks! I assume that if I want to undo, I simply change YES to NO? It's been a while since I've used defaults write.

**Comment by mackworth** [comment]
Correct. It should automatically reload the S/E info when you set this.  Note that you can also just manually edit the S/E info of one show in the drawer that opens to the side when you double-click on a show.

Also, if you set the debug level of Show to Detail (in Advanced Preferences), before you do that (or if you change it back), then it will list all the differences.  Search in the log file (just double click into Console) for "different Sea/Eps"

**Comment by wjmt3** [comment]
Thanks, Hugh. I'll give this a try in the next few days. I've had a lot on my plate. I'll close this for now and follow up when time allows. Thanks also for the additional tip!
