### ISSUE TITLE
Program not downloading

### ISSUE THREAD

**Issue by KevDoc** [mackworth/cTiVo#379]
I’ve been using cTivo successfully for some time, but I’m currently getting “server busy” error and the program I regularly download (Formula 1) won’t download. This started happening on the 30th June and I’ve been trying repeatedly since hoping it was a temporary glitch but it’s still not downloading.

I’ve temporarily had an issue in the past where a program would only partially download and then fail, but that problem simply resolved itself and this problem is different as it doesn’t even start downloading, it just cycles through the “waiting on tivo” stage.

I’ve verified that the program on the tivo isn’t corrupted as it still plays on the tivo and I’ve also tried rebooting the tivo by disconnecting the power.

The tivo is a T6 and the Mac I’m using is a Late 2012 Mac Mini running the latest version of MacOS. The cTivo version is the current version 3.3.1.

**Comment by mackworth** [comment]
The TiVo’s downloader is very brittle. If cTiVo says Server Busy, then usually that means the TiVo has received requests for downloads either at once or one right after the other. cTiVo tries very hard to avoid triggering this problem (hence the TiVo waiting phase).  So one cause can be having cTiVo running on two different Macs as I occasionally do accidentally while testing.  Sometimes it just happens after some internal problem. I haven’t heard of a show repeatedly causing the problem, but it certainly might. (Note that a show can be corrupt and not be downloadable, and yet still play fine. The download process is much more susceptible to digital glitches. )

Unfortunately, once you get that msg, you usually need to reboot the TiVo to reset the download process. Sometimes it resets itself after a few hours, but usually not. cTiVo’s retries will almost certainly fail immediately until you reboot. 

So I would suggest rebooting your TiVo, set your cTiVo Debug level to Major, try downloading a couple other shows to make sure there’s no general problem, then try the problematic show again. If it goes back into Server Busy only on that show, then I don’t think there’s much I can do, but happy to look at the log to confirm that.

**Comment by KevDoc** [comment]
Thanks I’ll try some of your suggestions, though I’ve already tried rebooting the tivo. For whats it worth I’ll also try re-installing the cTivo app even though it sounds like it’s likely to be a problem on the tivo end. 

Could this be an issue with the latest version of cTivo, I don’t recall when I updated to 3.3.1?

**Comment by KevDoc** [comment]
Ok so circling back, rebooted the tivo several times ( unplugged power) and other programs are downloading ok. Here is the log.
[com.cTiVo.cTiVo 2019-07-14--19-12-51-139.log](https://github.com/mackworth/cTiVo/files/3390480/com.cTiVo.cTiVo.2019-07-14--19-12-51-139.log)

**Comment by mackworth** [comment]
so, there's a couple of odd things in this log. The first is that your TiVo is "appearing" twice as DVR 9DAD and DVR 9DAD (2). You wouldn't have any really old Apple equipment on your net, would you?  Old Airport express, or non-upgraded Macs?  There's an old bug where network addresses would get cached, and then when the device reboots, it thinks another device already has its name, so it adds (2) and tries again.

But even if so, I don't think that's causing your problem. The other is a possibility. Assuming that the Formula One Racing shows are both on the exact same channel, it's very odd that the British one failed on TS, then switched to Program Stream and successfully downloaded, but the Austrian one gets Server Busy when it tries with Transport Stream.

First, in Edit>Channels, is the "Default to Using TiVo's Transport Stream option on? And/or is "Use TS" for this channel switched on? If either are true or even if Use TS is "Maybe" (a dash), then clear it (neither the check, nor the dash but empty.) This will force cTiVo to use Program Stream on that channel.

Then I would reboot your TiVo, then download a show on a different channel entirely (to validate everything is fine), then try downloading the Austrian show one last time and post the log.  (If you could note the time you rebooted your TiVo, it will make reading the log a little easier.)

**Comment by KevDoc** [comment]
Ok thanks, really appreciate the support, will give that a try tonight. The oldest Apple product I have is the mac mini that I’m downloading to, it’s a 2012 model but the OS is upto date. The only other Apple gear I have are iPhone’s, iPad’s and an iMac which are all more upto date.

**Comment by KevDoc** [comment]
Use TS was switched on, so as instructed I switched it off, rebooted tivo, and it worked!!! Fantastic! Thanks again for the help, do you still want to see the log? If so here it is, the tivo was rebooted at 7:41pm.
[com.cTiVo.cTiVo 2019-07-16--00-38-29-296.log](https://github.com/mackworth/cTiVo/files/3394804/com.cTiVo.cTiVo.2019-07-16--00-38-29-296.log)
