### ISSUE TITLE
Limit transcoder to single CPU thread

### ISSUE THREAD

**Issue by bryanmcain** [mackworth/cTiVo#380]
When using the GUI version of handbrake I am able to specify an encoder option "threads=1."  Doing this will limit the amount of processing power that handbrake uses to what appears to be a single CPU core.  

I recognize that this will greatly slow the total encode time, but as the primary usage of this machine is as a plex server, having some amount of CPU available to other processes is pretty important.

Is there a way to specify this option in cTiVo?  I've tried putting the above command in various places and it still uses all available CPU when encoding.

**Comment by mackworth** [comment]
Sorry for delay; I've been trying some testing and research. Where do you see the option on encoder in the GUI?  I don't see it in the CLI options, and they seem to be indicating that it's not available here: https://github.com/HandBrake/HandBrake/issues/1752

**Comment by bryanmcain** [comment]
![image](https://user-images.githubusercontent.com/4225686/63270960-20d8a600-c267-11e9-9ca3-f3bf440b694a.png)

This is the latest version, I believe (1.22).

**Comment by bryanmcain** [comment]
No worries on the delay (as you can see, I wasn't able to get back to this right away either).

From that same thread you linked:

> Some encoders (x264 for example) do have an extra argument "threads=x" however do note, this is only encoder threads, not decode, filters, sync, audio etc. On higher end systems you can effectively introduce a bottleneck to slow things down. Probably less so on a quad core.

**Comment by mackworth** [comment]
Two paths here. First, if you create a Preset in Handbrake, then you can create a Format in cTiVo that simply uses that Preset. Easiest is to Duplicate the "HB Default" Format, and use the pull-down on the right to get to all the Presets, including your custom ones.

Second, as it is encoder-specific, the Handbrake CLI says to use "-x" to pass those options through.  So if you just put "-x threads=1" in the cTiVo's Other Options for Encoder, then it should get to the encoder.

**Comment by bryanmcain** [comment]
Thanks! I'll test as soon as I can.

**Comment by mackworth** [comment]
Seems to work. I did the latter path, and on a sample download, it dropped CPU usage for HandbrakeCLI from 92% to 20%. It also dropped throughput from 700 KBps to 250KBps

**Comment by bryanmcain** [comment]
Yes, it is working for me as well.  I tried the first option - the list of handbrake presets is so long that it didn't occur to me at first to look for my custom one all the way at the end.

Thanks!
