### ISSUE TITLE
Subscriptions failing

### ISSUE THREAD

**Issue by sarpent** [mackworth/cTiVo#382]
Subscriptions stopped working for me many months ago following the last major update (currently using v3.3.1 - 1053). Only manual downloads work. I'm guessing that I have a config file somewhere that's corrupted. Where are all the config files stored? At this point I'm assuming that I need to delete everything and start over.

**Comment by mackworth** [comment]
The Subscriptions are stored in your preference file. In Finder, Cmd-Shift-G > ~/Library/Preferences ; it’s the file com.cTiVo.cTiVo.plist

But if you’re seeing the Subscriptions listed on the cTiVo screen, that’s probably not the reason. 

To diagnose, In Adv Prefs, if you set Subscriptions Debug Level to Verbose, then right-click on a Subscription that should have worked, then Re-Apply Subscription. then Help>Show logs in Finder and open the latest log in Console, it should tell you why it didn’t work. (Don’t forget to turn off Verbose afterwards)

If you want help reading the log file, just post it here (don’t use email reply, though). 

C

**Comment by testmack** [comment]
Any luck?

**Comment by sarpent** [comment]
I think so. Reapplying one of the subscriptions seems to have fixed something, apparently even for subscriptions that I didn’t reapply. Thanks for your help.

**Comment by mackworth** [comment]
Good to hear, although sorry you had the problem in the first place!
