### ISSUE TITLE
Tivo Skip on Tivo, but not cTivo

### ISSUE THREAD

**Issue by bdollahite** [mackworth/cTiVo#383]
My Tivo units (three of them all show the program has SKIP available.  Yet cTivo does not indicate anything — blank, no SKIP icon.   As such I am not able to force skip data to be downloaded.  I have reloaded all info (I assume this includes shows attributes like SKIP) data several times, same results.

**Comment by mackworth** [comment]
That's interesting.  Can you set Debug level to Detail, quit and restart cTiVo, then attach the log (Help>Show logs in finder) to this msg thread?

**Comment by bdollahite** [comment]
Requested log file with preference set to detail attached
[com.cTiVo.cTiVo 2019-09-15--03-36-05-779.log](https://github.com/mackworth/cTiVo/files/3614599/com.cTiVo.cTiVo.2019-09-15--03-36-05-779.log)

**Comment by bdollahite** [comment]
FYI - after 8 day and two Tivo quits and restarts — the skip finally appeared.   So I am not sure what else needs to donees the issue is no longer in play.  Note — I also applied a new Mojave update from Apple earlier tonight.  Mot sure if that update fixed an underlying issue.

**Comment by bdollahite** [comment]
Correction — no Tivo restarts (that was a typo) — should have read "two cTivo restarts."  Both restarts done today, first was part of an Apple software update that required a restart (now running 10.14.6), second restart of cTivo was a few minutes later.  Then iMac was idle (sleep mode), and when awaken - a clear Tivo SKIP button appeared where I expected it to be, so I forced Tivo's skip data  for the download to be manually load — it work.   Hence I no longer have an issue (other than why it happened in the first place).

**Comment by mackworth** [comment]
So, not surprisingly, I see the same thing in the logs, which has no details until after the reboot. There's no indication of a problem in the prior invocations, but that was before changing to Detail (which you should change back to Major now). There might have been a network problem previously, or maybe the software update cleared something.  Well, let me know if you have any other issues.

**Comment by bdollahite** [comment]
thanks - agree with closing
