### ISSUE TITLE
Question: capacity

### ISSUE THREAD

**Issue by macsrwe** [mackworth/cTiVo#387]
I can't find this answered anywhere.

Is there a way to get cTivo to display the "percent capacity used" on the TiVo?

**Comment by mackworth** [comment]
Not currently supported, but could be added. How would this be useful to you?

**Comment by macsrwe** [comment]
My TiVo is 3000 miles away from me, recording a bunch of shows. If it starts getting too full before I'm scheduled to return home, it would be nice to have the option to trim the stuff I want least -- especially since it's getting to be the season where network shows that have been on hiatus all summer will start recording again.

**Comment by tdlivings** [comment]
there is an app for that, I use the TiVo app for iOS and login using TiVo subscription credentials. The app shows up coming, recorded and allows me to schedule new recordings while offsite in addition to deleting and general management abilities.

**Comment by macsrwe** [comment]
You're 100% right. I was on my Mac when I was trying to get this done, and it entirely slipped my mind that by moving over to my iPhone, I already had the functionality I needed.

**Comment by mackworth** [comment]
Well, I've been meaning to get this done, so just added it to 3.4.0 (just released). It also shows network connectivity info and current activity.
