### ISSUE TITLE
After upgrade to MacOS Catalina "cTiVo cannot acess iTunes, probably due to Automation Permission problem in Mojave."

### ISSUE THREAD

**Issue by gew95001** [mackworth/cTiVo#390]
I suspect this is due to iTunes being split into separate apps. There is no cTiVo entry in Privacy->Automation. If this will be fixed in the next version please feel free to close this.

**Comment by mackworth** [comment]
Try the 3.3.2 beta version. It should fix this (for cTiVo, not the new cTV yet).  Let me know if you still have a problem.
https://github.com/mackworth/cTiVo/releases/tag/3.3.2Beta4

**Comment by gew95001** [comment]
I can now check the box to allow cTiVo to add to Apple TV. If I have any issues with the actual adding I'll submit another issue. Thanks for the quick response - looking forward to trying CTV.

**Comment by mackworth** [comment]
So 3.4.0 is now released, which fixes this, and also the cTV version as well.
