### ISSUE TITLE
Encodes overlapping with downloads

### ISSUE THREAD

**Issue by sfenwick** [mackworth/cTiVo#391]
I'd rather only run one encode thread at a time; it nicely loads the cores on my system. But that means the downloads aren't happening.

Is is possible to allow downloads to happen in parallel with encodes? Even if it were just downloading the next show while it's encoding the previous, that would be fine.

**Comment by mackworth** [comment]
_Downloads in parallel with encodes:_ 
In general, cTiVo is set up to do this, but that depends on the encoder. In particular, the Default format uses a shell script *ffmpeg_ac3.sh* to add commercial cutting features to ffmpeg, but that requires having the full source file downloaded before encoding begins.

If you don't need commercial cutting, ffmpeg can do this. An example is `Faster` Format. Unfortunately, while testing this note, I found a mistake in the current Faster, which you can fix by adding `<<<INPUT>>> -c:a copy` in the Audio Options of a Duplicate copy of Faster. ( You can also remove the `-preset veryfast -crf 25 ` which is what makes it faster at the expense of quality).

Attached is this revised Format, called Simultaneous. Just download/decompress the file, and use the `File>Import Formats` menu command to load it into your copy of cTiVo.

[simultaneousFormat.plist.zip](https://github.com/mackworth/cTiVo/files/3775280/simultaneousFormat.plist.zip)

Let me now if that works for you.

_Downloading the next show while the previous is encoding, and then wait until the previous one is complete_.
I see the benefit, but architecturally, this would be very hard. We optimize for parallel execution as much as possible (downloads, captions, commercial detection, etc), setting all those up at launch, so having it stop after the download would be hard to implement.

**Comment by mackworth** [comment]
Have you been able to try this Format?

**Comment by mackworth** [comment]
I've added Simultaneous to version 3.4.1 as I think it's useful. Doesn't do commercial cutting, nor AC3 passthrough, but otherwise is the same as Default and does do simultaneous download/encoding.
