### ISSUE TITLE
Mojave and Catalina and iTunes

### ISSUE THREAD

**Issue by tdlivings** [mackworth/cTiVo#392]
If we are staying put on Mojave, what are your suggestions on your new version? Should we update or stay with previous version?

Thank you

**Comment by mackworth** [comment]
Definitely upgrade to 3.4.0. Should be no issue, even back to 10.10.

**Comment by tdlivings** [comment]
Thank You

**Comment by mackworth** [comment]
To add some color here, even thought 3.4.0 fully supports Catalina, it also has a bunch of new features for older OSs, so I do recommend updating.

For those not up on Apple's latest swerves, MacOS Catalina has obsoleted iTunes, and replaced its functionality with multiple pieces. Just like iOS, there’s a Music app, a TV app, a Podcast app, and the Finder does your device management (e.g. moving files). 
 
Thus I had to do some rework to support the new TV app, but iTunes is still fully supported for the older OSs (all the way back to 10.9, although you can't use Handbrake Formats with 10.9).

And to update your scorecard, AFAICT, Apple now has a TV app (with a logo of TV on iOS and MacOS and TVOS on Apple TV), a hardware device called Apple TV, a service called Apple TV, and a premium service called Apple TV+.

**Comment by mackworth** [comment]
Re Apple TV:
https://imgur.com/a/GVdsG7r
