### ISSUE TITLE
Encoding fail

### ISSUE THREAD

**Issue by mrfusiontm** [mackworth/cTiVo#394]
I believe the last three shows cTiVo tried to download all failed at the encoding stage.  All three are from the same station.  I'll attach the verbose log file of one of them.

[com.cTiVo.cTiVo 2019-11-05--13-15-26-165.log](https://github.com/mackworth/cTiVo/files/3809133/com.cTiVo.cTiVo.2019-11-05--13-15-26-165.log)

I'm using version 3.4.0 and I'm still on Mojave.

**Comment by mackworth** [comment]
so, ffmpeg is definitely not happy with the downloaded file:

```

 ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)
  configuration: --prefix=/opt/local --enable-swscale --enable-avfilter --enable-avresample --enable-libmp3lame --enable-libvorbis --enable-libopus --enable-librsvg --enable-libtheora --enable-libopenjpeg --enable-libmodplug --enable-libvpx --enable-libsoxr --enable-libspeex --enable-libass --enable-libbluray --enable-lzma --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libfribidi --disable-libjack --disable-libopencore-amrnb --disable-libopencore-amrwb --disable-libxcb --disable-libxcb-shm --disable-libxcb-xfixes --disable-indev=jack --enable-opencl --disable-outdev=xv --enable-audiotoolbox --enable-videotoolbox --enable-sdl2 --disable-securetransport --mandir=/opt/local/share/man --enable-shared --enable-pthreads --cc=/usr/bin/clang --arch=x86_64 --enable-x86asm --enable-libx265 --enable-gpl --enable-postproc --enable-libx264 --enable-libxvid --enable-nonfree --enable-libfdk-aac
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[h264 @ 0x7fde3d004a00] missing picture in access unit with size 2205383
[h264 @ 0x7fde3d004a00] data partitioning is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[h264 @ 0x7fde3d004a00] If you want to help, upload a sample of this file to ftp://upload.ffmpeg.org/incoming/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[h264 @ 0x7fde3d004a00] no frame!
[mpegts @ 0x7fde3d00da00] decoding for stream 0 failed
[mpegts @ 0x7fde3d00da00] PES packet size mismatch
[mpegts @ 0x7fde3d00da00] Could not find codec parameters for stream 0 (Video: h264 ([27][0][0][0] / 0x001B), none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 0x7fde3d00da00] Could not find codec parameters for stream 2 (Unknown: none ([151][0][0][0] / 0x0097)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpegts, from '/tmp/ctivo/bufferThe Flash - S06E04 - There Will Be Blood-7.mpg':
  Duration: 01:01:00.66, start: 3100.807467, bitrate: 4040 kb/s
  Program 1 
    Stream #0:0[0x12a5]: Video: h264 ([27][0][0][0] / 0x001B), none, 90k tbr, 90k tbn, 180k tbc
    Stream #0:1[0x12a6]: Audio: ac3 ([129][0][0][0] / 0x0081), 48000 Hz, 5.1(side), fltp, 384 kb/s
    Stream #0:2[0x12a8]: Unknown: none ([151][0][0][0] / 0x0097)
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (ac3 (native) -> aac (native))
  Stream #0:1 -> #0:2 (copy)
Press [q] to stop, [?] for help
[NULL @ 0x7fde3d004a00] missing picture in access unit with size 2205383
[h264 @ 0x7fde3d801200] data partitioning is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[h264 @ 0x7fde3d801200] If you want to help, upload a sample of this file to ftp://upload.ffmpeg.org/incoming/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[h264 @ 0x7fde3d801200] no frame!
[h264 @ 0x7fde3d802a00] top block unavailable for requested intra mode
[h264 @ 0x7fde3d802a00] error while decoding MB 17 0, bytestream 2875276
[h264 @ 0x7fde3d802a00] concealing 3600 DC, 3600 AC, 3600 MV errors in I frame
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
[h264 @ 0x7fde3d803000] top block unavailable for requested intra mode
[h264 @ 0x7fde3d803000] error while decoding MB 1 0, bytestream 2416051
[h264 @ 0x7fde3d803000] concealing 3600 DC, 3600 AC, 3600 MV errors in I frame
[NULL @ 0x7fde3d004a00] non-existing SPS 29 referenced in buffering period
[NULL @ 0x7fde3d004a00] non-existing SPS 2 referenced in buffering period
[NULL @ 0x7fde3d004a00] non-existing SPS 32 referenced in buffering period
[h264 @ 0x7fde3d806000] non-existing SPS 29 referenced in buffering period
[h264 @ 0x7fde3d806000] non-existing SPS 2 referenced in buffering period
[h264 @ 0x7fde3d806000] non-existing SPS 32 referenced in buffering period
[h264 @ 0x7fde3d806000] top block unavailable for requested intra mode -1
[h264 @ 0x7fde3d806000] error while decoding MB 2 0, bytestream 1337108
[h264 @ 0x7fde3d806000] concealing 3600 DC, 3600 AC, 3600 MV errors in I frame
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
[NULL @ 0x7fde3d004a00] non-existing SPS 14 referenced in buffering period
[h264 @ 0x7fde3d806600] Invalid NAL unit 0, skipping.
    Last message repeated 1 times
[h264 @ 0x7fde3d806600] non-existing SPS 14 referenced in buffering period
[h264 @ 0x7fde3d806600] top block unavailable for requested intra mode
[h264 @ 0x7fde3d806600] error while decoding MB 2 0, bytestream 1920311
[h264 @ 0x7fde3d806600] concealing 3600 DC, 3600 AC, 3600 MV errors in I frame
Too many packets buffered for output stream 0:1.
[aac @ 0x7fde3d010a00] Qavg: 668.495
[aac @ 0x7fde3d010a00] 2 frames left in the queue on closing
Conversion failed!
```

There is a version 4.2 ffmpeg, so we could try that, but there's no indication that they've done any work on "data partitioning". You said this is over multiple files, can I see the ffmpeg log from the others? (Verbose isn't necessary, you can just run it at Major; all encoding failures dump the ffmpeg log to the cTiVo log.)

**Comment by mrfusiontm** [comment]
Yeah, I'll try and get that to you as soon as I get home.

**Comment by mrfusiontm** [comment]
Here's a log file of trying to import the three shows

**Comment by mackworth** [comment]
Unfortunately, posting through an email reply strips the attachments, so I didn't get the log file.

**Comment by mrfusiontm** [comment]
Sorry, I'll post it online

**Comment by mrfusiontm** [comment]
I tried downloading them again, then updated to the newer ffmpeg and tried again.  Still failed


[com.cTiVo.cTiVo 2019-11-07--01-48-55-271.log](https://github.com/mackworth/cTiVo/files/3819745/com.cTiVo.cTiVo.2019-11-07--01-48-55-271.log)

**Comment by mackworth** [comment]
So that log covers the time period of 2019-11-06 17:48 to 2019-11-07 05:11:00, and I'm not seeing any downloads at all during that period?

**Comment by mrfusiontm** [comment]
Crap, I must have grabbed the wrong one.  I'll double check when I get home
and send a new one.  Sorry.

**Comment by mrfusiontm** [comment]
Ok, hopefully this one is better.

[com.cTiVo.cTiVo 2019-11-08--01-38-13-316.log](https://github.com/mackworth/cTiVo/files/3824659/com.cTiVo.cTiVo.2019-11-08--01-38-13-316.log)

**Comment by mackworth** [comment]
It was, and I"ve attached the ffmpeg reports below (one for each show). 

So, those all look like normal glitchy failures to me: where it's seeing a bunch of failed frames, but then  resynching until it gives up. Could your cable have a weak connection? Are other shows making it through ok? Do those have any missing frames? You can check signal strength in TiVos settings. I note these are all CW, so maybe that channel is weak?

[ffmpegLogs.txt](https://github.com/mackworth/cTiVo/files/3826134/ffmpegLogs.txt)

**Comment by mrfusiontm** [comment]
Yeah, I was suspicious that they were all from the same channel.  I've
never had a problem with that channel in the past (including these shows
all worked in the last couple of weeks).  These are the only shows in the
queue right now, but I'll try forcing a download of a show from another
channel when I get home.

I'm sure you can probably see in the log that I also updated to the latest
ffmpeg as well.

**Comment by mackworth** [comment]
Yup.  I also just released 3.4.1, which includes the latest ffmpeg and other binaries as well as a few other fixes.  Nothing (other than the binaries) that should affect this though.

I would also try Handbrake Format to see if that helps.

**Comment by mrfusiontm** [comment]
I'll give both of them a try and report back.  Thanks!

**Comment by mrfusiontm** [comment]
I tried downloading a different show and it worked just fine.
I switched to the HB_SuperHQ and the first of the CW shows downloaded
without a problem.

Not sure what changed to make that ffmpeg suddenly stop working.  Do the
stations control how the video is encoded on the TiVo?  I would have
thought that's all controlled on the local machine.

**Comment by mackworth** [comment]
Digital channels (all of them now) are encoded by the original source/station/cable company, and just saved on disk by the TiVo. Then they are encoded with your MAK during the download process, which makes it particularly sensitive to errors. So there’s multiple phases where things might happen, and many, many choices for encoders and possible error sources along the way. For example, maybe CW is transmitting along a weak frequency in your particular cable line, so digital errors are introduced. Handbrake uses many of the same libraries as ffmpeg, but error recovery is quite different. 

Overall, in the aggregate statistics cTiVo collects, looks like about a 2% failure rate (after retries, which do frequently work).

It would require some intense video knowledge and access to various hidden measurement points to figure exactly what’s going on here. Fortunately, it sounds like you have a viable path to download them. I’ll close this for now, but let me know if it still has a problem.

**Comment by mrfusiontm** [comment]
As always, Thank you!

**Comment by mrfusiontm** [comment]
Ah we spoke too soon.  One of the other CW shows failed even after I set to Hi_SuperHQ and deleted the que
[com.cTiVo.cTiVo 2019-11-09--01-45-41-433.log](https://github.com/mackworth/cTiVo/files/3827811/com.cTiVo.cTiVo.2019-11-09--01-45-41-433.log)
ue and re-downloaded it.

**Comment by mackworth** [comment]
Sorry to hear it, but not terribly surprising; error recovery is hard.
