### ISSUE TITLE
cTivo with Comskip creates damaged file?

### ISSUE THREAD

**Issue by cgurley** [mackworth/cTiVo#400]
Recently I have noticed that I have a few shows that download and go though the normal comskip process and encoding - but when I play back the video it goes to a point where a commercial used to be and from that point on the length of the video is just a black screen. I do not hear sound or see video but quicktime continues to play the file. Moving the file to plex says the entire video is there, but stops playing once the "black screen" of the video begins.

If I download again the symptom happens in the same spot as before - but if I remove comskip from the process the video plays from start to finish with full video and sound. I have never seen this happen but it has now happened 3 times in the last week. Any ideas on what I can do to resolve this?

cTivo Version 3.4.1 (1108)

**Comment by mackworth** [comment]
Interesting. Which Format are you using?  (e..g Default or HB1080p)  Are the chapters still marked properly? Were these all on the same channel?  Does it happen on the first commercial break?

In Adv Prefs, turn on "Don't delete temp files" and turn logging up to Detail, then run the same show to completion Now go to the temp directory, and delete the large mpg files, and zip up the rest, including the ffmpeg directory (assuming Default format) and post it here.

**Comment by cgurley** [comment]
[
[cTivo.zip](https://github.com/mackworth/cTiVo/files/3992588/cTivo.zip)
](url)

Just tried a new show and got the same results - I have attached the files you requested. Thank you for taking the time to look at this!

**Comment by cgurley** [comment]
Answers to the questions above:

**Which Format are you using?** Default
**Are the chapters still marked properly?** I don't use the mark chapters option, I cut instead.
**Were these all on the same channel?** Yes, so far it has happened on A&E which is where I record a lot of things.
**Does it happen on the first commercial break?** It does not appear to happen on the first commercial break.

**Comment by mackworth** [comment]
sorry for delay; it took a while to find the issue and possible fix. It looks like there was an ffmpeg error about 24 minutes into the file.  For better or worse, it didn't fail, just created a weird file. Assuming that's where the black appears, I think I found a fix.  
Try a new Format, duplicating Default in Edit>Edit Formats, but adding ` -movflags delay_moov` after `h264` on the Video options line. This shouldn't affect anything other than fixing this error. Let me know if that fixes the problem, as I may make it standard.

**Comment by mackworth** [comment]
Spoke too soon. hold off on this test.

**Comment by mackworth** [comment]
Spoke too soon on holding off; you may proceed.  (One of my tests failed, but it was for a totally different reason.)

**Comment by cgurley** [comment]
Just ran the test with the new settings and it did the same thing.

**Comment by mackworth** [comment]
Hmmm. Can you do the same thing with the screenshot and the packed up log files?

**Comment by cgurley** [comment]
Here are the logs from the last attempt - thanks for looking!
[cTivo.zip](https://github.com/mackworth/cTiVo/files/4013265/cTivo.zip)

**Comment by mackworth** [comment]
Wait... The log file says "cTiVo-10.7.app"??  Is that correct? That version is really really not supported at this point.  Or are you reaching in there for the ffmpeg executable (also not good)?

Assuming that's not right...

I'm going a bit blind here, as this stuff is not particularly documented in ffmpeg.  In segment 003500 to 004320, you're getting the error: 
`Cannot write moov atom before AC3 packets. Set the delay_moov flag to fix this.` 
The patch I gave you does this, and ffmpeg seems to recognize the delay_moov flag or it would have given an error, but it also seems to have no effect.

Try changing `-movflags delay_moov` to `-movflags empty_moov+delay_moov` You can either run the whole process again, or if you still have the segments folder available, you could run the following command in Terminal:

`/Applications/cTiVo-10.7.app/Contents/Resources/../MacOS/ffmpeg -ss 3500.13 -i '/Users/cgurley/cTivo/bufferLive PD - S00E35 - Top 40 Moments of 2019.mpg' -max_muxing_queue_size 4000 -map 0:1 -map 0:0 -map 0:0 -vcodec h264 -movflags empty_delay_moov  -profile:v main -level 3.1 -vf 'yadif,scale=w=floor(iw*min(1\,min(1280/iw\,720/ih))/2)*2:h=-2' -c:a:0 aac -ac:a:0 2 -c:a:1 copy -to 820.09 '/Users/cgurley/cTivo/Live PD - S00E35 - Top 40 Moments of 2019_ffmpeg/segments/segment_003500_004320.mp4'`

Then look for that error msg again in the text output.

**Comment by cgurley** [comment]
The version I see when going to about is 3.4.1?

I will try the suggestion you posted

**Comment by mackworth** [comment]
What's the name of the cTiVo on disk?  and can you paste a smapshot of the Format edit page?

**Comment by cgurley** [comment]
![Screen Shot 2019-12-31 at 7 47 59 PM](https://user-images.githubusercontent.com/30550521/71636964-a94c5780-2c06-11ea-8112-b5d5af1dbf06.png)
![Screen Shot 2019-12-31 at 7 48 24 PM](https://user-images.githubusercontent.com/30550521/71636967-afdacf00-2c06-11ea-8263-e64bd25bae0e.png)

**Comment by mackworth** [comment]
So. In your /Applications folder, do you have both a cTiVo and a cTiVo-10.7?  If so, unless you need the 10.7, go ahead and delete it. 

Then edit your Format again, and see if the “Found at cTiVo-10.7.app...“ goes away. I don’t know why it’s picking it up, but that’s not good. 

Oh, and Happy New Year!

**Comment by cgurley** [comment]
![Screen Shot 2020-01-01 at 6 47 20 AM](https://user-images.githubusercontent.com/30550521/71641006-bbf47a00-2c62-11ea-9b0f-64e3246d2e00.png)

I removed cTivo completely and added it back. Path is now correct - but same result when I convert and cut commercials.

Happy New Year to you as well!

**Comment by mackworth** [comment]
I really should have gotten back to you a while ago. My apologizes. I'll close for now, but let me know if it's still ongoing.
