### ISSUE TITLE
Prevent creation of stereo track?

### ISSUE THREAD

**Issue by sfenwick** [mackworth/cTiVo#401]
How do I prevent creation of the stereo track in for the 1080p format? I've tried adding "--noStereo" to the Audio Encoder options (see below) but that fails every time.

Log data:
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.4)
  configuration: --prefix=/opt/local --enable-swscale --enable-avfilter --enable-avresample --enable-libmp3lame --enable-libvorbis --enable-libopus --enable-librsvg --enable-libtheora --enable-libopenjpeg --enable-libmodplug --enable-libvpx --enable-libsoxr --enable-libspeex --enable-libass --enable-libbluray --enable-lzma --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libfribidi --disable-libjack --disable-libopencore-amrnb --disable-libopencore-amrwb --disable-libxcb --disable-libxcb-shm --disable-libxcb-xfixes --disable-indev=jack --enable-opencl --disable-outdev=xv --enable-audiotoolbox --enable-videotoolbox --enable-sdl2 --disable-securetransport --mandir=/opt/local/share/man --enable-shared --enable-pthreads --cc=/usr/bin/clang --arch=x86_64 --enable-x86asm --enable-libx265 --enable-gpl --enable-postproc --enable-libx264 --enable-libxvid --enable-nonfree --enable-libfdk-aac
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Unrecognized option '-noStereo'.
Error splitting the argument list: Option not found

**Comment by mackworth** [comment]
That should work, but I’m traveling, so can’t try this out. A few questions: 

Are you sure you put two dashes?
 Is your Format using the ffmpeg_edl_ac3.sh encoder?
 If so, In Adv Prefs, turn on "Don't delete temp files" and turn logging up to Detail, then run the same show to completion. Now go to the temp directory, and delete the large mpg files, and zip up the rest, including the ffmpeg directory (assuming Default format) and post it here. Also If you could paste a screenshot of the Edit>Format page.

**Comment by mackworth** [comment]
Ps be sure to turn off “don’t Delete” afterwards

**Comment by sfenwick** [comment]
Screenshot of format below.

The download completes but none of the ffmpeg processing occurs, because it doesn't recognize the "--noStereo" flag. I attached the log file so you can see that too.

[Archive.zip](https://github.com/mackworth/cTiVo/files/4008400/Archive.zip)
[com.cTiVo.cTiVo 2019-12-28--20-21-35-154.log](https://github.com/mackworth/cTiVo/files/4008403/com.cTiVo.cTiVo.2019-12-28--20-21-35-154.log)

![noStereo](https://user-images.githubusercontent.com/8009301/71560625-8e6cbe00-2a21-11ea-84d3-a221ba404192.png)

**Comment by mackworth** [comment]
Sorry I can’t test this myself right now, but could you try one dash instead of two on the “-noStereo” option?

**Comment by mackworth** [comment]
I did have the chance to try it, and one dash ("-noStereo) is correct and works fine.
Sorry for the documentation fail (and my own faulty recollection above)!

**Comment by sfenwick** [comment]
Yes! That has worked. D'oh on me for not trying it!

Thanks!

**Comment by mackworth** [comment]
Cool.  Let me know if you have any other issues.
