### ISSUE TITLE
Decode / Decrypt failing

### ISSUE THREAD

**Issue by bryanmcain** [mackworth/cTiVo#403]
All of a sudden in the last few days, my downloads keep failing.  I've just watched it, and the download works fine, but the decryption fails.  I've just double checked the MAC is correct, and I'm not really sure where to go from here.  

This is what I see in the logs that seems to be relevant, but I don't understand it.

2020-01-25 23:32:48:376 -[MTTask failedTaskCompletion]@246>Task decrypt failed
2020-01-25 23:32:48:376 -[MTTask saveLogFileType:fromPath:]@208>errFile for task decrypt: Encryption by QUALCOMM ;)

Thanks

**Comment by mackworth** [comment]
Doesn’t say much, does it? bLet’s try turning up Debug level in Preferences to Detail and then post the log here.

**Comment by mackworth** [comment]
Sorry, forgot to add: and then run another Download before posting the log

**Comment by bryanmcain** [comment]
[com.cTiVo.cTiVo 2020-01-26--04-38-23-842.log](https://github.com/mackworth/cTiVo/files/4113628/com.cTiVo.cTiVo.2020-01-26--04-38-23-842.log)

Here you go.

**Comment by mackworth** [comment]
So that log shows an encoder failure, not a decrypt failure. The handbrake log is clipped, but the last part shows a listing of presets. This suggests to me that  it's not recognizing `bryan's default` as a Handbrake preset.  Although I'm not sure, you could check the spelling, or try a different preset.  If that doesn't work, if you temporarily set "Don't delete temp files", cTivo will leave the whole Handbrake log in the temp directory. (Be sure to turn it off afterwards, or it will eat your hard drive.) After this is fixed, you should turn Detail back to at least Major anyways.

BTW, your original note said the "download works fine, but the decryption fails". As the decryption occurs simultaneously with the download, it's unlikely that the whole download would work if there's a decryption failure. The clip from the log could result if the following download was interrupted (e.g hitting Pause Queue). Decrypt tracking will then log an error.

**Comment by bryanmcain** [comment]
Sorry, I thought that's what I saw when I was watching it download, but I must have misread it.

The weird thing is, I haven't touched ctivo or handbrake in ages - it work working fine as of december.  I can see "bryan's default" from the handbrake gui, but if I try to make a new format inside of cTivo, I no longer see user created presets.  In fact, at the bottom of the preset list after CLI Default it says "Handbrake has Exited." Which seems strange too.

I reran a single show with keep temp files turned on, where can I find the temp directory and the handbrake log?

**Comment by mackworth** [comment]
So it’s in a temp directory, in a complicated, unique folder. If you go to Adv prefs, and click on the “choose a temp directory”, I think it will show you the current one. 

Hmm, maybe that User-defined selection thing is broken with latest Handbrake. (It’s a little delicate). I’ll have to try that out.

**Comment by bryanmcain** [comment]
OK, I found the folder.  I think this is the relevant log.  Let me know if there is a different one I should send.
github won't let me upload the .err file, but I think this is the relevant log.  File name is:
decryptDC's Legends of Tomorrow - S00E03 - Crisis on Infinite Earths-Part Five.err

contents:
Encryption by QUALCOMM ;)

TiVo Header : 
 flags : 29
     origin : US
     format : Program Stream
     source : HDTV
  TiVo unit : Series3
mpeg_offset : 21504
chunks      : 3

read: Undefined error: 0
processing frame: Undefined error: 0
Failed to process file: Undefined error: 0

**Comment by mackworth** [comment]
That’s the decrypt one, which does suggest that it has a problem (unless we have the same stopping the queue). Look for the encrypt...  

BTW, you can upload the err file just by renaming it (e.g .err.txt)

**Comment by bryanmcain** [comment]
The encode error files are all blank.

Also, I tried an ffmpeg encode and it worked fine.  Well, it started to - I don't use ffmepg because I can't throttle it to a single processor the way I can handbrake, so once I saw the encode start successfully I killed it.

**Comment by mackworth** [comment]
Hmm, you can set the -threads parameter on the ffmpeg call, e.g.  -threads 2

Weird; what about in the log file? There should be something in those logs, even if it’s just the initial header.

**Comment by bryanmcain** [comment]
Hm, for some reason I couldn't get that to work (and we've discussed it in the past.  I came away thinking I had to use handbrake, but maybe I should look at it again).

Attached are all the log files from the temp directory.  I removed the binaries.
[templogs.zip](https://github.com/mackworth/cTiVo/files/4114306/templogs.zip)
[com.cTiVo.cTiVo 2020-01-26--04-38-23-842.log](https://github.com/mackworth/cTiVo/files/4114307/com.cTiVo.cTiVo.2020-01-26--04-38-23-842.log)

**Comment by rqchin** [comment]
I'm having almost exactly the same problem but with just one show. It keeps saying "task decrypt failed"

[com.cTiVo.cTiVo 2020-02-04--07-05-37-155.log](https://github.com/mackworth/cTiVo/files/4156756/com.cTiVo.cTiVo.2020-02-04--07-05-37-155.log)


2020-02-04 06:41:33:372 -[MTDownload launchDownload]@1677>Starting download (type 0) for Supergirl: Crisis on Earth-X, Part 1-Rick Roamio(d5460); Format: Default;  Mark commercials; Keep after iTunes; No Memory Buffer;tivodecode-ng; Program Stream
2020-02-04 06:41:33:443 -[MTDownload launchDownload]@1895>Starting URL http://dvr-162b.local.:80/download/Supergirl.TiVo?Container=%2FNowPlaying&id=311097 for show Supergirl: Crisis on Earth-X, Part 1-Rick Roamio(d5460) in 0.0 seconds
2020-02-04 06:41:34:443 -[MTTask failedTaskCompletion]@246>Task decrypt failed
2020-02-04 06:41:34:443 -[MTTask saveLogFileType:fromPath:]@208>errFile for task decrypt: Encryption by QUALCOMM ;)

TiVo Header : 
 flags : 29
     origin : US
     format : Program Stream
     source : HDTV
  TiVo unit : Series3
mpeg_offset : 24576
chunks      : 3

Invalid MAK -- aborting
processing frame: Undefined error: 0
Failed to process file: Undefined error: 0
2020-02-04 06:41:34:531 -[MTTiVoManager notifyForName:withTitle:subTitle:isSticky:]@1742>Notify: Supergirl: Crisis on Earth-X, Part 1: TiVo show failed
Retrying
2020-02-04 06:41:35:399 -[MTDownload launchDownload]@1677>Starting download (type 0) for Supergirl: Crisis on Earth-X, Part 1-Rick Roamio(d5460); Format: Default;  Mark commercials; Keep after iTunes; No Memory Buffer;tivodecode-ng; Program Stream
2020-02-04 06:41:35:405 -[MTDownload launchDownload]@1895>Starting URL http://dvr-162b.local.:80/download/Supergirl.TiVo?Container=%2FNowPlaying&id=311097 for show Supergirl: Crisis on Earth-X, Part 1-Rick Roamio(d5460) in 59.1 seconds
2020-02-04 06:42:35:774 -[MTTask failedTaskCompletion]@246>Task decrypt failed
2020-02-04 06:42:35:861 -[MTTiVoManager notifyForName:withTitle:subTitle:isSticky:]@1742>Notify: Supergirl: Crisis on Earth-X, Part 1: TiVo show failed
Retrying
2020-02-04 06:42:37:888 -[MTDownload launchDownload]@1677>Starting download (type 0) for Supergirl: Crisis on Earth-X, Part 1-Rick Roamio(d5460); Format: Default;  Mark commercials; Keep after iTunes; No Memory Buffer;tivodecode-ng; Program Stream
2020-02-04 06:42:37:894 -[MTDownload launchDownload]@1895>Starting URL http://dvr-162b.local.:80/download/Supergirl.TiVo?Container=%2FNowPlaying&id=311097 for show Supergirl: Crisis on Earth-X, Part 1-Rick Roamio(d5460) in 58.0 seconds
2020-02-04 06:43:37:157 -[MTTask failedTaskCompletion]@246>Task decrypt failed
2020-02-04 06:43:37:157 -[MTTask saveLogFileType:fromPath:]@208>errFile for task decrypt: Encryption by QUALCOMM ;)

**Comment by mrfusiontm** [comment]
I'm having the same problem on almost every show I try to download from the CW.    I've pretty much given up hope getting anything from that channel.  Every other channel still seems to work just fine.

**Comment by mackworth** [comment]
Can you post one of the files that fails somewhere i can retrieve it, and send me your MAK to mackworth at AOL's mail service   (<mylastname>@aol.com)? 

Oh, to get the file, easiest is use TiVo's web UI:
https://xxx.xxx.xxx.xxx/nowplaying/index.html

**Comment by 1742** [comment]
Cancel subscription，thanks.



At 2020-02-05 21:19:58, "mrfusiontm" <notifications@github.com> wrote:

I'm having the same problem on almost every show I try to download from the CW. I've pretty much given up hope getting anything from that channel. Every other channel still seems to work just fine.

**Comment by 1742** [comment]
Cancel subscription，thanks.



At 2020-02-05 23:12:06, "Hugh Mackworth" <notifications@github.com> wrote:

Can you post one of the files that fails somewhere i can retrieve it, and send me your MAK to mackworth at AOL's mail service (@aol.com)?

Oh, to get the file, easiest is use TiVo's web UI:
https://xxx.xxx.xxx.xxx/nowplaying/index.html

**Comment by mackworth** [comment]
Unfortunately, @1742, I'm just a user of Github's service like you, so I have no ability to unsubscribe you. So sorry to annoy you. The way Github's system works, every time someone pastes a log from cTiVo with the text `@1742` in it, you'll be notified.

 I believe you need to go to the main page: [](https://github.com/mackworth/cTiVo/) and click on the `Watch` button (with the eye icon), and specify `Ignoring`. Then you shouldn't get any more messages from this repository.

**Comment by bryanmcain** [comment]
Sorry I haven't been back to this in a while - you want me to post the .tivo file from one of the ones that fails?

**Comment by mackworth** [comment]
Exactly, and I then need the MAK to run through the decryption and see where it fails and if I can add a patch to tivodecode to let it continue.

**Comment by mackworth** [comment]
Closed due to lack of response, but happy to look at it again. There seems to be a general issue of increasing corruption in the TiVo system, but if I can see a way to modify the software to skip that section, that'd be great.
