### ISSUE TITLE
Temp directory not editable

### ISSUE THREAD

**Issue by mtdiamond** [mackworth/cTiVo#404]
3.4.1 (Mac) , fresh install.

1. ~~Temp files are not being deleted, despite Advanced setting not saying to keep them. (See screenshot) This quickly fills up my boot drive with buffer files, of type .mpg and .tivo.~~ (see comment for likely explanation)

2. Temp directory is not editable through the UI. When I click on the field it pulls up the current temp directory in a new window, but this seems to be informational. It's not a prompt that lets me select a different directory.

Hope this helps.

![Screen Shot 2020-01-26 at 11 33 31 PM](https://user-images.githubusercontent.com/9596573/73150568-f5b77580-4094-11ea-985d-557642397a62.png)

**Comment by mtdiamond** [comment]
>     1. Temp files are not being deleted, despite Advanced setting not saying to keep them. (See screenshot) This quickly fills up my boot drive with buffer files, of type .mpg and .tivo.

Sorry- this part of my report may be wrong. It may be a consequence of the skipmode logic. Until that logic is complete the temp files can't be deleted. I have changed my prefs to allow the skipmode to run more often, so we'll see. But I'm optimistic.

I have changed the issue description accordingly.

**Comment by mackworth** [comment]
Just checking; are you running cTV or cTiVo?  (The former cannot change its temp directory, due to sandboxing issues.)

And yes, it will keep the temp files around until it’s fully finished processing, as it may have to do a comskip pass if Skipmode never arrives.

**Comment by mtdiamond** [comment]
Of course you are right - was running cTV, not cTivo. I didn't realize there were two different apps.
I could wish that the app itself contained a notice, particularly when trying a sandboxed action, but if I was the only one confused by it then nothing more need be done. :-)

Thanks for answering the question; issue is resolved.

**Comment by mackworth** [comment]
Agreed it's confusing, and I spent quite a while trying to get around the restriction. That's the only technical difference between the apps (and then the name/logo).

FYI, this issue is that while the main app would be allowed to ask for access to a different temp directory, the "helper" apps cannot be granted the same access, at least for dynamic access, as opposed to static access granted when the app is built.  

Glad it's resolved!
