### ISSUE TITLE
Local LAN Tivos not being found; why not allow a manual [+] config?

### ISSUE THREAD

**Issue by forrie** [mackworth/cTiVo#406]
I have a simple LAN here, but cTivo doesn't find my Bolt.  I note that I cannot [+] add a manual ip to the configuration, why not?  I think this would help solve the problem.   Can we get that?

**Comment by mackworth** [comment]
Which version of cTiVo do you have?

**Comment by forrie** [comment]
Apologies, I should have put that in the request.

I have Version 3.4.1 (1108)

**Comment by mackworth** [comment]
And what happens when you hit + in Edit TiVos?

**Comment by rqchin** [comment]
I just had a possibly related issue. I rebooted my Mac and when I opened cTivo, it couldn't find any Tivos even though minutes before it was downloading shows. I could add the device manually by IP address but that meant it thought this Tivo was a completely different device. I ultimately renamed my Tivo so that it matched the previous name (not sure how or when the name got changed) and cTivo immediately found it. No matter what the name, it was always visible in the Bonjour Discovery browser from http://www.tildesoft.com. Running 3.4.1 also

**Comment by forrie** [comment]
I see the issue here, which is in the UI of the Preferences panel, under TiVos.   The top part of the pane reads "Remote (Manual) TiVos", while the bottom says "Local Network TiVos".   This is confusing and where I didn't see an option to add [ + ] on the Local Network TiVos, and the network scanning (still) isn't working, it appeared to be a problem.   By "Remote", that generally means (in context) a TiVo that is not on your LAN.  

I was able to add my TiVo manually in the Remote pane, using my media key.

Anyhow, I'd think it's confusing :)

**Comment by mackworth** [comment]
So, IF the bonjour discovery were working, then “Local” is correct as your TiVo would have shown up, and “Remote(Manual)” is correct (if ”mispunctuated”) as you can do both of those things. 

But I agree that if it’s nit working, then it’s definitely confusing. I’ll reword slightly. 

@rqchin So If I understand correctly. the TiVo name was showing as unchanged, but you changed it?  And it showed up?  This could be a good clue. Can you go into more detail on what were the exact steps?

**Comment by tdlivings** [comment]
I had the same problem. CTV found the TiVo but CTiVo did not. After I added it to CTV and then opened CTiVo app there were on both sides. Odd....

**Comment by mackworth** [comment]
I haven’t been able to spend any time here recently; my apologies.  This is a particularly hard issue to debug remotely.  I did find this advice re Bonjour and Catalina to reset the IP address table:

In Terminal:

> sudo killall -HUP mDNSResponder
> sudo arp -a -d

You’ll need to provide the admin password after the first line.

**Comment by tdlivings** [comment]
Don’t worry. I fixed it
