### ISSUE TITLE
Another download / convert failure

### ISSUE THREAD

**Issue by NoahBuddy** [mackworth/cTiVo#409]
Greetings!  I'm having problems downloading / converting files.  
I've enclosed a log.  
Please advise.
my thanks.
[com.cTiVo.cTiVo 2020-02-29--23-54-28-213.log](https://github.com/mackworth/cTiVo/files/4289990/com.cTiVo.cTiVo.2020-02-29--23-54-28-213.log)

**Comment by NoahBuddy** [comment]
[com.cTiVo.cTiVo 2020-02-29--23-54-28-213.log](https://github.com/mackworth/cTiVo/files/4289983/com.cTiVo.cTiVo.2020-02-29--23-54-28-213.log)

**Comment by mackworth** [comment]
So you're getting a strange message:
`/Volumes/Tivo World 2019/Tivo 2019/The Late Show With Stephen Colbert 2020-02-25 Chris Christie; Nathaniel Rateliff S05E92.mp4: Device not configured`

Is this an external volume called "Tivo World 2019"? Can you see that folder in Finder?  If so, go into Terminal and try `ls  /Volumes/Tivo World 2019/Tivo 2019/`  Then go into Disk Utility and do a Verify on the drive. Maybe try rebooting as well.

**Comment by NoahBuddy** [comment]
Hmmmmm...   it's definitely there in the Finder, but when I go to Terminal, i get

**Comment by mackworth** [comment]
Oops; my fault.  Terminal command needs to be `ls '/Volumes/Tivo World 2019/Tivo 2019/'` Or else the spaces cause problems.

**Comment by NoahBuddy** [comment]
I not only rebooted, but I also ran Drive Genius on both my primary OS HD and my "Tivo World 2019" HD with a secondary OS HD.  I rebuilt both HDs, rebooted with my primary OS HD.   When I ran Terminal, I once again got a "No such file or directory" message.   I ran Disc Utility, couldn't find a Verify (Mac OS 10.12), but I did run Repair.   Still no luck with Terminal.

**Comment by NoahBuddy** [comment]
still no luck with the "/Volumes/Tivo World 2019/Tivo 2019/" Terminal command

**Comment by mackworth** [comment]
Did you add the single-quotes as indicated above?  `ls '/Volumes/Tivo World 2019/Tivo 2019/'`  It will definitely fail otherwise

**Comment by NoahBuddy** [comment]
AH..... /Volumes/Tivo World 2019/Tivo 2019/: is a directory

**Comment by NoahBuddy** [comment]
I recently switched from a 2017 version of software to 3.4.1.   The old version kept rejecting something like 2 out of 10 downloads.    The new version seems to reject 9 out of 10 or 10 out of 10 downloads.      Is there anything else I should do to confirm set up before trying out?

**Comment by NoahBuddy** [comment]
[com.cTiVo.cTiVo 2020-03-05--03-00-05-779.log](https://github.com/mackworth/cTiVo/files/4294362/com.cTiVo.cTiVo.2020-03-05--03-00-05-779.log)
OK, it's definitely working better now.   I was able to download 3 out of 5 clips.  I'm not sure why I'm having problems with the other two, but I've enclosed the latest logs.

**Comment by NoahBuddy** [comment]
On an unrelated note, my programs no longer are organized in appropriately named folders. Apparently, it didn't save the old preference.   What setting should I change to make that work again?

**Comment by mackworth** [comment]
If you have a file that worked in 2017, and fails in current one, that would be very useful for me to submit to the ffmpeg group.

Have you tried Handbrake instead?  If there’s one Format that works better than another, that would be useful also.

**Comment by NoahBuddy** [comment]
From what I can see, I don't think there were any files that worked in 2017,  but not in the latst version.   I just see a handful of files, mostly CW programs, that I was not able to download/encode with cTivo.   I'm not sure how to download without the encoding process.  Can I do that with cTivo or is there another software I can use for that?

**Comment by NoahBuddy** [comment]
So far, it looks like it's working much better.   There's still a few problem files that refuse to be download/encoded with cTivo.

**Comment by mackworth** [comment]
Good to hear, and sorry for extended delay in responding.  Let me know if I can help otherwise
