### ISSUE TITLE
(null): Internal Logic Error! 

### ISSUE THREAD

**Issue by tdlivings** [mackworth/cTiVo#410]
I was just wondering if there is any hope of recovering from this error. Thanks in advance.

[com.cTiVo.cTiVo 2020-03-05--05-36-42-741.log](https://github.com/mackworth/cTiVo/files/4291168/com.cTiVo.cTiVo.2020-03-05--05-36-42-741.log)

**Comment by mackworth** [comment]
So, you should never get this issue (as it suggests.)  Was this due to your bad hard disk?  Has it recurred since then?

**Comment by tdlivings** [comment]
No, just happened from time to time. Free TV OTA, we get what we pay for.
