### ISSUE TITLE
I had a intermittent power issue that caused a ssd failure

### ISSUE THREAD

**Issue by tdlivings** [mackworth/cTiVo#412]
had to rebuild the SSD and re-install everything and now the CTIVO will not discover the TiVo. Do you have any suggestions on a resolution?

**Comment by mackworth** [comment]
I'm sorry for the extended delay here. I've been working on some other projects, and I missed this one completely until going back through the issues now.  From your later comments, I take it this got resolved, so I'll close for now. Let me know if that's not true.
