### ISSUE TITLE
Reconfiguring Network w/ New Modem

### ISSUE THREAD

**Issue by NoahBuddy** [mackworth/cTiVo#415]
I recently had to buy a new modem after my old Netgear cable modem stopping working last night.  Apparently, this Motorola MG7550 cable modem I purchased doesn't offer a Bonjour option, which makes the cTivo setup a bit more challenging.  I don't remember there being so many steps the last time I did this.

Anyone know any easy way to install Bonjour with this Motorola modem?

The manual option feels a bit intimidating for .....  starting with ...
"Configure your DHCP to reserve a fixed address for your TiVo."
System Preferences> Network > Advanced > TCIP/IP 
Would this be "Using DHCP with Manual address?"

If there's a way to provide more screen captures, that would be awesome.

**Comment by NoahBuddy** [comment]
As it appears there's no easy way to use a Bonjour option on this Motorola modem, i'll probably return it for another Netgear modem.

**Comment by mackworth** [comment]
I still think there's an issue of Bonjour discovery in Catalina. I haven't been able to reproduce the problem myself.  

It's not so bad to configure the manual option. You should be able to also use the TiVo's own name, not a fixed IP address. 

If you like, I can walk you through a few steps.  Start by downloading the browser here:
https://apps.apple.com/us/app/discovery-dns-sd-browser/id1381004916?mt=12

Let me know if your Tivo appears in the list.

**Comment by NoahBuddy** [comment]
I'm running Mac OS 10.11, so I can't use that application which requires 10.12.

**Comment by mackworth** [comment]
ah.  Try [Bonjour Browser](http://www.tildesoft.com/files/BonjourBrowser.dmg) (its predecessor) instead.

**Comment by mackworth** [comment]
What is your network configuration? Specifically, how does data get from your Mac to your TiVo? (Wifi to a router to Ethernet, or both on Wifi, or ...)

**Comment by NoahBuddy** [comment]
Xfinity cable modem> LInksys router > ethernet cable

**Comment by NoahBuddy** [comment]
Mac (OS 10.11) w/ cTivo, Motorola router adm + Bonjour Browser all open ..  and awaiting advice on what to do next.

**Comment by mackworth** [comment]
So, the Mac and the Tivo are both connected to Ethernet, and then both connected directly to the same router?

Does BB show any Tivos in the list?

**Comment by mackworth** [comment]
In fact, if you want to paste a screenshot from BB that would be good.

**Comment by NoahBuddy** [comment]
![Screen Shot 2020-05-04 at 2 27 42 PM](https://user-images.githubusercontent.com/15773695/81015611-d6f31880-8e13-11ea-9ed9-ccf9e2055afa.png)

**Comment by NoahBuddy** [comment]
I typed IP address  + media key to Tivo default #1, renamed as Tivo main

**Comment by NoahBuddy** [comment]
not sure what BB stands for, but i'm hoping this is what you need..

**Comment by mackworth** [comment]
Sorry, I meant from Bonjour Browser.

But your cTiVo screenshot (I deleted as it has your MAK in it) shows three TiVos discovered on the local network, with one disabled. Is that right?

**Comment by NoahBuddy** [comment]
![Screen Shot 2020-05-04 at 2 35 02 PM](https://user-images.githubusercontent.com/15773695/81016014-8a5c0d00-8e14-11ea-9621-84de7bb2062b.png)

**Comment by NoahBuddy** [comment]
I have a Tivo Roamio and Tivo mini

**Comment by NoahBuddy** [comment]
Not sure why it thinks it may be 3

**Comment by mackworth** [comment]
So, the Mac and the Roamio are both connected to Ethernet, and then both connected directly to the same router?  How is the Epson connected?  

Do you have any old Apple devices on the network?  (Airports, or Macs, or AppleTVs, etc)?

And, let's switch to mail instead.  Email me at mackworth at aol dot com

**Comment by NoahBuddy** [comment]
it doesn't look like the Bonjour Browser shows either of the two Tivos
I just sent an email

**Comment by mackworth** [comment]
Not seeing the email? Double-check spelling?

**Comment by NoahBuddy** [comment]
So, the Mac and the Roamio are both connected to Ethernet, and then both connected directly to the same router? 

YES

How is the Epson connected?


WIFI
Do you have any old Apple devices on the network? (Airports, or Macs, or AppleTVs, etc)?

There’s 3 Macs (2 on WiFI, 1 with ethernet)
2 iPhones  somettimes on Wifi

**Comment by NoahBuddy** [comment]
No email yet?  Hmmmm..

**Comment by NoahBuddy** [comment]
hopefullly email came through

**Comment by NoahBuddy** [comment]
Thank you Hugh!

**Comment by mackworth** [comment]
Turned out to be the router was putting Wifi on one network (192.168.1.xx) and Ethernet on another (192.168.0.xx) . Thus they could talk to each other, but bonjour broadcasts weren't getting through.
