### ISSUE TITLE
Corrupt stream?

### ISSUE THREAD

**Issue by WedgieTwo** [mackworth/cTiVo#416]
Good morning!  I have been using CTiVo for years, and everything was perfect until recently.  When streaming to the iMac, the video is garbled or has streaking lines across it.  I don't recall ever changing a setting or have had the need to.  Saw a couple other issues relating to Catalina, so I don't know if that's it.  All previous videos work fine.  Any help you can provide is welcome.  Thank you!

**Comment by mackworth** [comment]
Sorry for delay; didn't see this one.  So is this a single video that has problems? Or all on one channel or all of them?  If it's a single episode or channel, that unfortunately happens sometimes. The encrypting process on the TiVo brings out problems in the digital stream that may not be visible on your TV. If it's all of them, please go to Help>Show Logs in Finder and post the log file on GitHub

**Comment by WedgieTwo** [comment]
Hi there.  I could have sworn I responded to this.  I got the logs and everything.  Anyway, after further research, it is everything from one of our two TiVo boxes.  I'll post the log in the next comment.

**Comment by WedgieTwo** [comment]
[com.cTiVo.cTiVo 2020-05-31--13-06-58-306.log](https://github.com/mackworth/cTiVo/files/4770550/com.cTiVo.cTiVo.2020-05-31--13-06-58-306.log)

**Comment by mackworth** [comment]
So, that doesn't show much. It shows two files launching, and strangely no results of those launches, neither success nor failure.  I should note that DVD as a Format is problematic; I haven't tried that in a long time, and it's definitely not a good choice for viewing on the Mac.

So, change to Default, and set Debug Level to Major, then run it again and see what it says and whether the quality improves.

**Comment by WedgieTwo** [comment]
Good morning.  That format change may have done it.  I don't recall ever changing an internal setting, but I changed the format to "default" and re-downloaded the specific shows that were not coming through clearly.  They seem to be cleared up now!

Maybe an upgrade altered something?  Who knows, but I definitely appreciate your help!  Thank you!

**Comment by mackworth** [comment]
It’s also on the upper right corner of the main window, so it may have been hit accidentally. Glad it’s working for you!
