### ISSUE TITLE
Enhancement request: Move percentage-complete information from tooltip status to the forefront

### ISSUE THREAD

**Issue by wjmt3** [mackworth/cTiVo#421]
I like to see the percentage complete. It would be nice to see it right alongside all the other information, without having to hover over the progress bar. 😃

**Comment by mackworth** [comment]
Forgot to respond to this one.  Not quite sure what you meant. Do you mean yet another column? It already shows a rough estimate of total time to complete?

**Comment by wjmt3** [comment]
Hi Hugh!

Thanks for the reply. I didn't want to bug you. 😄 

No, it definitely doesn't need more columns. I had something a little more elegant in mind.

As it currently operates, the DL Status column merely says "Downloading", "Encoding", etc.

I would update it so that it says "Downloading: 1%", "Encoding: 15%", etc.

This would in fact eliminate the need for the tooltip (popup) entirely, because the percentage is the only bit of information not already conveyed elsewhere in the interface, front and center.

You are right that it shows a total time estimate, but I think the percentage is still a worthwhile statistic to display, because the time estimate can change based on processor load, while the percentage only moves in one direction.

I hope this makes more sense than my original phrasing! Happy Thanksgiving, and stay safe!

-Will

**Comment by mackworth** [comment]
So, just to be clear, that percentage complete is the same info as the shaded bar?  

Although redundant, as an experiment I've implemented the % number. and will try it out for a while.  

BTW, I note the tooltip has different info than the info bar at the top of the table when you have more than one unfinished show in the queue.

Thanks for the suggestion!

**Comment by wjmt3** [comment]
Just wanted to let you know that this is exactly what I had envisioned. Thank you!
