### ISSUE TITLE
Tivo Bolt+ Crashes when program data is loading..

### ISSUE THREAD

**Issue by BobSnodgrass** [mackworth/cTiVo#422]
I saw the other string on crashes when downloading a show but in this case my TiVo Bolt+ with 21.9.7.v8-USC-11-849 crashes while the show information is being populated!  I'm brand new to cTiVo and has just downloaded the latest 3.4.1 version.  It seems to get partway through and I do see image thumbnails on a few shows.

Anything I can do to help track down the issue?  It's 100% reproducible every time.

**Comment by mackworth** [comment]
Just to confirm, it's the TiVo crashing, not cTiVo? 

Starting point would be to get a detailed log of what cTiVo is seeing.  To do that, start cTiVo while holding down both the Control and Option keys. (This sets to Verbose logging from the get-go) Then use Help>Show Logs in Finder , and right-click in the Finder to Compress the logs and post the resulting zip file here (don't respond to the email you got, as it strips attachments).   

We'll see what we can find...

**Comment by mackworth** [comment]
Just going back through and cleaning up old issues.  Any news here?
