### ISSUE TITLE
Tivo not showing up - duplicate IP address

### ISSUE THREAD

**Issue by rqchin** [mackworth/cTiVo#423]
This is a solved problem for me but I wanted to document it here in case it helps you with troubleshooting for anyone else.

My Mac running Mojave 10.14.6 got a security update the other day and it required a restart. After the restart, cTivo couldn't locate my Tivo on the network any. (It came up with the "Searching for Tivo for an unusually  long time" message.) Nothing had changed elsewhere on the network, so I wasn't sure why this happened.

I used the Discovery browser to see if it could see the Tivo and it could. Then I logged into my router and looked at the Access Control settings to see a list of devices it was seeing. (Access Control is off but it still shows a detailed list of devices.) There I saw two Tivos with the same MAC address and two different (wired) IP addresses. (For example, 192.168.0.134 and 192.168.0.135) Going to the actual Tivo, I saw the actual IP address was 192.168.0.135. (Getting an IP address via DHCP.)

I decided to restart the Tivo (a Roamio Plus) via the menus and when I did, the ghost IP address disappeared in the Access Control list in the router and cTivo found my Tivo again.

I doubt this is something you could easily detect in cTivo, so I wanted you to know this is a possible situation in case anyone else experiences it. I hate to suggest the "Did you try restarting it?" step of troubleshooting, but in this case, it resolved the problem.

No need to keep this issue open unless there is more info I can provide for you.

**Comment by mackworth** [comment]
This was helpful, and I think I've found and fixed an issue.
