### ISSUE TITLE
Format Description Editing Anomoly

### ISSUE THREAD

**Issue by tannebil** [mackworth/cTiVo#424]
The Description field has a grey background as opposed to a white background on other editable fields so it's not clear it can be edited.

Go into an editable Format, click in the Description, make a change. The "Save" button does not highlight. Click Done. The Leave Window\Continue Editing\Save dialog appears.

Go into an editable Format and change a different field. The Save button highlights. Make a change in the Description field. Save. Click Done. The Leave Window\Continue Editing\Save dialog appears

**Comment by mackworth** [comment]
Sorry, Bill; in going back through the issues, I realized I never saw this one.  Can confirm; will be fixed in 3.4.2 (beta2 or release).  (FYI, if you click away from the description to another field, it will update save button.)
