### ISSUE TITLE
My show is not copy protected. The Tivo will only download the commercials and skips every minute of the actual show. What happened and how can I fix it?

### ISSUE THREAD

**Issue by ringo175** [mackworth/cTiVo#426]

**Comment by mackworth** [comment]
Fascinating. Were you using auto SkipMode or general comskip?  Is it just one show?  If so, we could diagnose what’s causing it, or you could just turn off commercializing. If not (or you want to diagnose), can you go to Advanced Preferences, turn General Debug level to Major, Download to Detail, and Commercial to verbose, then run the show again? Then go to Help>show logs in Finder, and find last log. Then right-click Compress log and post the zip file here (NOT responding as an email attachment)

**Comment by ringo175** [comment]
OK, sorry it took so long here, I was put of town and I am not too quick with all of this. Thanks for your response.
So, here is what I did:
Checking the settings, I was on Skipmode for these first attempts. So, I went with your suggestions, changing the preferences. But... I was unable to find a tab in the advanced preferences for Commercial, so I did not do that step. The results were the same, only downloading the commercials, not the actual show. I tried one more time after that, but this time I changed the setting to Comskip mode. Same result.
I am going to try one more time with another tweak. I will uncheck all boxes in the "Captions and Commercials" area of the settings. I will let you know what happens with that one.

**Comment by ringo175** [comment]
I am trying to add the compressed lob here, but the site is telling me it can't process the file

**Comment by mackworth** [comment]
Sorry, you are correct; there is no Commercial preference; the Download covers that.  (Typed the comment from memory)

Is the file extension .zip?  I just tried dragging/dropping one, and it worked fine?

**Comment by ringo175** [comment]
[com.cTiVo.cTiVo 2020-09-25--05-56-51-638.log.zip](https://github.com/mackworth/cTiVo/files/5315316/com.cTiVo.cTiVo.2020-09-25--05-56-51-638.log.zip)

**Comment by ringo175** [comment]
OK I tried again and got the zip file to post.
I also tried the video download again, as stated before with all boxes unchecked in the "captions and commercials" section. This time, I actually got the entire video, start to finish.
Thank you again for looking into this with me. Hopefully that data will help with your efforts.

**Comment by mackworth** [comment]
Got the zip, but that particular log file is from 9/25, and doesn’t show a download. Is there another in the log directory?

**Comment by ringo175** [comment]
[com.cTiVo.cTiVo 2020-09-29--06-00-05-471.log.zip](https://github.com/mackworth/cTiVo/files/5315726/com.cTiVo.cTiVo.2020-09-29--06-00-05-471.log.zip)
I think this might be the one. Sorry, I am not really a power user (Probably obvious at this point). I normally know just enough to get through the day, and sometimes get myself into tech trouble. But I think I got the right one this time.
Thanks again, also for your patience.

**Comment by mackworth** [comment]
Sorry for delay; I was finishing up the latest release.  that log does seem to cover the period, but the debug level seems to be at a normal level.  Well, if it happens again, feel free to let me know!
