### ISSUE TITLE
Plex Skip Feature?

### ISSUE THREAD

**Issue by shawnp0wers** [mackworth/cTiVo#427]
If I move the downloaded and encoded videos over to plex, they're recognized, and the chapters for commercials are available. I'm curious, however, if it's possible to "do whatever plex DVR does" to video files so that there's a handy "skip" button when a commercial happens. instead of needing to pull up chapters to switch. It's a relatively new feature in plex, but is really handy.

I realize you might not be a plex person, but since one of your naming schemes is based on Plex, I figured it wouldn't hurt to ask. 👍 

(BTW: Awesome program, it makes my Roamio useful again! Thank you!!!)

**Comment by mackworth** [comment]
That'd be good. I've asked them on their forum for more technical information on how to integrate with that. Not trivial as they seem to store the commercial info in their XML file separate from the MP4 file (where the chapter info is stored). We'll see if they respond.

**Comment by mackworth** [comment]
They've confirmed that they only read their own XML file and there's no way to get an EDL into it.  So, not much I can do until they provide a mechanism for that.  The alternative path is to use their comskip instead of cTiVos.  If I hear anything else, I'll reopen this request.
