### ISSUE TITLE
low quality video with hevc

### ISSUE THREAD

**Issue by shersoni610** [mackworth/cTiVo#429]
Hello,

I have been experimenting with various bitrate with hevc_videotoolbox. Although
FPS is impressive the video quality is almost garbage. How should I get a good
quality video which is as good as libx265?

Thanks

**Comment by mackworth** [comment]
Let me connect to @tannebil who's done a lot of work on this issue.

**Comment by tannebil** [comment]
My experience is that high quality, low bit rate encoding is impossible to achieve with the Apple hardware encoder. Getting quality similar to software encoders requires at least a 30% higher bit rate. The only time I use HW encoding is when the source is a high bit rate MPEG2 and the target is high bit rate H.264/5. 

I never found any settings tweak that made a difference. Just kick up the bit rate to 1300+ and take the hit.

I gave up on HW encoding and switched back to “Default”.  However, Comcast has switched all my channels to MPEG4 earlier this year so I don’t even bother to transcode shows these days as as smaller size isn’t a priority for me.

The only time HW makes much sense might be if you are running cTiVo on a low-end MacBook Pro and are dealing with MPEG2 shows. A 30% larger show in 25% of the time is an attractive trade.

**Comment by mackworth** [comment]
for more details, you can see issue #343 .  Let me know if I can do anything else for you.

**Comment by mackworth** [comment]
FYI, it looks like Handbrake is now doing a decent job on this.  Here's a couple of Formats to Import and try:  
[HB HW Formats.plist.zip](https://github.com/mackworth/cTiVo/files/10960944/HB.HW.Formats.plist.zip)
