### ISSUE TITLE
HB Custom presets not showing in cTiVo

### ISSUE THREAD

**Issue by tdlivings** [mackworth/cTiVo#430]
I was looking at a similar issue someone else had in this area. 1.3.3 moved the user presets and I was wondering if you could point me in the right direction as to the preset location on the MAC. I have looked several times and can not find them. If I don't use the option align A/V the cTiVo generated HB file has no sound occasionally.

**Comment by mackworth** [comment]
3.4.2 beta now ships with 1.3.3 (as of a couple minutes ago), so give that a try.

The file itself is here:`~/Library/Application\ Support/HandBrake/UserPresets.json `

**Comment by mackworth** [comment]
Let me know if there's still an issue here.
