### ISSUE TITLE
3.4.2 Beta Release

### ISSUE THREAD

**Issue by mackworth** [mackworth/cTiVo#431]
If you have any issues or questions about the 3.4.2 Beta Release, let me know here.

**Comment by tannebil** [comment]
I upgraded to 3.4.2 beta (1122) and am getting a keychain password prompt. Neither my macOS password nor my iCloud password will unlock it and it’s not in Keychain Access

![Screen Shot 2020-11-03 at 6 41 33 PM](https://user-images.githubusercontent.com/9303332/98063876-e0caf800-1e05-11eb-95f2-e13a29b9024d.png)

**Comment by mackworth** [comment]
Interesting. Anyone else have this?  Try just hitting OK (no password).

**Comment by mackworth** [comment]
Oh, BTW, 1124 may have an effect here.

**Comment by tannebil** [comment]
I did to clear it but it came back some random time later. I don't think out was correlated with a reboot or a restart of cTiVo

**Comment by tannebil** [comment]
I have a heck of a time finding releases in GitHub. Where is 1124? I go to https://github.com/mackworth/cTiVo/releases/ and I see the source code but not the binaries. Are they in a different place?

![Screen Shot 2020-11-03 at 7 58 17 PM](https://user-images.githubusercontent.com/9303332/98067679-f8f34500-1e0e-11eb-9f6c-509682f51238.png)

**Comment by mackworth** [comment]
That is weird.  It showed the binary as damaged, so I re-uploaded it.

**Comment by mackworth** [comment]
Did you find it?

**Comment by tannebil** [comment]
Yes. It started up without the Keychain message but I want to give it a few days as it’s been a random appearance (which seems pretty weird)

**Comment by mackworth** [comment]
I take it that it's working ok now?
