### ISSUE TITLE
not finding any tivos

### ISSUE THREAD

**Issue by FloridaMatt** [mackworth/cTiVo#432]
I have 2 Roamios and 2 Premieres, all on local network 10.52.21.*.  cTivo finds none of them when scanning and none when I enter them manually.  Bonjour is presumed working as my macs use it to find TimeMachine nas shares.  A windows pc running pytivo finds them with no issues. http connections from a browser successfully access the "congratulations" page.

Please advise what diagnostics to gather to document this problem.

**Comment by mackworth** [comment]
So if you hold down Cmd-Option as you launch cTiVo, it will turn on Verbose mode. Then a few seconds after it launches, use Help>Show logs in Finder, then (right-click) compress the most recent log in the cTiVo directory, and post the result.

Also which version of cTiVo are you using? and which version macOS

**Comment by FloridaMatt** [comment]
Macos 10.15.7.  cTivo Version 3.4.1 (1108).
[com.cTiVo.cTiVo 2020-10-23--18-50-15-512.log.zip](https://github.com/mackworth/cTiVo/files/5431509/com.cTiVo.cTiVo.2020-10-23--18-50-15-512.log.zip)

**Comment by FloridaMatt** [comment]
Ok, looking at the log, and seeing the disabled message, I realized I hadn't enabled the tivo I added.  When I enabled it, all 4 showed up in local tivios.

So I guess from my perspective it's fixed.  You can close this unless you want me to gather any additional data.

**Comment by mackworth** [comment]
Actually I gave you the wrong keystrokes. Try Ctrl-Option instead.

**Comment by mackworth** [comment]
And actually, yes, if you don't mind. Delete the Manual one entirely, and do the log thing.

**Comment by FloridaMatt** [comment]
[com.cTiVo.cTiVo 2020-10-23--18-50-15-512.log.zip](https://github.com/mackworth/cTiVo/files/5431546/com.cTiVo.cTiVo.2020-10-23--18-50-15-512.log.zip)
And with the manual one deleted, cTivo once again can't find any tivo.

**Comment by FloridaMatt** [comment]
it popped up the message about not finding any tivos but when I looked, they were there this time but not enabled.  perhaps I should delete everything and try this from the top?

**Comment by mackworth** [comment]
Actually, that would be good (mostly deleting the preferences file com.ctivo.ctivo in ~/Library/Preferences and then logging out and back in to defeat the caching) , but can you try it with [the beta version](https://github.com/mackworth/cTiVo/releases/download/3.4.2beta/cTiVo.app.zip)? I think I fixed this, so that would be a great test.

**Comment by FloridaMatt** [comment]
I'll clear it all out and try the beta.  just a few minutes.  Should I start with verbose or not?

**Comment by mackworth** [comment]
Sure.  If it doesn’t work, that log would be useful.

**Comment by FloridaMatt** [comment]
It worked, in the sense that it found them.  But it still displayed the message after searching for a while, and when I looked at the list, they were not enabled.  I'd think it should bring up the Edit Tivos box upon finding the first one, and add to it for additional ones found over the next nn seconds.  Just my opinion.

**Comment by FloridaMatt** [comment]
[com.cTiVo.cTiVo 2020-10-23--20-18-21-823.log.zip](https://github.com/mackworth/cTiVo/files/5431635/com.cTiVo.cTiVo.2020-10-23--20-18-21-823.log.zip)

**Comment by mackworth** [comment]
did it ever ask for a MAK?

**Comment by FloridaMatt** [comment]
It didn't ask, but the MAK is in the local tivos list

**Comment by mackworth** [comment]
right, but if the defaults are erased (and logged out), then it shouldn't have any MAK.

**Comment by FloridaMatt** [comment]
I had supplied it (unasked) on the first install when they showed up, but I did move the com.ctivo folder from library to trash, and then rebooted before starting the beta.

**Comment by FloridaMatt** [comment]
The mak does not appear in the log...

**Comment by FloridaMatt** [comment]
nor in com.ctivo.  and a system wide search for ctivo, including hidden files, didn't find anything else.

**Comment by mackworth** [comment]
It's always blocked in the logs, (so people can post them without revealing MAK). 

When you say you moved the folder, that would be the log folder, no?  Need to move ~/Library/preferences/com.ctivo.ctivo to trash, then log out/back in.  you can confirm that it worked in Terminal, type `defaults read com.cTiVo.cTiVo TiVos`, and it should say `The domain/default pair of (com.cTiVo.cTiVo, tivos) does not exist`

**Comment by FloridaMatt** [comment]
Sigh.  I had deleted the com.ctivo folder in application support, and not the one in preferences.  But Finder, for some silly reason, faiuled to find the ctivo file in preferences.  Ok, give me a few minutes and I'll get it right this time...

**Comment by mackworth** [comment]
Oh, there's also a possibility that the MAK got stored in your Keychain (if you checked that box).  If so, you can search for "tivo",  it'll be in the form of internet password for dvr-XXXX.local.  where x is a hexadecimal digit

**Comment by mackworth** [comment]
And ... I didn't even know it was creating an Application Support folder, as that's new with the latest crashlytics.  Thanks for that info!

**Comment by FloridaMatt** [comment]
Ok, started the beta after properly clearing stuff.  It instantly demanded the MAK for one tivo (M Bedroom), and went on to display its contents.  And that's kind of it.  No other tivos found.  Edit tivos only shows m bedroom (but at least it's enabled).
[com.cTiVo.cTiVo 2020-10-23--21-21-18-259.log.zip](https://github.com/mackworth/cTiVo/files/5431839/com.cTiVo.cTiVo.2020-10-23--21-21-18-259.log.zip)

**Comment by FloridaMatt** [comment]
Apologies for before, I'm somewhat new to macs, having been working with windows nt since before it had a name...

**Comment by FloridaMatt** [comment]
have to step away for a bit for supper

**Comment by FloridaMatt** [comment]
quit ctivo & restarted; now it sees all the tivos and didn't ask about their maks.  Done computing for evening, back tomorrow.  As before, close if you want, or I can do additional testing.

**Comment by mackworth** [comment]
I think I see the problem (and restarting to find the rest fits it). I've made a change that I'd love you to test, as I think the remaining problem only exists with multiple TiVos. I'm testing it now, so if you can give it a try tomorrow, that'd be great.

Same test: trash com.ctivo.ctivo from preferences, log out, log back in,  (or you can do  `defaults delete com.cTiVo.cTiVo' in Terminal), then run the beta

**Comment by mackworth** [comment]
Here's the 3.4.2 beta2 link:  https://www.dropbox.com/s/ta1sv7p3wph4xam/cTiVo.app.zip?dl=0

**Comment by FloridaMatt** [comment]
Works fine.  Asked for mak for one, then picked up all 4 and marked them enabled.  Thanks.

Unrelated question: might a future version support publishing files for a tivo to find and upload (like pytivo, but with the added ability to create data files allowing the tivo to see them as episodes within a series)?

**Comment by mackworth** [comment]
Yay!  Thank you.  I haven’t had a good repeatable case, so this is excellent news.

On your pytivo-like case: the short answer is no for cTiVo. TiVo has broken the upload functionality with Hydra UI, which is all that’s supported on the very latest machines.  

On the other hand, (assuming the old uI)  pytivo works great with cTiVo even on the same machine. Thus folks will offload shows to a Mac or network hard disk, and be able to immediately browse them using PyTiVo.  All metadata is maintained in the round trip. (I actually thought about bundling a copy of PyTiVo inside cTiVo to make setup easier, but never quite got around to it.)

Which presents the opportunity to create or modify that metadata on the Mac as you wish.  Again, requires the old UI.

There are discussions of this on pyTiVo site on Tivo Community Forum.. IIRC, Matching up to an existing series requires getting the seriesID correct.  The actual season/episode numbers are stored as standard MP4 tags.

So if you use the mp4v2 library you can add the metadata yourself.  All the mp4v2 manipulation is in MTTivoShow.m  There’s a createTestMP4 routine that shockingly creates a test MP4 that contains metadata, so you can see how that’s done.

BTW, you don’t need to code at the c level necessarily. There’s an old program atomicParsley that can read/set MP4 tags from a command line.

Beyond the Season/episode info, the tivo-specific metadata are stored in one of two places. The first is  a .TXT file with same directory/basename as the MP4 file. cTiVo creates this if it is enabled in AdvPrefs “Eport Metadata to pyTiVo .TXT file".  This is created from the XML downloaded from the TiVo about each show, using an  embedded XSLT template to do the XML->TXT transformation.  format is:

showingBits : 0
time : 2020-09-15T01:58:00Z
showingBits : 0
colorCode : 4
description : Noticias deportivas y temas del momento son debatidos.
isEpisode : false
seriesTitle : Pasión Deportiva
title : Pasión Deportiva
startTime : 2020-09-15T01:57:58Z
stopTime : 2020-09-15T02:01:01Z
seriesId : SH0322878787
displayMajorNumber : 1037
callsign : KPWC-LD5
programId : SH0322878787-0322877280

Alternatively, the tivo-specific metadata are embedded as XML within the MP4 using a custom tag that was agreed to with pyTiVo.  If you use the MediaInfo app to show you the MP4 tags, you’ll see one named tiVoINFO, which looks like the following 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>colorCode</key>
	<string>4</string>
	<key>displayMajorNumber</key>
	<string>710</string>
	<key>programId</key>
	<string>EP0000017787-0428858588</string>
	<key>seriesId</key>
	<string>SH0000017787</string>
	<key>showingBits</key>
	<string>4099</string>
	<key>startTime</key>
	<string>2020-10-15T03:59:59Z</string>
	<key>stopTime</key>
	<string>2020-10-15T05:00:00Z</string>
	<key>time</key>
	<string>2020-10-15T04:00:00Z</string>
</dict>
</plist>
