### ISSUE TITLE
Minor positioning error

### ISSUE THREAD

**Issue by FloridaMatt** [mackworth/cTiVo#433]
The word "encoding" isn't quite in the column.
![image](https://user-images.githubusercontent.com/1142046/97085586-5a840a00-15ec-11eb-8eac-1b940fa20bfa.png)

**Comment by mackworth** [comment]
Well, technically, it's fully in the column, just right-justified versus the column header, which is centered. The progress-bar highlighting further makes it look outside the column. On the other hand, the program is somewhat inconsistent about justification, and I'll take a look at that.
