### ISSUE TITLE
ComSkip Log

### ISSUE THREAD

**Issue by Jimbronie** [mackworth/cTiVo#435]
Hi,
  I love cTivo. The ComSkip has been rock solid for what I use it for (Hallmark holiday Movies).  But lately it has been clipping the very beginning of the movie.  I know this isn't a cTivo issue, but what I was wondering is, where are the Comskip logs stored at?.  I am looking for it so I can determine what values to change in the Comskip.ini to fix the beginning clip.

Thanks!
Keep up the great work!

**Comment by mackworth** [comment]
The log is stored in cTiVo's temp directory, the name is chosen by macOS, starting with `/private/var/folders...`. You can see the path to it by going to Adv Prefs and clicking on the Temporary Files Directory Field, then clicking on the folder at the top of the form. You can also manually choose another  folder to make it more convenient.  You're looking for` commercial... .txt` and/or `commercial... .err`.  

Note that cTiVo typically deletes the files immediately after a download, so you'll need to turn on `Don't delete temp files (for debug only)`.  This will leave ALL the temp files, including the massive video ones, so turn it off after you're done experimenting. 

Alternatively, cTiVo will also record the last 5K of both log and error files in the cTiVo Logs (`Help>Show Logs in Finder`) if there's a comskip failure OR if you turn Debug Level for Task to Detail in Adv Prefs.

I take it you're looking at the comskip website for .ini ideas, but let me just mention that you chosse your own .ini file by Duplicating a Format in Edit>Formats, then adding`—ini=<full path>/comskip.ini` in ComSkip Options, providing the path to your .ini file.

**Comment by Jimbronie** [comment]
﻿
﻿Thanks so much for all the great info. It will be a big help!

Sent from my iPhone

**Comment by mackworth** [comment]
Great. let us know if you find a good solution.
