### ISSUE TITLE
Big Sur

### ISSUE THREAD

**Issue by LarryWahlers** [mackworth/cTiVo#436]
Will upgrading to Big Sur break cTivo?

Thanks!

**Comment by mackworth** [comment]
If you're running current version, I don't believe so. I've done some basic testing, and it's been fine.  Let me know if you have any issues.

For anyone looking...Apple Silicon seems to be fine also running cTiVo under Rosetta. ffmpeg and the other apps have not been recompiled for ARM yet. That should happen over the next couple months, and I'll do a new version then.

**Comment by LarryWahlers** [comment]
Thanks! I just bought a new Mac Air a month ago, so I’m running Intel processor. I’m glad I did, too, because I use BOOTCAMP. 

-- 
Larry

**Comment by ryanbreen** [comment]
I can confirm everything looks fine on Big Sur, so I think this is closable.

**Comment by mackworth** [comment]
For anyone searching here, there’s a lot of good work going on for ffmpeg on M1, but still a ways to go yet. Handbrake does have a beta out, so I could do a Franken-beta-release with ffmpeg as Intel and cTiVo/Handbrake as AS1 if anyone wants to experiment with that.
