### ISSUE TITLE
TiVo Edge

### ISSUE THREAD

**Issue by richmilchman** [mackworth/cTiVo#438]
I just upgraded from a Romeo to an Edge.  cTiVo had been working perfectly using the Romeo for years.  When trying to download and encode from the Edge the videos are choppy and pixelated.  Any suggestions?

**Comment by mackworth** [comment]
So, I take it the same videos are fine on the screen?  
Look at your signal strength/SNR in the TiVo settings screens on channels with an issue.  

Nonetheless, an attenuator may help:
https://www.tivocommunity.com/community/index.php?threads/tivo-edge-pixelation-issues.574905/

If you still have your Romeo, then recording a short segment on your TiVo, and downloading the Decrypted TiVo version would let me compare the files to see if there's a difference. Also, it would be worth seeing the logs (Help>Show Logs in Finder> )

Let me know if that helps.

**Comment by richmilchman** [comment]
Live viewing of shows is fine as well as watching recorded videos on the TiVo itself and on tivo mini's. Unfortunately the Romeo is no longer connected.  I can download a show off of my Edge and post it in a location where you can download it if it would help.

**Comment by mackworth** [comment]
Have you looked at the SNR/strength? Sometimes the digital files have issues that only come up during the encryption process that ties the downloaded video to your MAK. It looks like the Edge is more susceptible to this issue.

**Comment by richmilchman** [comment]
It's the cable version.  Signal strength 100%, SNR 41DB.  It's also connected to Fios, so theirs fiber into my home, then the OTA has a coax output.

**Comment by mackworth** [comment]
So, TiVo says the maximum on SNR is 30-35, so 41 is way strong, which might make sense if it's coming straight in from the box. 

As the Edge is sensitive to overdriving, that could cause the problem. 
Maybe try adding a splitter? Just connect it in and out; ignore second output. This will reduce the signal strength. 

There's a good discussion and more diagnostics here:
https://tivoidp.tivo.com/tivoCommunitySupport/s/article/Troubleshooting-Digital-TV-Signals

**Comment by richmilchman** [comment]
There already was a 3 way spliiter, added an additional 2 way and the numbers didn't drop.  Guess I'll order some attenuators and see if they help, just need to figure out what sizes to try.

Thanks

**Comment by mackworth** [comment]
Do you see any RS issues?

**Comment by richmilchman** [comment]
No RS issues

**Comment by mackworth** [comment]
btw, I note [this comment](https://www.tivocommunity.com/community/index.php?threads/tivo-edge-pixelation-issues.574905/):

> I ordered a few different attenuators. 3db, no change. 6db, no change. 8db, slightly better. 9 db, 12 db, 16 db, 18 db, 20 db, all no change. At 26 db the signal strength finally moved and was low to mid 90s and SNRs were 35-37, but the pixelation was actually worse. We ordered a new splitter and we'll try replacing the splitter on the outside of the house, other than that I have no idea what else to do.

**Comment by richmilchman** [comment]
Thank you.  If I add all the ones I ordered it comes out to be ~28 db, they should arrive tomorrow.   

Something I find interesting is if I copy a show from one TiVo to another (using TiVo Online) on the original TiVo the file converts fine.  On the new one it's all jittery / pixilated.

If I have time tonight or tomorrow I will try recording something on the Edge, copy it to the Romeo and then converting it.  This is more curiosity then anything.  I do need to get the edge working properly.

Thanks again.

**Comment by mackworth** [comment]
Not quite clear what that middle paragraph means? Sounds like if you copy from the Romeo to the Edge, the download is pixelated, but if you copy a show from the Edge to the Romeo, it's fine.  That would pretty clearly indicate it's NOT a signal issue, as the Edge-recorded show would already by corrupted.

But that interpretation seems contradicted by the third paragraph?

**Comment by richmilchman** [comment]
Sorry let me restate what I tested.

Record on the Edge, convert from the Edge.  Pixilation

Record on the Romeo, convert on the Romeo.  No issue

Copy from the Romeo -> Edge (traffic goes over Ethernet), convert  on the Edge.  Pixilation

Today or Tomorrow I will try recording on the Edge, copy to the Romeo, convert on the Romeo.

**Comment by mackworth** [comment]
Ok. So, that Romeo->Edge file was obviously fine on the Romeo hard disk prior to being transferred, so it can't have been corrupted by a signal-strength issue. Instead something on the Edge downloading process must be going wrong.  

Can you try using the  `Decrypted TiVo Show` Format (it's hidden by default, so you'll probably have to go to Edit>Formats, select it from the list and click `Show in User Interface`)?

That downloads a show without any re-encoding, just the decryption. That will show whether the pixelation is occurring on the Edge, or if there's an interaction with the re-encoding.

**Comment by richmilchman** [comment]
I tried the decrypted format, still no luck.  I found several posting saying this "I received a update recently (21.9.7.v3-USM-12-D6F) and now tivo2go appears to be working. Thanks Tivo. There is a catch. I get a lot of video corruption issues when using a ps download. ts works fine Yay."  

To be honest, I'm not sure what it means or how to do it.

**Comment by mackworth** [comment]
I take "no luck" as meaning still pixelated?  Can you look at the file in Finder with Get Info? What Codec type does it show?

TS is Transport Stream. PS is Program Stream. You have to use TS for H.264 compressed video (aka MP4), and generally you use PS for MP2 (aka mpg or .ps).  

So, go to Edit Channels, and it will show you whether each channel is using H.264 or not. You can force it to download the other type with the Use TS column.  Note that a H.264 cannot be downloaded with PS. You will only get an audio signal if you try (and cTiVo will complain). On the other hand, you can force a TS with a MP2, which would fix the problem as described in that quote. Clear enough? :)    

There's more details here:  https://github.com/mackworth/cTiVo/wiki/Advanced-Topics#edit-channels

**Comment by richmilchman** [comment]
For the show I'm testing with it shows "AC3, MPEG-2 Video".

**Comment by mackworth** [comment]
Ok, so that's a MP2, which by default will download as PS.  Go to the channel you are using in Edit Channels, turn on Use TS, for that channel, and try it again.  If it's the same thing they are describing, it will now download as TS, and hopefully fix the pixelation.

**Comment by richmilchman** [comment]
I made the change, but it had no effect.

**Comment by mackworth** [comment]
Sorry; I've got nothing else. If the raw files coming across are damaged/pixelated, there's really nothing cTiVo can do. The only other possibility would be to look at the decryptXXX.txt and .err files in cTiVo's temp directory (you can turn on  "Don't delete Temp files" in Adv Prefs, but be sure to turn it back on again afterwards.  It's vaguely possible that the decryption software is not working well for you.  There's another choice TiVoLibre (again in Adv Prefs), but it requires that Java virtual machine be installed on your system, so I don't generally recommend it.

**Comment by richmilchman** [comment]
Thanks for your help.  I did try changing decoders, but it didn't seem to correct the issue.  I guess I'm stuck waiting / seeing if TiVo does anything to correct the issue.

**Comment by mackworth** [comment]
Sorry I don’t have any other suggestions. Hope they are of some help. 

(Just one last suggestion: in the Finder, check with get info that the shows you downloaded as TS, really are?)
