### ISSUE TITLE
Odd captioning error message

### ISSUE THREAD

**Issue by wjmt3** [mackworth/cTiVo#439]
When transferring a program today, I got an error message (paraphrased from memory) that said "Error decoding captions. Captions not included."

And yet, as I discovered afterwards, the captions are perfectly intact.

Before the error message, the transfer speed was slow (3.2 MBps); afterwards, it jumped to 12 MBps.

Something happened, but it doesn't seem to have had anything to do with captioning. Do you have a clue what might be going on? This has happened before, but I just now remembered after the most recent occurrence.

Thanks!

**Comment by mackworth** [comment]
I've seen this as well; haven't looked into it much yet, but I think it has to do with a download failing due to PS/TS issue, then captionTask reports a failure, even though what's actually happening is restarting with TS instead.

**Comment by mackworth** [comment]
Confirmed that 's the problem.  Will fix
