### ISSUE TITLE
Unable to see TiVo's anymore

### ISSUE THREAD

**Issue by stevehoek** [mackworth/cTiVo#440]
Not sure if this started since updating to Big Sur or not, but on both my MBP and iMac I can no longer see the TiVo's.
I have 6 Mini's and 2 Roamio's and an Edge.
Discovery app does not show any Bonjour advertisements from _tivo on either Mac
However, Discovery on the iPhone does
So, I'm thinking it is something with the Mac?  or Big Sur?
I don't run any firewall or anything on the Macs.

Edit: I just check my Windows machine with pyTiVo and it can see the TiVo's just fine.  

Any ideas?

**Comment by mackworth** [comment]
It seems like there's two possibilities: either something changed in your network or Bonjour is being blocked within your system.  (I'm glad you checked Discovery; that helps a lot). OTOH, if it's just the TiVos, and just on the Macs, that's pretty weird. I don't have any obvious answers, Big Sur in general works fine, but I have a buncha tests you can try:

On the network side: Sometimes a change of routers can cause problems with Bonjour network discovery. Certainly try rebooting routers/modems etc. Strangely, rebooting any AppleTVs may help also (they maintain a directory for devices that have gone to sleep). Haven't heard of it being necessary for a while, but sometimes bringing down the entire core net (all hubs/routers/ATVs/modems) at once can flush the shared directory caches. Maybe avoid Wifi for a test and connect your iMac and a TiVo via wired Ethernet? 

In Discovery, can your Mac see other devices (each other, Windows, etc)?  Can you see a printer that iPhone/ Windows machine can see?Within the Mac, are other services visible? Any anti-viral software running? Double check the built-in firewall.  Turn one of the Minis off, reboot a Mac, run Discovery, and then restart the Mini, and after it's up, refresh Discovery.

Sorry I can't be more help than "Turn it off and back on", but maybe some of these might help. Let me know what you find.

**Comment by stevehoek** [comment]
Thanks for the detailed reply.  I did reset a few of the devices, such as the router and ATV, but that did not help.
I checked my wife's MBP running Catalina still and it can see the TiVo mDNS/Bonjour services.

My iMac and MBP are configured with almost all the same apps, so that got me wondering if it was something on the system that was preventing it.  I know cTiVo was working sometime this summer when I used it to pull some shows off a TiVo Roamio before upgrading to the Edge, so it may not be related directly to Big Sur, but that is when in my mind I seem to have noticed it.

I just now booted my iMac into Safe Mode, and it can see the _tivo-device.tcp_ mDNS service, as well as the other TiVo and non-TiVo services that it was not seeing before.  So, something in the OS or the apps I run seems to be interfering with seeing the full list of mDNS services.   After rebooting back to "normal" Mode, I no longer see the full list of services.

I know now this is not a cTiVo problem, but can you think of anything to check to see what could be blocking some but not all mDNS services?  Its really strange... I still see third party services like Spotify Connect and HEOS, but not all of them.

**Comment by stevehoek** [comment]
Well, I found the culprit... the latest version of Checkpoint Endpoint Security VPN that I need to access my corporate network.
I recently upgraded it to the latest version to be ready for Big Sur, and after uninstalling it I could see all my Bonjour/mDNS services again.

I'll report the issue to them and hope they can resolve it!

Thanks for listening and trying to help.

**Comment by mackworth** [comment]
Hah! Told ya it was a firewall. (Well, together with 20 other things...). 

You may need to specifically whitelist the TiVos. I note that TiVo uses a self-signed SSL cert, which triggers a lot of these security systems.
