### ISSUE TITLE
Queue Stuck?

### ISSUE THREAD

**Issue by tracer-x1** [mackworth/cTiVo#441]
Hi,

LOVE this app.  Thanks so much for spending time on it.  My 80 year old mom uses it daily.   Weirdly, it just stopped......the shows are in the queue, but the queue won't start. I tried pausing and unpausing, reinstalling and rebooting the Tivo.  I'm a bit stuck on how to help her.  Running on a Mac (10.15.7).

Thanks!

**Comment by tracer-x1** [comment]
Tried a new disk, which worked.

**Comment by mackworth** [comment]
Well, this was easy...  Happy Black Friday!
