### ISSUE TITLE
Subscriptions Location

### ISSUE THREAD

**Issue by mosleyh** [mackworth/cTiVo#442]
Trying to rebuild after a crash. Where does cTiVo save subscription data?

**Comment by mackworth** [comment]
In the prefs file.   ~/Library/Preferences/com.ctivo.ctivo.plist

In Terminal, `defaults read com.ctivo.ctivo SubscriptionList` will show you current subscriptions

**Comment by mackworth** [comment]
Were you able to rebuild?
