### ISSUE TITLE
Constant restarts with Mac Big Sur 

### ISSUE THREAD

**Issue by slodiver** [mackworth/cTiVo#444]
Hello... I have been having problems getting my Tivo recordings over to my Mac (2019 3GHz 6-core Intel Core I5 with 40GB of RAM) ever since I upgraded to macOS Catalina. I thought that it might fix itself when I upgraded to Big Sur, but it hasn't. I did a complete erase and install but I did save my settings. CTivo is the only program that creates this crash. I have been using CTivo with great success for quite some time and would love to see this resolved. I've attached my most recent error log. It seems to trigger a kernel panic but I can't figure it out. Can you help? Thanks! Chad

[Error log.txt](https://github.com/mackworth/cTiVo/files/5710770/Error.log.txt)

**Comment by mackworth** [comment]
Sorry, I missed this one.  I don't have a lot of suggestions here. I haven't had anybody else complain of kernel panics. My main thought is that cTiVo might be triggering a hardware problem as it drives a lot of disk traffic, and uses a LOT of CPU time for the reencoding process. You might try restricting it in Adv Prefs to only one encoding at a time.  

Reading your panic log: you crashed in the kernel with the backtrace only containing Apple extensions.  Do you have any third-party RAM in your system?  Are you using an external drive with cTiVo? Do you have other reports to see if there's any consistent message?

**Comment by slodiver** [comment]
Wow! Thanks for responding! I had forgotten I emailed you. I do have third party ram. No external drives on my TiVos. I have three. I’ll limit it to one encoding at a time and one TiVo at a time too. Ran for a long time with same settings and no problems before Catalina upgrade. 

------------------------------
Chad Lortie

**Comment by mackworth** [comment]
How's it going?   If you're still having issues, the third party RAM can be a problem. You can run Apple's diagnostics by booting up while holding down D key.

**Comment by slodiver** [comment]
Thanks so much. I’ll try that tomorrow!

------------------------------
Chad Lortie

**Comment by mackworth** [comment]
Just going back through old issues; any luck here?

**Comment by slodiver** [comment]
So I removed my third party Ram and everything worked. Then I reinserted in a different configuration and it works. Must have been the way I had it set up! Thanks for following up!

------------------------------
Chad Lortie

**Comment by mackworth** [comment]
Good to hear!
