### ISSUE TITLE
Get SkipMode grayed out

### ISSUE THREAD

**Issue by alecksjaycubd** [mackworth/cTiVo#445]
In the past this has been just fine but for some reason right now I can't choose Get SkipMode from Tivo when I right click on a show. I've restarted just about everything and I'm on the latest version. Any thoughts? I feel like I'm missing something simple but can't find it.

**Comment by mackworth** [comment]
There should only be three reasons SkipMode will be grayed out. 
o The show doesn’t have any SkipMode Info OR
o cTiVo has already downloaded it OR
o cTiVo has tried and failed 

What does the SkipMode column show?

**Comment by alecksjaycubd** [comment]
Well I think I played a part in this. There was a block of shows, some of which showed the skip logo. I added some shows and tried the Get SkipMode menu but it was gray. I thought maybe there was a problem so I highlited all from that block and chose Reload All Info. The shows that had the Skip logo no longer showed that logo so I thought I had to have cTivo check them again but that option is still grayed out.

**Comment by mackworth** [comment]
well, to figure this out, I need you to be a little more specific on the skipmode icons. It might be worthwhile to see the [operation of skipMode in the docs here](https://github.com/mackworth/cTiVo/wiki/Commercials#skipmode). 

it shouldn’t be the case that the icon goes from green-on-white or white-on-green to blank, even if you do a reload, but a reload will reset the comskip one (black on green, which usually happens after a download).

The Get SkipMode command will only be available if one of the selected shows is in the breakpoints “available” mode (green on white). Once they are pulled over, it goes to white-on-green.

I’ve updated the previous comment with the relevant icons as well.

**Comment by astettner** [comment]
Hi.

I hope you don’t see this as too much of an intrusion but is there a way to speed up the transfer from a TiVo?   What is the max speed or where is that “throttled?”

   armando

Sent from my iPad

**Comment by mackworth** [comment]
Sorry for delay; should really open a new issue instead, as it's somewhat unrelated.

Unless you have a slow wireless network, the performance for the download is mostly determined by your TiVo. It has to encrypt the download. In my experience, that restricts it to about 12mbps.  Once the show is downloaded, then it has to be re-encoded (to compress the size). This is determined by which Format you choose. Higher resolution outputs are slower than low res ones.  More info on this (and some benchmarks) available here:  https://github.com/mackworth/cTiVo/wiki/Video-Formats

@alecksjaycubd  any results?  Also, can you check for "latest version" again?

**Comment by mackworth** [comment]
Closing due to lack of response. Let me know if there's still an issue.
