### ISSUE TITLE
Deleting shows issue

### ISSUE THREAD

**Issue by CipherDude** [mackworth/cTiVo#446]
When pressing the delete keys (command+delete) or using delete from the menu bar (Edit --> Delete), the selected group &/or selected individual shows do not delete from cTivo (or from Tivo itself).

I get the following in the log:
2021-01-01 08:27:31:895 -[MTTivoRPC tearDownStreams]@370>Tearing down streams for *[Name of Tivo]*
2021-01-01 08:27:31:895 -[MTTivoRPC checkStreamStatus]@329>Stream failed, but reachable: (null) (failure #0); Trying again in 10 seconds
2021-01-01 08:27:41:896 -[MTTivoRPC launchServer]@291>Launching RPC streams for *[Name of Tivo]*
2021-01-01 08:27:41:938 -[MTTivoRPC stream:handleEvent:]@565>StreamError on inStream: Error Domain=NSOSStatusErrorDomain Code=-9828 "(null)" UserInfo={_kCFStreamErrorCodeKey=-9828, _kCFStreamErrorDomainKey=3}

I tried restarting the app. Did not fix
I deleted the preference file: it worked for a bit, but now it doesn't fix the issue.

**Comment by mackworth** [comment]
Sorry to hear that. Have you updated to 3.4.3? The old RPC certificate in 3.4.2 and prior expired in December.

If you have, then I'm a little surprised deleting the Prefs file had any effect. but the first thing I would do is reboot the TiVo itself. If that doesn't fix it, then let me know: do you have the same problem with other RPC-based commands?  For example, does the Remote Control window work? Does getting SkipMode data work? Are you getting images that match the ones on TiVo? (In a somewhat circular question, does your "Reboot TiVo" command work?)

If you can increase TIVoRPC logging in Adv Prefs to Detail, that might help me narrow down what's going wrong.

**Comment by CipherDude** [comment]
Hi,
Thanks for the response. The version is: 3.4.2 (1124)
I did try to update the software (many times), but it tells me that it's up-to-date.

I get the following pop-up window when I go to "Check For Updates":

"You’re up-to-date!
cTiVo 3.4.2 is currently the newest version available."

How do I get the current / updated version?

Thanks.

**Comment by mackworth** [comment]
Indeed.  Try "Check for Updates" again.  (Thought I had pushed 3.4.3 but ... no)

**Comment by mackworth** [comment]
I take it this is ok now, so I'll close this issue.

**Comment by CipherDude** [comment]
Yes. It’s working.

Thanks.
--
