### ISSUE TITLE
Recording status in cTiVo not matching that reported ON the TiVo

### ISSUE THREAD

**Issue by wjmt3** [mackworth/cTiVo#447]
In cTiVo, I see a LOT of programs with yellow exclamation dots, the majority of which are actually standard blue dots if I look on the TiVo itself. It's as though cTiVo doesn't have (or isn't applying) a standard dot icon. I seem to remember this wasn't always the case. Is there a regression that's crept in somewhere?

Edit 1: Just now, as I have a program in the queue, I notice the program does have a blue dot, but perhaps only because it is currently in the queue? Every other program is either a green dot or a yellow exclamation.

Edit 2. Nope. The dot remained blue after it completed, but it was a yellow exclamation dot when I started it. The transfer did have the PS/TS issue (#439), so perhaps the icon got updated when it restarted as TS? Otherwise, I'm stumped.

Thanks!

**Comment by mackworth** [comment]
Hmm, I investigated this a while ago, but apparently didn't write it up.

It's actually TiVo that changed. It used to distinguish between shows just about to be vulnerable to deletion and ones that were further off. Quoting there manual:
> Blue Dot: Recording will be kept until space is needed.
> Yellow Dot: Recording may be deleted in less than 3 days to make room for other recordings you have requested, but only if space is needed.
> Yellow Exclamation Dot: Recording may be deleted in less than one day to make room for other recordings you have requested, but only if space is needed

They now say: 
> Blue Dot: Recording will be kept until space is needed.
> Yellow Dot:  Recording may be deleted to make room for other recordings you have requested, but only if space is needed.
(Personally, I can't tell the difference between those two.)

In practice, I only see Blue dots and Green dots on my TiVo.

Meanwhile, they haven't changed what they report in the API, except that I notice that shows that used to be marked as "Recent" (cTiVo Blue Dots) are now marked as "To Be Deleted" (cTiVo Yellow Dots). AFAICT, only shows that have just finished being recorded come up as Recent (cTiVo Blue). At some point, they quickly change it to "To be Deleted", but TiVo doesn't notify cTiVo of a change, so cTiVo never updates the screen. If you manually refresh or it refreshes for some other reason (e.g. starting a transfer), then the dot will refresh to yellow.

So, long story short, TiVo stopped displaying Yellow icons, and now displays only Blue. cTiVo still shows the old yellow ones, as that's what TiVo is telling us. I could convert it to blue, but it wouldn't change the meaning (except losing the 1 day vs many days distinction).

**Comment by mackworth** [comment]
Well, decided matching what TiVo shows is worth it, so I changed the yellow to Blue, and added a Blue Exclamation point one.

**Comment by wjmt3** [comment]
Sounds great! Matching TiVo, yet not giving up the distinction that remains helpful!

**Comment by mackworth** [comment]
[New release here](https://github.com/mackworth/cTiVo/releases/tag/3.5.0Beta)
