### ISSUE TITLE
Increase volume when encoding

### ISSUE THREAD

**Issue by pkleeberg** [mackworth/cTiVo#448]
One TV station is at a lower volume after conversion.  With FFMPEG with KMTTG, I was able to modify the .enc file to include -vol 1024.  Do I modify a line in /Applications/cTiVo.app/Contents/Resources/ffmpeg_edl_ac3.sh?  If so what is the line or what do I search for?

**Comment by mackworth** [comment]
Just go to Edit Formats and Duplicate the Format you want to change (eg Default). Probably rename it to `Louder Default`or something. Then add your `-vol 1024` to Encoder Audio Options and Save. Then you can select that Format for any download or subscription. 

If you have any problems, set Log level for Download to Detail to see the exact string passed to the EDL shell script. (Or let me know)

**Comment by mackworth** [comment]
I take it that worked?  Let me know otherwise...
