### ISSUE TITLE
De-Sync'ing Video/Audio

### ISSUE THREAD

**Issue by bop3162** [mackworth/cTiVo#449]
Exporting Tivo Hallmark recordings from Romeo to CTivo - format ProRes LT
to new Mac mini. latest Apple OS (apple silicon)
Edit with Final Cut Pro to cut out commercials.
"share" to .mp3 file for use in Plex server/client

Output progressively looses video/audio sync as you go from the start to end of the movie.

Anyone familiar with this condition (and maybe a solution). The problem has way too many variables to figure it out from scratch.  Especially if someone has already been through it...

**Comment by bop3162** [comment]
correction .MP4 files output to Plex system

**Comment by tdlivings** [comment]
ProRes LT is problematic. Instead you can download handbrake and use Production Proxy 1080 with the sync a/v box ticked and it will give you a Final cut editable mp4.  Thanks to Hugh, you can use this as an output for subscriptions in the cTiVo app.

**Comment by bop3162** [comment]
tdlivings - the reply is a bit confusing.  is "Production Proxy 1080" an app that needs to run under handbrake?  Couldn't find "Production Proxy 1080" as an available download format among the cTivo formats.

**Comment by tdlivings** [comment]
It is a preset in handbrake. Once you customize it with align a/v you can save it in handbrake and then open ctivo and make it available as a preset.

**Comment by mackworth** [comment]
So, I take it this is resolved?
