### ISSUE TITLE
Multiple OSs multiple Macs downloads always fail

### ISSUE THREAD

**Issue by ronhare** [mackworth/cTiVo#452]
High Sierra on iMacPro. Mavericks on old MacPro. Roamio and Bolt.
cTivo worked last month but now fails repeatedly to download even on local news.
I created a tmp file per the latest High Sierra issue. Nothing changed.
Mavericks delivers 0-byte files after hours of starting a download, then starting over after stopping partway.
Rebooted Tivos and everything else in the house.
[com.cTiVo.cTiVo 2021-02-13--20-48-25-646.log](https://github.com/mackworth/cTiVo/files/5978705/com.cTiVo.cTiVo.2021-02-13--20-48-25-646.log)

**Comment by ronhare** [comment]
Update:
Using El Capitan and waiting for partial downloads/retries, cTivo generated a file readable by VLC. Reformating by HandBrake made it useful.
Note: The El Capitan Mac does NOT have the cTivo /tmp folder. That folder is no the iMacPro running High Sierra.

**Comment by mackworth** [comment]
Due to power failures, I’m having serious internet problems, so can’t really try anything out, but I see you’re getting a lot of Java failures. Try switching to tivodecode in Adv Prefs.

**Comment by ronhare** [comment]
tivoencode-ng has been the default for ctiVo on all my Macs.
I also tried a Mohave iMac. No luck there.
All tries were with the Roamio, but the Bolt seems no better, though.

A clean install of Mavericks just this week on a brand new hard drive in the 2009 MacPro is the only configuration that works.
Curiously, even the Mavericks configuration flails around and eventually refuses to download a file marked "Keep Until I Cancel" (CW Network via Comcast Cable).
Also, ctiVo created an audio-only file from one of the two High Sierra Macs.

There are way too many variables here, and I accidentally stumbled on one combination that works (except for the file that's marked "Keep-Until") - the clean install of Mavericks .
I can live with that, so problem accidentally solved.

It's still puzzling why cTivo worked so well last month and doesn't now.
I changed nothing that I know of.

Thanks for your quick reply.

**Comment by mackworth** [comment]
That’s very strange. The log file above shows many decrypt failures, all due to tivolibre not finding a useful version of Java. 
````
[MTTask failedTaskCompletion]@246>Task decrypt failed
2021-02-13 12:48:49:793 -[MTTask saveLogFileType:fromPath:]@208>errFile for task decrypt: Exception in thread "main" java.lang.UnsupportedClassVersionError: net/straylightlabs/tivolibre/DecoderApp : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ...

````

Well, glad it’s working. If it starts failing again, happy to help figuring out why. (After my power comes back, that is)

**Comment by ronhare** [comment]
The High Sierra Mac was set to tivolibre when the log file was created.Changing it did not help, so there must be other problems.All other Macs, including the Mavericks that works, were defaulted to tivodecode.
Since nobody else is reporting this, I must have a gremlin in the wires.Oh well.
Thanks again.


-----Original Message-----

**Comment by mackworth** [comment]
Happy to look at other log files to see what happened...
