### ISSUE TITLE
Download Folder dialog box won't go away if expected folder is offline and you click Cancel in response

### ISSUE THREAD

**Issue by wjmt3** [mackworth/cTiVo#454]
My download folder is on an external volume. If I forget to turn it on, I am (as expected) prompted to choose a new one, use the default location, or click Cancel, which is useful if you don't want to make changes, having perhaps launched cTiVo accidentally.

But if I click Cancel, however, the dialog box just reappears, endlessly, until I either bring the expected folder online, or choose one of the other options.

**Comment by mackworth** [comment]
So, "Cancel" here implicitly means "I fixed it, check again", so maybe you plugged in a drive, or turned it on.  

There's really no scenario in which we want to proceed w/ cTiVo running w/out an available folder, but you're correct: I'll add a button for Quit cTiVo as an alternative.
