### ISSUE TITLE
Error: Show May Be Damaged/Incomplete

### ISSUE THREAD

**Issue by n0g0** [mackworth/cTiVo#455]
Trying to figure out why I'm getting this error - plays fine on the Tivo itself, trying to download results in nearly immediate error.

There is a visible "glitch" in the recording when played back on the Tivo - does this mean the stream is corrupt?

Also - the error log says it's a Series3, but I verified on my Tivo that I have a Series4. Not sure if that's related?
[decryptLaw & Order-Special Victims Unit-The Only Way Out Is Through-2.err.TXT](https://github.com/mackworth/cTiVo/files/6057486/decryptLaw.Order-Special.Victims.Unit-The.Only.Way.Out.Is.Through-2.err.TXT)
[encodeLaw & Order-Special Victims Unit-The Only Way Out Is Through-2.err.TXT](https://github.com/mackworth/cTiVo/files/6057487/encodeLaw.Order-Special.Victims.Unit-The.Only.Way.Out.Is.Through-2.err.TXT)

**Comment by mackworth** [comment]
Yes, if you look at the encode error log, it says `corrupt decoded frame in stream 0` on frame 311. 

Unfortunately, the TiVo encryption process is more susceptible to damaging the stream that its display process, so it can display shows that come over corrupted. Sometimes, but not very often, Handbrake can convert them when ffmpeg can't (and vice-versa), so you could try that. Other than that, there's not much hope.
