### ISSUE TITLE
Requesting key access

### ISSUE THREAD

**Issue by dcborn61** [mackworth/cTiVo#456]
<img width="449" alt="Screen Shot 2021-03-16 at 10 54 50 AM" src="https://user-images.githubusercontent.com/80771786/111330954-cbcd6380-8646-11eb-86d6-2ae7c5e76bf6.png">

I just started getting this pop-up recently with cTiVo, I have no idea what it is trying to access. Any idea?

**Comment by mackworth** [comment]
There's a point where cTiVo creates a temporary keychain to get access to the TiVo certificate. It then deletes it, but I've seen cases where it doesn't actually go away.

When you get this prompt, you can confirm this is the problem, as the password is the highly secure `password`.

If you go to ~/Library/Keychains, you should see a folder with that UUID (3BD...). Just delete this and you should be good. Let me know if that works.

**Comment by dcborn61** [comment]
I keep getting the pop-up a couple of times a day. I have entered the
highly secret password but it does not seem to stop the pop-up requesting
it.

I also tried deleting the keychain UUID, that also hasn't stopped it.

**Comment by mackworth** [comment]
So, "password" works, it goes away, but then comes back again soon?  
And is it during the same session, or do you quit the app in between (and if the latter, is it every time you restart?)

**Comment by dcborn61** [comment]
Yes, it seems to take “password” but comes back without me ever quitting out of the app.

**Comment by rqchin** [comment]
I'm seeing this happen also, but oddly, it just started this week. Maybe as a result of a Mac OS update? I'm on 12.6 on a MacBook Pro 16" M1 Pro cpu. Mine is looking for this UUID: "85F894B4-6B9D-438F-B877-0991EE9A7FED". It will happen in the same session, when I quite cTivo, or even after a complete shutdown of the Mac, however, when it happens is very random. It's not like it happens during encoding for every show. It might not happen for 50 shows and then suddenly it pops up. I have a log from right after it happened, but I'm not sure if that really helps.

![cTivo Keychain request 2022-09-30 at 00 27 28@2x](https://user-images.githubusercontent.com/33967440/193191237-49d3abd7-8ba3-476b-bae9-39ddccf64666.jpg)
[com.cTiVo.cTiVo 2022-09-29--02-18-52-785.log](https://github.com/mackworth/cTiVo/files/9680777/com.cTiVo.cTiVo.2022-09-29--02-18-52-785.log)

**Comment by mackworth** [comment]
Sorry, this issue drifted down the list and I missed it. If anyone is still having this problem (and cares), please let me know.

**Comment by rqchin** [comment]
It was happening for a while but it seemed to stop in October or November of 2022.

**Comment by mackworth** [comment]
Okay, I'll close for now.  For anyone who hits this, let me know, but in addition to looking for that temporary file, you might check in Keychain Access to see if there's a spurious entry there for your TiVo (probably not tivo.com entries, nor the CA entries)
