### ISSUE TITLE
cTiVo keeps losing connection

### ISSUE THREAD

**Issue by coach-jt** [mackworth/cTiVo#457]
I was able to download several shows in the last month, and now I have issues with all my shows recently.  I keep getting.
Code=-1001 "The request timed out." after this message is posted:
[MTTiVoManager netServiceBrowser:didRemoveService:moreComing:]@2005>Service disappeared: Family Room

I have made the following troubleshooting attempts:
- Uninstalled and Installed cTiVo
- Disabled AV Software
- Rebooted TiVo, Router and Mac (several times)

Any thoughts/suggestions would be great.

**Comment by mackworth** [comment]
Sorry for delay.  Not much other suggestions.  Have you tried downloading it in the browser to see if it works there?  (the log will give you the URL, and then use "tivo" as user and your MAK as the password.).

That message suggests a network problem of some sort. The MacOS is reporting that the Bonjour (aka mDNS) discovery process has reported that your TiVo has dropped off the network.  Is it hardwired or WifI?  Could something be interfering with it?  Bad cable?

Does the log show it coming and going all the time, or just during download?    Does it occur at a specific time into the download, or random intervals?

Although that's not the relevant error numbers, are you certain that the AV software is not running (TiVo uses a self-generated SSL certificate, which means it needs to be whitelisted in almost every AV system)?

**Comment by coach-jt** [comment]
Thank you for getting back to me.  I thought I had everything disabled with the AV, but there was 1 additional toggle to turn off.  Everything worked great this time!  Thanks for the support on this.

**Comment by mackworth** [comment]
Oh, that’s good to hear. Can you post a log with the numbers, as I may need to add a case for the AV check

**Comment by mackworth** [comment]
And did it fail within a few seconds of start?

**Comment by coach-jt** [comment]
The original failure was about 2-3 mins in.
Once the Norton AV was disabled (completely) everything worked great.  I only have the success log from today, is that what you are looking for, or from a previous failed attempt
