### ISSUE TITLE
Can't deliver 1080 res. from TiVo 1080 source

### ISSUE THREAD

**Issue by iXod** [mackworth/cTiVo#458]
Never mind...

**Comment by iXod** [comment]
Original is not 1080. I missed the HD broadcast version instead recorded the SD version.

**Comment by mackworth** [comment]
Correct; the 1080p won’t upscale the video

**Comment by iXod** [comment]
Hugh,
Thank you for your reply.

It would be helpful if cTiVo would alert the user that the source video is equal to or less than the requested encode resolution.

At the very least, refuse to upscale. It’s a waste of time otherwise.

Thanks,
Dave

**Comment by mackworth** [comment]
cTiVo does know about SD v HD channels, so you can specify "HD-only" in your Subscription. (You'll need to Ctrl-click on the title bar of your Subscription table to see the HD Only column.)

If it's an lower-res video on an HD channel (e.g. 720i on a 1080i), it doesn't really know about that, only ffmpeg once it starts processing the video.
