### ISSUE TITLE
closed captions in transcoding

### ISSUE THREAD

**Issue by petersbar** [mackworth/cTiVo#461]
I am sure this is not an "issue" but user error. my recording on tivo has no captions but when transcoded to the mac using cTivo, it has them.

the only option I saw was to "export captions" which was checked off. please help this user :)

**Comment by mackworth** [comment]
First, even if your TiVo isn't showing captions, the show apparently has them; cTiVo can't create them. 

More surprising would be if it's running the caption task, even when export captions is off.  I note that there are several places to control that, at the application level, the subscription level, and the individual download, so check that the Subtitle checkbox is off in the Download Queue (middle table in main window). If Subtitle column is not visible, you may have to turn on this column by control-clicking in the header of the table.

If it is turned off there and you're getting captions in the downloaded file, then go to Preferences, set DebugLevel to Major and download another show. When complete, go to Help>Show logs in Finder. Then Control-Click on the log folder, choose Compress. Then post that compressed file as an attachment to this issue on GitHub's website (don't use the Reply to email, as it deletes attachments). That will enable me to see what's going on with your system.

**Comment by petersbar** [comment]
Thanks so much for the lengthy informative answer I will give it a try when
I get back home all the best

**Comment by petersbar** [comment]
subtitles was off. I set log level to major (in preferences>general) and
will download again. stay tuned.

**Comment by petersbar** [comment]
Apologies. After further looking this was setting on a my tv using the plex
video player. Nothing to do w ctivo. Sorry!

**Comment by mackworth** [comment]
Good to hear.
