### ISSUE TITLE
File downloads but doesn't encode

### ISSUE THREAD

**Issue by rqchin** [mackworth/cTiVo#462]
I just had a recording download but then not encode (I think). At first, I thought it was just waiting for skip data, but it never went further. Is there anything I can do?

Rick
[TivoLogs_rqc.zip](https://github.com/mackworth/cTiVo/files/6904179/TivoLogs_rqc.zip)
![download_jeopardy](https://user-images.githubusercontent.com/33967440/127578611-a2862d5a-b36f-461b-b6be-10a1ff30287d.jpg)

**Comment by mackworth** [comment]
So, you've got two unusual things happening with that download.  
From the logs
```
2021-07-28 20:04:04:222 -[NSString(Helpers) setXAttr:toValue:]@175>XAttr error 2 for setting com.ctivo.filecomplete to 433250 for file /Volumes/Elements 12TB/zctivotemp/bufferJeopardy! - S37E178 - LeVar Burton.mpg
2021-07-28 21:07:23:057 -[MTAppDelegate launchPseudoEvent]@444>Looks like cTiVo was frozen out for 34 seconds
```
The first one is an OS error while trying to mark the file as complete.  That could indicate your system needs to be rebooted, or that you're having hardware trouble with the drive itself.  Secondly, your system froze up for 30 seconds a couple minutes later. So I'd first reboot, then maybe run a disk test. If that's ok, just try the download again.

I note also that you're doing a lot of retries for Transport v Program. Did you configure your system to force PS on certain channels?  It seems to try PS every time and after failing, then doing TS and succeeding.

**Comment by rqchin** [comment]
I restarted and ran Disk Utility on both the boot disk and the target disk; both came back fine. (I definitely think it needed a restart though - not sure why but I did update to Big Sur 11.5.1 recently.)

I tried downloading it again and it did the same thing - no encoding. Could it be a naming conflict?

Also, I think the Channels/Transport settings are all default. Do I need to change something there? I thought it automatically detected the settings that are necessary for each channel.
[com.cTiVo.cTiVo 2021-07-30--13-54-47-061.log.zip](https://github.com/mackworth/cTiVo/files/6910004/com.cTiVo.cTiVo.2021-07-30--13-54-47-061.log.zip)
![transport screen](https://user-images.githubusercontent.com/33967440/127711271-b6e9e564-c0f9-495b-9d01-f1b3acdc3b5a.jpg)

**Comment by mackworth** [comment]
Okay, doing some housecleaning for upcoming beta,  and realized I missed your response here.  In general, it does auto detect, but you can force it.  So BBCAM is being forced to PS in that diagram.  

Otherwise, let me know if you're still having an issue here.
