### ISSUE TITLE
Downloading recordings after changing from Cable to OTS.

### ISSUE THREAD

**Issue by pkleeberg** [mackworth/cTiVo#463]
I have just cut the cord and I switched my TiVo series 3 (Hearth Room AKA OTA TiVo) from recording shows from the cable company to over the air. After resetting the TiVo to receive only over the air and gathering channel information, I am able to see the recordings on the TiVo but I cannot download them. The newer shows appear on the OTA TiVo in the TiVo column but it appears I am unable to download them. 

Looking at the TiVo itself it shows all the pre and post conversion shows.

I what do I need to do to resolve this?
![Screen Shot 2021-08-05 at 3 15 42 PM](https://user-images.githubusercontent.com/76737081/128415536-21f88ff1-e99a-40f1-919f-333a417c6172.png)

**Comment by mackworth** [comment]
Sorry, missed this entirely I'd need to have access to your log to figure out it (Help>Show Logs in Finder; Right-click to compress and then come to GitHub to post the resulting Zip file).

**Comment by mackworth** [comment]
I take it this got resolved. If not let me know; you may need to disable the older TiVo name to get it to link properly. Again, my apologies for the delay in seeing this question.

**Comment by pkleeberg** [comment]
Sadly, it got resolved in a way that I did not expect.  The new TiVo no longer supports exporting to a computer.  One can only export, in my instance, to an iPhone or iPad via an app AND it will only download one file at a time AND only when the app is open.  Dreadful.  Had I known this I never would have purchased the new device and continued to use my TiVo HD which has both cable and OTA and worked just great.

**Comment by mackworth** [comment]
I assume you heard that from TiVo support. I don't think it's true. There was a problem with the TiVo EDGE when it came out, but that was resolved. If you want to try and get it running, happy to help. We would start with your running cTiVo, and then post an updated screenshot (like the one above) and a screenshot of your Edit>TiVos screen and your log (Help>Show Logs in Finder; Right-click to compress and then come to GitHub to post the files)

**Comment by pkleeberg** [comment]
I was distracted by other issues and after talking to support, was left with no hope.

I am a bit embarrassed.  Your last instruction "Edit>TiVos" did it.  Silly me.  My call to support was fruitless:  They said it was no longer possible.  They told me to use the iOS app but I had found that worthless because the download stops as soon as the screen locks.

Since the GameRoom TiVo is cable only, and I have cut my cable, my process was to use the GameRoom TiVo to pull from the edge and then cTiVo would pull it from the Edge.  A time consuming process.  

Thanks so much for getting back to me.  Now my cTiVi slave computer is downloading 31 hour of video.  That should keep it busy for a while....

**Comment by mackworth** [comment]
Never got around to closing this one, so... Glad it's working...
