### ISSUE TITLE
Downloads begins encoding then fails

### ISSUE THREAD

**Issue by Dial430** [mackworth/cTiVo#464]
[com.cTiVo.cTiVo 2021-10-11--00-23-10-010.log](https://github.com/mackworth/cTiVo/files/7322456/com.cTiVo.cTiVo.2021-10-11--00-23-10-010.log)

**Comment by dballenger** [comment]
I think I'm seeing something similar to this on Big Sur (I was still running Mojave until a few weeks ago when I noticed this behavior), the error file for encoding looks like: https://gist.github.com/dballenger/7bc210481a5055cb0cf3e7fcaefa6d67

**Comment by mackworth** [comment]
@dballenger that looks like a different problem.  Rather than a failure of encoding, that's a failure during launch of encoding. It says "    At least one output file must be specified". Which Format are you using, and if not a built-in one, can you post a screen shot of  it (Edit>Formats>YourFormat)

**Comment by mackworth** [comment]
BTW, @Dial430 The failure you indicated is similar to others I've seen where the download is corrupted, and I have no fix for. One of these days, I hope to try a workaround I've read about that purposefully slows the download, which MAY avoid some problem in TiVo's encoding/encryption during download.

**Comment by mackworth** [comment]
Let me know if you're still having an issue. I haven't been able to replicate this problem, and the easiest test might be to run PyTiVo Desktop to see if their algorithm fixes your problem

**Comment by Dial430** [comment]
Hi Hugh,
I am following up on your previous offer to help.  I have been using Tivo, successfully for a long time.  That said, every so often, cTivo will fail to encode a program. Multiple attempts to download but fails to encode, other times it works well, no issues.  I have attached my recent logs.  Today, I had another fail, I was able to download the file, in .ts mode, the file is 9 GB. For some reason, cTivo is unable to encode the file?  I tried PyTivo but could access my Tivo, see the file and try to download but the program would not download the file??

Any guidance you can provide would be appreciated.
Regard,
Fred Dial

**Comment by mackworth** [comment]
Unfortunately, GitHub strips off attachments from emails, so you need to go to the website to post the log.  From your description, it’s probably a glitchy video, so not much I can do. Try using handbrake instead of the Default ffmpeg encoders.
