### ISSUE TITLE
ffmpeg encoding fails with built in 1080p format

### ISSUE THREAD

**Issue by dballenger** [mackworth/cTiVo#465]
I think I'm seeing something similar to this on Big Sur (I was still running Mojave until a few weeks ago when I noticed this behavior), the error file for encoding looks like: https://gist.github.com/dballenger/7bc210481a5055cb0cf3e7fcaefa6d67

> @dballenger that looks like a different problem.  Rather than a failure of encoding, that's a failure during launch of encoding. It says "    At least one output file must be specified". Which Format are you using, and if not a built-in one, can you post a screen shot of  it (Edit>Formats>YourFormat)

_Originally posted by @mackworth in https://github.com/mackworth/cTiVo/issues/464#issuecomment-962696997_

Yeah, I just reviewed the cTivo side of the logs and it doesn't match up as well as I initially thought.  I'm using the built in 1080p format.

**Comment by dballenger** [comment]
<img width="582" alt="Screen Shot 2021-11-07 at 15 07 11" src="https://user-images.githubusercontent.com/889311/140665376-c0fbf3b3-52b8-4b0b-a3de-480ba049cf36.png">

**Comment by mackworth** [comment]
was there anything after that gist?  (e.g. "No video streams")?

**Comment by mackworth** [comment]
And which options were you using? (Subtitle? Cut/Mark? Is there SkipData?  Can you set it to Detail and run it again? (That should give the exact FFmpeg command line)

**Comment by mackworth** [comment]
That output looks like what cTiVo actually expects from ffmpeg when first launched. cTiVo uses ffmpeg to confirm that it's seeing an H.264 stream in a TS (or an MPEG2 stream in a PS) before continuing the download/encode. It purposefully doesn't give it an output stream, so that after it reports on input it exits.  So the rest of the log is needed to see what else is going on.

**Comment by dballenger** [comment]
I'm able to get some other shows off the tivo to encode so I'll try to see what differences/similarities I can find between the successes/failures and report back.  The previously provided log is for a show that seems to fail at the encoding (or at least after the "download" stage) every time.

**Comment by mackworth** [comment]
Can you post the full log?

**Comment by mackworth** [comment]
Any update? And/or can you post the log?

**Comment by dballenger** [comment]
Thanks for checking back in -- here's a log from some failed encodes today https://gist.github.com/dballenger/9e1d5296bb18c82dd311704053f55f9e

**Comment by mackworth** [comment]
So you're getting an error on a file copy, which is odd, and shouldn't matter from one show to the next.

Most obviously, can you check the disk space available on Data/qnap? cTiVo checks, but I don't see the result, so is it a network volume? If so, you might try using a local drive for the temp files.  If there's lots of space, you might also do a Disk utility check.

**Comment by mackworth** [comment]
closing for now.
