### ISSUE TITLE
cTiVo macOS Monterey Compatible? 

### ISSUE THREAD

**Issue by NCRobino** [mackworth/cTiVo#466]
Hello, has anyone tested cTiVo v 3.4.3 with the new macOS Monterey 12.0.1?

I don't want to kill the program, please advise if anyone has had success or failure with the new OS and this current version of the program.  

Thank you!

**Comment by mackworth** [comment]
So, I haven't personally updated but the (anonymous) analytics show hundreds of people using 12.0.1 already, with no reported problems. Let me know if you run into any minor compatibility issues.
