### ISSUE TITLE
No video on 1 or two of each season transferred issue

### ISSUE THREAD

**Issue by NCRobino** [mackworth/cTiVo#467]
Hello, So I have a few shows I subscribed to transfer and auto add to Apple TV Library.  All episodes 1-9 transferred and only 2 do not have video.  I deleted those files, reinitiated the transfer and encode... and all of these same episodes remain with no video, only audio.  Any advice?

**Comment by mackworth** [comment]
If you can set the debug log to Detail , rerun a show and post the log, that'll help me figure out what's wrong.  My guess is a corrupted source file, but happy to look.

**Comment by NCRobino** [comment]
Gotcha, I’ll give it another go for ya then as soon as I can 

Rob

**Comment by NCRobino** [comment]
How do I change to Detail?

**Comment by NCRobino** [comment]
Nevermind found it, processing now.

**Comment by mackworth** [comment]
Be sure to post the log on the site; email attachments are stripped off.

**Comment by NCRobino** [comment]
[com.cTiVo.cTiVo 2021-11-18--20-01-10-272.log](https://github.com/mackworth/cTiVo/files/7566593/com.cTiVo.cTiVo.2021-11-18--20-01-10-272.log)

**Comment by NCRobino** [comment]
There you go, let me know if that didn't work as you need it.  Attempted again after upgrading Mac to Monterey, good news, that does indeed not affect cTiVo's performance... but it also didn't fix this issue, those two episodes are fine on Tivo, but remain black, no video, audio only once transcoded and transferred to Apple TV Library.  Also checking files via VLC, they play the same there. Thanks for any help

**Comment by NCRobino** [comment]
Hi again, any insight to the logs I posted?  

Rob

**Comment by mackworth** [comment]
Sorry, I've been knee deep in compiler settings and build scripts.

So, that sounds like the video is glitchy coming from TiVo, which is a known problem. I would suggest trying again with another encoder. Handbrake (HB 1080p for instance), will probably show the same symptom, but is worth trying. The other scenario is to just download the file w/o encoding using Decrypt MP4, which will just copy the MP4 bits from TiVo into a file. If that file is also corrupted, there's nothing to be done.

**Comment by NCRobino** [comment]
Gotcha, how do I get the unencoded .tivo file to try that with handbrake?

In my past experience I couldn’t get handbrake to convert from .tivo to mp4, is that possible?

**Comment by mackworth** [comment]
Sorry, I mean just use HB encoder inside of cTiVo.  Go to Edit>Edit Formats. Select HB 1080p from the pulldown, and enable "Show in user interface", then Save, Done, and select HB1080p from Format pulldown in upper right. Yes, it saves to MP4. 

HB can't handle raw .tivo files as they are encrypted.  If you really do want to use HB GUI, then use Decrypted TiVo Show format, which doesn't change the file at all beyond decrypting it. You should then be able to load that file (.ts or .mpg) into Handbrake's program.

**Comment by NCRobino** [comment]
Got it, working it now, thanks for the detailed info!  BTW, is there a place I can donate to your efforts?  I am very thankful for this program to save some programs I’ve had on there for years that I needed off but the old TiVo program I had was long dead from TiVo.

So thank you!

**Comment by mackworth** [comment]
Nope, thanks. Just a hobby, at least until TiVo DVRs are "dead from TiVo"

**Comment by NCRobino** [comment]
Well a huge THANK YOU!!!

Rob

**Comment by mackworth** [comment]
Another thing to try: use the TiVo UI to pull the shows with glitches to a different TiVo, and try cTiVo from there. Let me know if any of these things actually work.

**Comment by NCRobino** [comment]
Will do.  I only have one TiVo, the other 3 are minis so I can’t move them sadly.  

I’ll keep ya posted 

Rob

**Comment by NCRobino** [comment]
Hey Hugh, 

All failed. Same result, audio no video.  Tried default, 1080p and HB 1080p, source is 720p.  

Any other steps I can take that you can think of?  I’ll try again on Friday after the holiday. 

Happy Thanksgiving!

**Comment by mackworth** [comment]
So, in my beta testing, I've found I have a file that does the same thing. I even downloaded it with no re-encoding (Decrypted  TiVo Show Format) which can't be played with Quicktime player or TV, but can be with VLC.  It also was corrupted.

Only remaining suggestion I have is to try [PyTiVo Desktop](https://www.pytivodesktop.com). It has an algorithm that retries slower and slower on failures to try and recover bad files. I tried it and it didn't succeed, but your mileage may vary.

**Comment by NCRobino** [comment]
Gotcha, so weird that it plays fine on the tivo itself, yet is somehow corrupted.  

I’ll give this link a try, stay tuned

**Comment by NCRobino** [comment]
Hmmmm.. well I cannot get this program to find my tivos for some reason, so I am kind of stuck here for now… any suggestions are welcome to troubleshoot, but I’ll ask the maker for that program. 

Thx again

**Comment by NCRobino** [comment]
Finally got the py program working.  Trying it now, wish me luck , I’ll let you know how it goes

**Comment by mackworth** [comment]
any progress? Did pyTivo's algorithm help?

**Comment by NCRobino** [comment]
Nope.  Nothing ever helped sadly, the two files play on TiVo but not on the transfers.  I kept the shows in hopes of figuring it out so if ya have any other idea let me know!

Rob

**Comment by mackworth** [comment]
So, closing this as TiVo's never gonna fix it...

**Comment by NCRobino** [comment]
Such a bummer.  Thanks for letting me know. RobOn Mar 9, 2023, at 5:10 PM, Hugh Mackworth ***@***.***> wrote:﻿
So, closing this as TiVo's never gonna fix it...
