### ISSUE TITLE
Is Apple Silicon support still being worked on?

### ISSUE THREAD

**Issue by larsenv** [mackworth/cTiVo#468]
Is cTiVo going to be built for Apple Silicon?

I know there's already an issue about this, but I never get a response via email or GitHub, and I haven't heard any information about it.

cTiVo is the best TiVo app for Mac.

**Comment by mackworth** [comment]
It is. cTiVo compilation is automatic, but building the subprograms has been the issue. ccextractor and comskip were pretty easy, Handbrake provides their CLI, but ffmpeg was the delay. Building it in the straightforward way compiles easily, but is no faster than Intel emulated version. Building it in a way that incorporates the NEON changes, and is still built on dynamic libraries that are also used in comskip while still supporting older MacOS on Intel...has been a royal pain.  I'm close to a beta version through now; AFAIK, just testing remains.

**Comment by mackworth** [comment]
Closed to keep this on issue #443
