### ISSUE TITLE
Moving settings to a new Mac

### ISSUE THREAD

**Issue by rqchin** [mackworth/cTiVo#471]
Is there a way to move my existing cTivo settings to a new Mac? I'm not using the Migration Assistant or restoring from a backup of my previous Mac but I'd like to keep my settings, especially my Subscribed Shows.

Rick

**Comment by mackworth** [comment]
Sure. If you just copy your Prefs file over, you should be fine. In the Finder, type Cmd-G `~/Library/Preferences/`and then look for `com.cTiVo.cTiVo.plist` Copy that file to the same place on your new Mac, and start up cTiVo. 

Let me know if you have any issues.
