### ISSUE TITLE
Encoded file is distorted

### ISSUE THREAD

**Issue by pkleeberg** [mackworth/cTiVo#473]
After switching to OTA. TiVo is able to record programs from public television and there are few instances of digital decay however the same program after encoding has terrible decay in both audio and video.  Is there some setting in cTiVo that will allow me to remedy that?  I could not find it in the documentation.

Paul

**Comment by mackworth** [comment]
Sorry, just noticed I missed this one entirely (from a year ago). My apologies. Nonetheless, unfortunately, this is a known issue and one we cannot control as it seems TiVo's encryption garbles the file under certain conditions...  see also #467 and #460
