### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by cyxodus** [mackworth/cTiVo#474]
I would like for the following features to be added to cTiVo:

1) An automated action that allows for the renaming of a file.
       a) add text to the beginning or ending of a video.
       b) delete text at the beginning or ending of a video
       c) add a date stamp to the end of a video.

2) Allow each subscription to have a different destination folder instead of just one for everything.

**Comment by mackworth** [comment]
If I'm understanding correctly, these are available already, although the first would require some programming on your part.

The first request is a post-processing hook currently used for Pushover notifications, although your note prompted me to do some long-needed [documentation](https://github.com/mackworth/cTiVo/wiki/Advanced-Topics#post-processing-hook) on how it works. I would note that if you rename the video file itself during that script, then I think cTiVo will lose awareness of it, so will not be able to launch the video from the cTiVo UI, but manipulating the video and leaving it in place should be fine. You may need to copy the extended meta-attributes from the old file to the new one.

For the simple version of your second request, just go to Preferences>Advanced, pull down Filename Templates and select cTiVo Folders (or Plex folders if you're using that system). You can then modify that as you see fit; [documentation here](https://github.com/mackworth/cTiVo/wiki/Advanced-Topics#filename-templates)

Let me know if I'm misunderstanding and if that meets your needs.

**Comment by mackworth** [comment]
I take it those worked for you (or you've moved on!)
