### ISSUE TITLE
CTivo hanging on start

### ISSUE THREAD

**Issue by clclementsj** [mackworth/cTiVo#475]
I force quit cTivo after a freeze on my Intel Mac Mini running cTivo v3.5. Now, every time I start the app it just beachballs at updating TiVos with no content in the upper panel.

I’ve performed the following, with no resolution:
- Deleted and reinstalled v3.5

- Dragged to the trash, emptied trash, and reinstalled v3.5

- Deleted, purged all files in /Library and ~/Library containing “ctivo” and reinstalled v3.5

- Deleted, purged all files in /Library and ~/Library containing “ctivo” and reinstalled older v3.4

- Performed each of the steps above, but with a reboot after the deinstallation, before reinstallation

Any ideas as to how to resolve this or start again with an actual clean deinstall / reinstall?

**Comment by mackworth** [comment]
To be precise, by beach-balling, do you mean the rainbow-colored, "spinning wheel of death" cursor, or the grey spinning circle indicating that it's not finding any TiVos? 

If the latter, have you tried rebooting the TiVo, and/or using [DNS Discovery](https://apps.apple.com/us/app/discovery-dns-sd-browser/id1381004916?mt=12) to find out if your Mac can "see" your TiVo? (actually those two steps would be good anyways)

And I take it that it worked previously? (3.4 and/or 3.5?)

**Comment by clclementsj** [comment]
LOL

It’s the former; the rainbow colored spinning wheel of death. The menus all display that icon and there’s no way to stop the app other than Force Quit. I did allow it to run for a long time, at which time the OS complained that all memory had been exhausted.

I installed cTivo on two other Macs and it’s running fine there, accessing the same TiVo Bolt as the problem child, and downloading/encoding content on both. So, the TiVo itself seems to be fine.

Yes, it’s been working perfectly up until now, which is the frustrating part. I just wish I could find out what’s being left behind after the uninstall.

--
Charles Clements

**Comment by mackworth** [comment]
Any luck?

**Comment by mackworth** [comment]
No problem; glad it worked!

So that's a sign that the Preferences file was never "really" gone. (That's where the MAK is stored.) Not surprising, as MacOS tries really hard to keep it around through caching. For anyone reading the thread in the future, one trick is to type "defaults delete com.ctivo.ctivo" in Terminal, which should erase all preferences. Alternatively one can confirm deletion with "defaults read com.ctivo.ctivo", which will show all the keys available.
