### ISSUE TITLE
Shows failing after downloading.

### ISSUE THREAD

**Issue by Colby3122** [mackworth/cTiVo#478]

**Comment by mackworth** [comment]
Can you post your log?  (Help>show logs in Finder, then right-click to compress the files and post the resulting .zip file here)

**Comment by mackworth** [comment]
Sure. In cTiVo, use the "Show Logs in Finder" command in cTiVo's Help menu. Then Cmd-Click on the cTiVo directory the Finder will have selected. Use the Compress command in the popup menu to compress the files. That should result in a `ctivo.zip` file. Then come back to this issue on gitHub, and at the bottom, drag the file to the "Attach files by ..." bar then post the comment.  (Do not reply to the. email as GitHub strips attachments.)

**Comment by Colby3122** [comment]
[cTiVo.zip](https://github.com/mackworth/cTiVo/files/8653829/cTiVo.zip)

**Comment by Colby3122** [comment]
Tivo transfers shows all the way then just as it goes to encode the show it fails, I tried this on my Roamio and my older series two Tivo several shows. here is the log in files you requested, please respond. er01@roadrunner.com
Thank you!
[cTiVo.zip](https://github.com/mackworth/cTiVo/files/8654654/cTiVo.zip)

**Comment by Colby3122** [comment]
I still can't encode shows, they download but when then start to encode they always fail. I have 4 tiros, two Roamios a Bolt and a series two. I do not seem to be able to download from any of them anymore. The HD's are all on MOCA. up until 2 days ago everything worked great for at least 8 years, nothing has changed except a new
[cTiVo.zip](https://github.com/mackworth/cTiVo/files/8664346/cTiVo.zip)
software update to 352(1139
[cTiVo.zip](https://github.com/mackworth/cTiVo/files/8664343/cTiVo.zip)
)

**Comment by mackworth** [comment]
So, don't know why yet, but the Format "HB Tiny" is broken. Try using another Format and you should be good.

**Comment by mackworth** [comment]
To be clearer, use the pulldown control in upper right (which probably says `HB Tiny` now), and change it to another format. e.g. Default.  If you do want lower Resolution, you could use Standard Def

**Comment by Colby3122** [comment]
Thank you, standard def works for now, I use it for my iPod Classic. Takes a little longer to encode the Hd but it is fine for the series 2 Tivo, thanks again!


On May 10, 2022, at 4:31 PM, Hugh Mackworth ***@***.***> wrote:


To be clearer, use the pulldown control in upper right (which probably says HB Tiny now), and change it to another format. e.g. Default. If you do want lower Resolution, you could use Standard Def

**Comment by mackworth** [comment]
Good to hear Series 2 still works. I'm kinda surprised.  you could try using the "Not Recommended" Format `iPod`. You'll have to enable it in `Edit Format>iPod>Show In User Interface` Give it a try, but if it fails, go back to Standard Def.
