### ISSUE TITLE
Downloads fail before encoding begins!

### ISSUE THREAD

**Issue by Colby3122** [mackworth/cTiVo#479]
I still can't complete downloads, I own 4 Tivo's, 2 Roamio's a Bolt and a series 2. the shows on all 4 download then when they start to encode they fail. this began Sunday. prior to that everything worked great for at least ten years. I have the latest software version (3.5.2 (1139)) Can anyone help me! Here are the logs you asked for
[cTiVo.zip](https://github.com/mackworth/cTiVo/files/8664412/cTiVo.zip)

**Comment by mackworth** [comment]
Redundant issue with #478
