### ISSUE TITLE
3.5.2 Universal RPC Cert Warning?

### ISSUE THREAD

**Issue by vidsky2** [mackworth/cTiVo#480]
Very happy to see that 3.5.2 is now available as a stable update but I'm a little confused about the warning that's included in the release notes:

**Warning**: TiVo RPC certificate will expire December 2022

Is this saying that cTiVo will stop working after December, that my current version (3.4.3) will stop working after December if I don't update, that a new certificate will be required, or that nothing will happen one way or the other?

I've tried hunting for information on the RPC certificate but am clearly out of my depth. If I'm not the only one, perhaps the warning could include clarification language; especially if it will be a common occurrence.

**Comment by mackworth** [comment]
Good question. Hopefully we’ll find a new certificate to be able to update cTiVo. If not (or you don’t update), the basic functionality of cTiVo would continue, but a number of features would fail. 

See [the main cTiVo page](https://github.com/mackworth/cTiVo), the features that are marked with a star (*) require the RPC connection and would not be available thereafter.

**Comment by mackworth** [comment]
ps I added a note to the README along the same line. Thanks for posting

**Comment by vidsky2** [comment]
Excellent, thanks for the explanation!

**Comment by mackworth** [comment]
And....we have the certificate, thanks to @lart2150's PR #482 , so we're good to go through 5/2024.
