### ISSUE TITLE
Encode fails with HDR10 shows

### ISSUE THREAD

**Issue by tannebil** [mackworth/cTiVo#483]
I'm seeing an occasional show where either I just get the audio or the encode fails outright. I dug a little deeper into one where I got audio only when try to do a Handbrake custom encode and a outright failure when I tried "Decrypt MP4". I was able to download the complete file via Safari but didn't try any subsequent processing on it. Just for fun, I made a copy of the "Decrypt MP4" format and turned off simultaneous encoding while downloading. Not surprisingly, it postponed the failure until it tried to encode it (2nd log)

[com.cTiVo.cTiVo 2022-05-17--11-01-10-110.log.zip](https://github.com/mackworth/cTiVo/files/8712524/com.cTiVo.cTiVo.2022-05-17--11-01-10-110.log.zip)
[com.cTiVo.cTiVo 2022-05-17--11-01-10-110 2.log.zip](https://github.com/mackworth/cTiVo/files/8712592/com.cTiVo.cTiVo.2022-05-17--11-01-10-110.2.log.zip)

**Comment by tannebil** [comment]
I've been doing more testing and everything I've found points to corruption in the file downloaded from TiVo even when downloaded through the TiVo web interface. Other postings indicate that is something outside the control of cTiVo. Time to throw in the towel and just accept that some percentage of shows are going to fail?

**Comment by mackworth** [comment]
That’s my impression. I think while encrypting/transmitting a file (maybe with with minor glitches in it), the TiVo is corrupting the file beyond readability.   

There was some discussion in the kmttg thread that slowing down the transmission might help, but I haven’t had a reproducible case on my system to try that out. 

You might try downloading with TiVo decrypt” instead. It doesn’t do any encoding. I note it’s failing immediately, so it might be corrupted in the header.

**Comment by tannebil** [comment]
Same problem with the .ts file with "Decrypted TiVo Show".

It may be a red herring but could a show having HDR10 be causing an issue? I don't ever recall seeing it until just now but the shows I've been using for testing are HDR10 according to MediaInfo (I didn't even think that HDR10 was available for Xfinity cable shows). I'm going to download all the recent shows using "Decrypted TiVo Show" and check them for a pattern.

**Comment by tannebil** [comment]
I checked 17 recent shows. All 11 shows that MediaInfo said were HDR10 failed and the 6 shows that were not HDR10 worked fine. With some series, it was the latest episode while with others, it was a prior episode with the latest not being HDR. That's all definitely suspicious. 

Maybe Xfinity or CBS/NBC are trialing something? I don't ever recall seeing anything supported HDR outside on 4K content.

I turned off HDR on the TiVo but it didn't change anything with already recorded shows. Several of these series have episodes next week so we will see how it goes with those series.

**Comment by mackworth** [comment]
Excellent detective-Ing. I look forward to seeing your further results. Can you post the mediainfo of one that failed v one that worked?

**Comment by tannebil** [comment]
[MediaInfo.txt](https://github.com/mackworth/cTiVo/files/8750383/MediaInfo.txt)

"The Debate" works fine while "The Recall" only plays audio.

**Comment by tannebil** [comment]
All the shows that had failed on previous episodes that had new episodes this week (6 out of 8 shows) encoded without a problem. My conclusion is that either somebody in the chain (program source, Xfinity, or TiVo) screwed up the shows with HDR10 info and stopped screwing it up (likely), or turning off HDR support on the TiVo fixed the the issue (less likely), and that we will never really know (99.9% likely)

**Comment by mackworth** [comment]
A bit of background…

https://www.tivocommunity.com/threads/tivo-edge-and-auto-hdr-question.573704/

Maybe try turning the option on again and see if it recurs? I’d love to know if I need to recommend turning it off.

**Comment by tannebil** [comment]
I'll give it a try but it may be months before I have any results. All the shows are either CBS or NBC network shows and I think all the seasons may have ended. None of them are in the current "to do" list.

**Comment by mackworth** [comment]
I'll close this for now, let me know if you see it again afterwards.
