### ISSUE TITLE
2.5.3-beta

### ISSUE THREAD

**Issue by techpro2004** [mackworth/cTiVo#486]
I see some reference to version 2.5.3 but I cant find it anywhere. it is not under releases and the built in updater says 2.5.2 is the latest. thanks.

**Comment by mackworth** [comment]
Assuming you mean 3.5.x, 3.5.3 is still officially in “pre-release”, just because I haven’t pushed the release button yet. No problems reported from the field though, so you should be good if you want to get it. It’s [here…. ](https://github.com/mackworth/cTiVo/releases/tag/3.5.3-beta)

**Comment by techpro2004** [comment]
Thanks. I just downloaded it.

**Comment by mackworth** [comment]
Great; let me know if you have any issues.
