### ISSUE TITLE
Remote Module 

### ISSUE THREAD

**Issue by tadgill** [mackworth/cTiVo#487]
I know it is not a big part of this software but I uses the remote fairly often - but one thing seems odd/off to me. 

30 Second Forward is mapped to -TAB- and it shows 10sec back is -⌘Tab-. 

My issue is that ⌘Tab is the app switcher. Can we do like Option+Tab or something?

**Comment by mackworth** [comment]
Thanks for writing in; nobody ever mentions the remote, so wasn’t sure if anyone is using it. 

Good point! Not at all clear why I didn’t catch then when trying all the buttons. Will change in next release.

**Comment by mackworth** [comment]
And (Finally!) the beta is released...
