### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tdlivings** [mackworth/cTiVo#492]
I guess this may sound odd, but do you recommend this new version for the apple silicon machines? I noticed it wasn't on the auto update delivery queue yet.

Thank you

**Comment by mackworth** [comment]
Yes. 

3.5.2 is the current auto update one. 3.5.3’s only difference is the new certificate ( and future update mechanism). So no real difference today, as the old cert is still good until December. I usually give it a few days between release and auto-update, but it’s about time to do that.

**Comment by tdlivings** [comment]
Yes, and I could help but notice the updated CLI, Thank You for that.

**Comment by mackworth** [comment]
Ah. That’s right! Have to do the release notes as well.

**Comment by mackworth** [comment]
Um...so, no. (I really shouldn't answer from my phone w/o checking these things. )

AFAIK, 3.5.3 does NOT have the newest CLI, v1.5.1; it still has 1.4.2. The reason being that 1.5.1 will not run on MacOS 10.11, and I wanted to bring that version up to speed with the new cert before upgrading the CLI in the NEXT release.

**Comment by tdlivings** [comment]
Yes, I saw slower encode speeds. But to be fair it was still 5 minutes not 30.
