### ISSUE TITLE
Open From File Instead of Tivo

### ISSUE THREAD

**Issue by M1078** [mackworth/cTiVo#502]
Hello,
I don't currently have a Tivo box connected but do have files that were previously downloaded from the box.  How can I direct to open those files rather than look for a Tivo box on the network?

**Comment by mackworth** [comment]
Unfortunately, cTiVo can't do that, as there's information it needs from the TiVo to do its thing. If you just want to view the files, [VLC](https://www.videolan.org) should let you watch them, and if you want to convert them to another format, [Handbrake](https://handbrake.fr) is probably your best choice.

**Comment by M1078** [comment]
Thanks for the quick reply!

**Comment by M1078** [comment]
Let me ask again with a little different spin.  The Tivo files I have are on a NAS that were written there by the Tivo box.  There was an option on Tivo to save files to an external device.  So the files were saved there and I could also playback any of them on the Tivo box.  Does that make any difference?  Since the NAS would allow the Tivo box to play the recorded shows could I point cTiVo to the NAS?

**Comment by mackworth** [comment]
Ah, I assumed you had decrypted files. 

If you want to decrypt then ( to view in VLC or convert w Handbrake, then I gave a short batch file to do that. See issue, #124

**Comment by M1078** [comment]
Mac OS wouldn't let me open the app.

**Comment by mackworth** [comment]
Note sure what you mean. If you mean the script, It’s run in Terminal. You’ll have to edit it to point to the directory with your TiVo files. Then save it as a .sh file, say `TiVo.sh`. Then you’ll need to mark it executable. `chmod -x TiVo.sh`. Then run it with `./TiVo.sh`

**Comment by mackworth** [comment]
did that work for you?

**Comment by M1078** [comment]
Hi Hugh,

I think it's a little too complicated for me right now.  Appreciate you 
following through.

Regards,
Jared
603-494-4337
