### ISSUE TITLE
Open File from NAS

### ISSUE THREAD

**Issue by M1078** [mackworth/cTiVo#503]
Let me ask again with a little different spin. The Tivo files I have are on a NAS that were written there by the Tivo box. There was an option on Tivo to save files to an external device. So the files were saved there and I could also playback any of them on the Tivo box. Does that make any difference? Since the NAS would allow the Tivo box to play the recorded shows could I point cTiVo to the NAS?

**Comment by mackworth** [comment]
Discussion in #502...
