### ISSUE TITLE
cTivo not responding I think I broke it

### ISSUE THREAD

**Issue by PCDOS-1dot1** [mackworth/cTiVo#506]
MacOS 13 on Mac Studio Max

Used cTivo 3.4.5 for a couple days and I love it .  I wanted to customize the download file name and location and I think I made an error in editing location or file name.
Now it hangs at startup while showing "Updating TiVo-OTA"
Activity Monitor reports "app not responding" in red
Tried multiple force-quits and restarts
Tried multiple app deletes, downloads and installs.
I can access the TiVo with online vivo in Safari
TiVo works normally.
I can access the TiVo with TiVo app on iPads.

Am reminded of the Mouse's Prayer "I don't want the cheese anymore, I just want out of this trap.
Can you help?
And many thanks for a great app.

Kind Regards,
Gary

**Comment by mackworth** [comment]
Yup, redoing preferences should fix it, let me know what happens!

From Issue #507:
> Looks like there may be a solution already posted.
> I will try the instruction in #475 and will let you know what happens.
> Hope this save you needless keystrokes

**Comment by PCDOS-1dot1** [comment]
Terminal command worked like a charm.
Everything is ok
Thanks
Gary
