### ISSUE TITLE
Can't delete shows from Tivo box using cTivo.

### ISSUE THREAD

**Issue by aofrailey** [mackworth/cTiVo#509]
The cTivo "Delete from Tivo" menu option is greyed, prohibiting the ability to delete shows from the Tivo box from my computer. This seemed to have happened recently.  I had not upgraded my operating system or my cTivo software between the time it worked until it did not.

**Comment by aofrailey** [comment]
I have also noticed a difference in the status icon. The icon show an exclamation point within a blue circle. I recall that previously the icon had an orange fill.

**Comment by mackworth** [comment]
Make sure you've got the latest version of cTiVo. A certificate expired early this month, and that would cause those problems.

**Comment by mackworth** [comment]
You can just use `Check For Updates...` in cTiVo's Apple menu.

3.5.3 is the latest; but if you're on MacOS prior to 10.12, you can use 3.4.4 or 3.4.5

**Comment by mackworth** [comment]
I take it that worked for you, but let me know otherwise...
