### ISSUE TITLE
scratch files not deleting

### ISSUE THREAD

**Issue by dapostman** [mackworth/cTiVo#510]
I'm fairly sure this is a SUE (Stupid User Issue); appreciate your forbearance and help.

I have a scratch directory where chive does all of its processing. For some reason, the temporary files are not getting deleted upon successful exit, so my drive is filling at a very fast clip.

Is there a setting I have tweaked wrong somewhere?

TIA!

**Comment by mackworth** [comment]
Could be.  See Settings>Advanced>Don't delete Temp files (for Debug only)

**Comment by dapostman** [comment]
Thought that might be it - but this is what that prefpane shows:

<img width="583" alt="image" src="https://user-images.githubusercontent.com/121366446/218175710-64a7e6d9-b092-471d-b63f-9c56b4bb1534.png">

**Comment by mackworth** [comment]
Well, that's unfortunate.  Can't think of any other easy reason. Let's see; a few diagnostic questions...
Assuming this wasn't true before, any thing changed recently?
Are all file types not being deleted? 
If you quit cTiVo and go back in, are the temp files deleted?
Shouldn't matter, but maybe not have a space in the scratch name?
Can you post the log to check if there's any errors being reported?
(`Help>Show logs in Finder`, then Cmd-Click on latest log and `Compress "com.ctivo....log"`, then post the resulting zip file (Note, you can't attach to an email).

**Comment by dapostman** [comment]
I ended up trashing all of the support/prefs in !/Library, and reconfiguring. works now; must have been a little something somewhere that snuck in.

jp

**Comment by mackworth** [comment]
When in doubt, blow it up!

Glad it worked; sorry for your trouble!
