### ISSUE TITLE
Downloading show repeats multiple times and then fails

### ISSUE THREAD

**Issue by TheApApp** [mackworth/cTiVo#513]
I have a show that keeps trying to download, it goes thru the process 3 or 4 times, changing from ready to downloading, goes from 0-100%, and then goes back to ready.  After about 4 times it comes back as Failed.  

I am running cTivo 3.5.3 (1147)

**Comment by mackworth** [comment]
My guess is that it is a damaged file, but happy to take a look. Can you post the logs (Help>show logs in finder; then  cmd-click compress, and post the resulting zip file. Note you can’t attach to an email)

**Comment by michaelrowe01** [comment]
[com.cTiVo.cTiVo 2023-03-05--01-19-53-180.log.zip](https://github.com/mackworth/cTiVo/files/10890560/com.cTiVo.cTiVo.2023-03-05--01-19-53-180.log.zip)
Thanks @mackworth

**Comment by mackworth** [comment]
So, is that the only show giving you problems? The log shows it failing instantly, which usually means either an incorrect MAK (in which case all shows would fail), or something's really wrong with it.  Try a download with Encrypted TiVo Show (you'll have to "Show in User Interface" in Edit Formats) and confirm that it can download more than 20% (you can then cancel it). If that works, turn Debug level to Detail and try a Decrypted TiVo Show without commercial cut or mark or captioning and then post that log.

**Comment by mackworth** [comment]
Actually, go ahead and the the Encrypted download finish.  Then if you can post it somewhere (Github won't take a gigabyte file) and give me a link, I'd like to try an experiment with it.

**Comment by TheApApp** [comment]
Here's a video of trying the download... And when I check my ~/Movies/TiVoShows directory there is no file.
https://user-images.githubusercontent.com/2049209/223772822-5a15f6e1-8fdf-4d75-85ab-3017c317b82a.mov

**Comment by mackworth** [comment]
Sorry, I forget sometimes to be specific in these more unusual paths.

To enable Encrypted TiVo Show, go to `Edit>Edit Formats`, then use the pulldown at the top (to the right of Formats to select `Encrypted TiVo Show` (greyed-out). Then click on `Show in User Interface`.  Then hit `Save` and `Done`.

Now Pause the Queue (Cmd-U), and either drag the misbehaving show to the Download Queue (or if it's already there, then Cntrl-Click Reschedule it. Then use the Format column pull down and select `Encrypted TiVo Show`. Cut Mark Subtitle should all be turned off.  Then unpause the queue (Cmd-U) and it should proceed.

(Alternatively you could just change the Format in the upper right to Encrypted TiVO Show, then drag the show into the Queue, and then change the Format back, so future shows use the Default Format.

**Comment by TheApApp** [comment]
Let me know where I can send you a link for you to download the file.. it is 1.12 GB in size....

**Comment by TheApApp** [comment]
try this link and let me know when I can disable it - https://www.dropbox.com/s/t33sm8tq0etz1mo/Great%20Performances-The%20Magic%20of%20Spirituals.tivo?dl=0

**Comment by mackworth** [comment]
Got it.  To play with it, I would need your MAK. If that's ok with you, then you can email it to my AOL account (same user name: mackworth).

**Comment by mackworth** [comment]
Good news, I was at least able to decrypt it. I’ll do a smaller version tomorrow and post it. --Hugh ***@***.***@mackworth(503) 816-9711On Mar 8, 2023, at 5:32 PM, Michael Rowe ***@***.***> wrote:﻿
try this link and let me know when I can disable it - https://www.dropbox.com/s/t33sm8tq0etz1mo/Great%20Performances-The%20Magic%20of%20Spirituals.tivo?dl=0

**Comment by michaelrowe01** [comment]
Are there specific setting I need to use to get it to work on my machine? I am able to process other files?
