### ISSUE TITLE
3.6 Release; any issues...

### ISSUE THREAD

**Issue by mackworth** [mackworth/cTiVo#514]

**Comment by tdlivings** [comment]
Installed fine, all settings passed through. 1:04:00 HD show downloaded in 00:1:45, encoded with custom Handbrake profile (H.265) using videotoolbox hardware encode 4 minutes. These are the numbers for intel though. I haven't tried it on a Mac Studio ultra yet.

**Comment by tdlivings** [comment]
I have been using a moded cTivo 3.5 with 1.6.1 handbrake CLI on a Mac Studio ultra and a pro max units and both have the same results.

**Comment by mackworth** [comment]
Thanks. good to hear. By same result, I assume you mean it's working well? How's the quality on both Intel and Arm?

**Comment by tdlivings** [comment]
Yes, consistent results across both platforms.

**Comment by mortax** [comment]
not a big issue but i'm seeing an alignment issue for the [+] and [-] buttons:

<img width="538" alt="image" src="https://github.com/mackworth/cTiVo/assets/788303/0ff1f44b-86e9-4f28-b0e8-83143eb3466b">

**Comment by mackworth** [comment]
[Final 3.6 Release](https://github.com/mackworth/cTiVo/releases/tag/3.6.0) is posted, and it includes that alignment fix.

FYI, that has been there forever, and oddly, standard Mac buttons are actually defined to align their text on the top edge with no vertical center alignment available. Nonetheless, now that you have pointed it out, I couldn't help but to fix it.

**Comment by mackworth** [comment]
final release of 3.6.1
