### ISSUE TITLE
Migrating to a new Mac

### ISSUE THREAD

**Issue by mosleyh** [mackworth/cTiVo#515]
I'm upgrading my Mac mini media server and would like to be able to migrate my cTivo config (mainly the subscriptions) to the new computer. Is that possible? Thanks!

**Comment by mackworth** [comment]
Sure thing. Everything relevant is in the file ~/Library/Preferences/com.ctivo.ctivo.plist (There’s some caches and other things that will be recreated on your new server)

If you use Apple’s migration, then it should come over automatically. 

Let me know if you have any problems.
