### ISSUE TITLE
subtitles are scrambled/jumbled

### ISSUE THREAD

**Issue by dapostman** [mackworth/cTiVo#516]
I've done some searching, and see that this issue was discussed a few years ago, with some comments at the time that CCExtractor was the issue.

I'm getting this on every show, and have confirmed via the logs that whatever is being extracted is different that what I get when I watch it natively on my TiVo.

I'm wondering if there is a fix.

thanks in advance!

ctivo ver 3.5.3 (1147)
macOS 13.3.1(a)
mac mini m1

**Comment by mackworth** [comment]
Unfortunately, you are correct. It slides two characters back four places, making it really hard to read. They've never fixed the problem and nothing we can do at our level. See [here](https://github.com/CCExtractor/ccextractor/issues/1109)  and [here](https://github.com/CCExtractor/ccextractor/issues/136)

**Comment by dapostman** [comment]
Thanks for this. On May 14, 2023, at 10:12 PM, Hugh Mackworth ***@***.***> wrote:﻿
Unfortunately, you are correct. It slides two characters back four places, making it really hard to read. They've never fixed the problem and nothing we can do at our level. See here  and here
