### ISSUE TITLE
repeated download failures when MacBook Pro is sleeping

### ISSUE THREAD

**Issue by johnsonea** [mackworth/cTiVo#518]
MacBookPro16,1 (2019 core i9), Ventura 13.13.1 (a)

When my MacBook Pro is closed, but presumably during a short "dark wake", cTiVo seems to be able to grab the updated show information (which is great), sees a new show in one of my subscriptions, queues it up, and starts downloading but gets only 0.000419 (0.0419%) of the way done when it fails with a NSURLErrorDomain Code=-1005 "The network connection was lost."  If the computer remains closed, periodic attempts will continue until the retry limit is hit.

It seems that either the retry count should not be updated, or downloads should be on hold, during a "dark wake"?

**Comment by mackworth** [comment]
Interesting. Could you set Debug Level to Detail, run that scenario again, and post the resulting log (Help>Show logs in Finder)?

**Comment by johnsonea** [comment]
Attached.

[com.cTiVo.cTiVo 2023-05-30--21-40-31-158.log](https://github.com/mackworth/cTiVo/files/11617947/com.cTiVo.cTiVo.2023-05-30--21-40-31-158.log)

**Comment by johnsonea** [comment]
This issue seemed to have gone away with some update to Ventura (somewhere between 13.13.1 and 13.6.1).

**Comment by mackworth** [comment]
Never got around to closing this one...
