### ISSUE TITLE
Update To TIVO Edge, Now cTIVO Is Encoding With Pixelation, Tearing Etc

### ISSUE THREAD

**Issue by themuzikcafe** [mackworth/cTiVo#519]
Hi Hugh,

I hope things are well. 

I recently updated my Tivo from a Bolt to an Edge.

I set the Tivo Edge up, went over to my Mac and it found the new TIVO inside cTIVO immediately. I didn't change anything.

I noticed that when the cTivo encodes the new recordings from the Edge, the video is pixelated and all blurry, and has screen tears. Is there something I need to do as far as encoding? Does the Tivo Edge require a different encoder or setting within cTivo?

Thank you so MUCH for this awesome product!

I look forward to hearing from you soon. Thank you in advance.

EB

**Comment by mackworth** [comment]
Sorry for delay; I don't have much to add, as this is a known issue with the Edge; [see this search](https://www.google.com/search?q=edge+pixelation+tivo) for some history and some recommendations on making it better.
