### ISSUE TITLE
New HandBrake Hardware Acceleration

### ISSUE THREAD

**Issue by alecksjaycubd** [mackworth/cTiVo#524]
So far it works great! I typically just use the defaults so I'm new to all the options. Is there a way to take the HW Default and have it compress a little more? I'd like to get the file size down a bit.

**Comment by mackworth** [comment]
There's not a lot of control over the hardware compressors, but you can set the Quality level (Less quality -> small file sizes). 

To create a format with a different quality level, say 40, go to `Edit>Edit Formats`, select the` HW Default Format`, Duplicate it, then add `-q 40` to the Video options line. 

A few suggestions for experimenting with different levels on the same file

-   Add the quality number to the name of the Format; 
-   Add the Format name to the output filename template in Adv Prefs to help identify which Format created which file.)
- Set `Settings>Advanced>Allow duplicate Downloads` to make things easier.

I should note the difference between H.265 and H.264; from the release notes:
`HB HW Default generates a high-quality H.265 file, while HB HW Small generates a lower-quality but very small H.264 file, about a quarter of the size.` There's also the option of `-e vt_h265`, which I didn't use.
 
I warn that this can be quite a rabbit hole. Handbrake's [guidance is here](https://handbrake.fr/docs/en/latest/technical/video-cq-vs-abr.html), but people have [very strong opinions, e.g. here](https://www.reddit.com/r/handbrake/comments/ybs1dy/macos_h265_10bit_videotoolbox_settings_for/) and [more sources here](https://www.google.com/search?q=handbrake+videotoolbox+quality).


Let me know what you find!

**Comment by mackworth** [comment]
Oh, I should mention that a simpler path may be to download a Decrypted TiVo file, then use the Handbrake user interface to experiment with different quality levels and encoders.

**Comment by alecksjaycubd** [comment]
Thanks. I tried removing the '10 bit' from the 265 hoping that would do the trick and it did. Plenty small enough for me. Thanks!

**Comment by mackworth** [comment]
Great!
