### ISSUE TITLE
Since 9/10/23 Tivo Roamio no longer works!

### ISSUE THREAD

**Issue by Colby3122** [mackworth/cTiVo#526]
I have 3 Tivo's, two roamio's and one bolt, the roamio's all three use the old format, and software version 20.4drc15-848-6-848,
menue software b-todui-quatro-3-14/2018.04.12-1401. I have never had problem before. Did Tivo change something? can I do anything! Please Help ( I use an older Mac with Catalina 10.15.7 software)

Edward Rich
er01@roadrunner.com
805-984-5333

**Comment by mackworth** [comment]
By "no longer works", do you mean that you can't "see" the TiVos? Or that they won't download? Or ..>? Am I reading that the Bolt is working, but both Roamios are not?  And which version of cTiVo do you have?

Can you attach a log file? Help>Show Logs in Finder. Then in finder Command-click on folder > Compress Files, and come back here to post the resulting Zip file (don't attach to an email, as GitHub strips that off).

**Comment by mackworth** [comment]
Checking in again here...

**Comment by Colby3122** [comment]
It turned out ,after weeks of talks with Tivo, that the problem was with Spectrums equipment! Ti did have to switch two of my three machines from MoCa to WiFi, but it all seems to work ok noe! Thank you for the follow up, I had a colonoscopy recently or I would have gotten back to you sooner!

On Sep 19, 2023, at 8:03 PM, Hugh Mackworth ***@***.***> wrote:


Checking in again here...

**Comment by mackworth** [comment]
Good to hear!
