### ISSUE TITLE
Can cTiVo only transfer shows from boxes with active subscriptions?

### ISSUE THREAD

**Issue by DashingDave** [mackworth/cTiVo#529]
When I replaced my Roamio with an Edge, I dropped the TiVo subscription on the older device. Still has a handful of shows on it, and cTiVo can apparently detect it with my MAK, but the count just reads as 0. Is that to be expected?

**Comment by mackworth** [comment]
As far as I can remember, that should work ok. I don’t think they require the subscription to download. 

If you want to set Debug level to Verbose then Reload your old TiVo, then Help>Show logs in Finder, then option-Click>Compress the log, then post it on this thread (don’t attach to a GitHub email), I can take a look to see what’s happening.

**Comment by DashingDave** [comment]
The pertinent info looks to be at the very end at this time mark:
2024-02-24 13:19:25:785
The "old" TiVo is the Roamio; the new one is labeled EDGE2 (because cTiVo is probably detecting my mom's TiVo as the first Edge).
[
[com.cTiVo.cTiVo 2024-02-24--03-18-54-524.log.zip](https://github.com/mackworth/cTiVo/files/14394061/com.cTiVo.cTiVo.2024-02-24--03-18-54-524.log.zip)
](url)

**Comment by mackworth** [comment]
Thanks. That doesn’t look like it’s in Verbose debug mode?

**Comment by DashingDave** [comment]
It looks like the app automatically reverts to Major mode when quitting. I figured I was supposed to set the log to Verbose, delete the old TiVo from the TiVo panel in Settings, quit, and restart so that it would re-find the TiVo on the network. So I tried again setting it to Verbose, then clicking the checkbox in the TiVo panel, and then going to the log file without quitting the app--maybe that's how I was supposed to do it? Here's the log; looks like it has a very long list of channel settings now.
[com.cTiVo.cTiVo 2024-02-24--03-18-54-524.log.zip](https://github.com/mackworth/cTiVo/files/14394147/com.cTiVo.cTiVo.2024-02-24--03-18-54-524.log.zip)

**Comment by mackworth** [comment]
Correct on reverting to Major on restart. You really, really don't want to run Verbose all the time as it sucks up performance, so it turns it off on restart. A hidden feature is that you can hold down Command (I think) and force it to Verbose when you start up.

Nonetheless, the log showed that TiVo's response to the request for Now Playing was "Access Forbidden". So I guess they don't allow that while not subscribed. 

You can confirm this by first going to System Information (on your Tivo and looking for TiVoToGo setting. it should be a,a,a,a.  

If so, then reboot your TiVo, and after it's restarted, click on this link: [https://DVR-6C51.local./nowplaying/index.html](https://DVR-6C51.local./nowplaying/index.html). Then log in with "tivo" as the user name and your MAK as the Password (see Edit>TiVos if you don't have it). That should take you to your playlist.  If that does work, try cTiVo again. If not, then they're not letting you get to it without a subscription.

**Comment by DashingDave** [comment]
My TiVoToGo line was slightly different (i,i,i,i) but I did get an "Access Forbidden/permission denied" message when trying to log into the device's Now Playing list.

Thanks for your assistance though! 8^)

**Comment by mackworth** [comment]
Sure thing. 

I should mention another scenario: you >may< be able to transfer the old TiVo’s shows to your new TiVo directly, and thence download to cTiVo.

**Comment by DashingDave** [comment]
Unfortunately, shows can’t be transferred from a non-Edge model to an Edge w/out using TiVo online, and that requires both devices to have subscriptions.
